% Generate flat annual plots from Voyager COHO one-hour source records.
% All plotted samples come directly from the source CDF files. The plotting
% routine does not interpolate, average, resample, or fill missing values.

programRoot = fileparts(mfilename('fullpath'));
dataRoot = 'Z:\SPART-WORK\Data\Voyager';
outputFolder = fullfile(programRoot, ...
    'UniformLowPrecision_Yearly_Raw');
cacheRoot = fullfile(tempdir, 'Voyager_monthly_cdf_cache');
nasaV2MagFile = fullfile(programRoot, ...
    'NASA_COHO_Voyager2_MAG_1h_2021_2024.html');

report = Voyager_Plot_COHO1h_Raw_Yearly( ...
    'DataRoot', dataRoot, ...
    'OutputFolder', outputFolder, ...
    'CacheRoot', cacheRoot, ...
    'NasaV2MagFile', nasaV2MagFile, ...
    'Spacecraft', [1 2], ...
    'GapBreakHours', 1.5, ...
    'Overwrite', true, ...
    'Visible', false, ...
    'ExportDPI', 150);

fprintf('\nAnnual Voyager COHO one-hour plotting complete.\n');
fprintf('Output folder: %s\n', outputFolder);
fprintf('Manifest rows: %d\n', height(report));
fprintf('Successful/existing figures: %d\n', ...
    sum(ismember(report.Status, {'ok', 'existing'})));
fprintf('Errors: %d\n', sum(strcmp(report.Status, 'error')));
