% Generate the two requested flat Voyager output collections.
programRoot = fileparts(mfilename('fullpath'));
dataRoot = 'Z:\SPART-WORK\Data\Voyager';
cacheRoot = fullfile(tempdir, 'Voyager_monthly_cdf_cache');

highestFolder = fullfile(programRoot, 'HighestPrecision_Segments');
lowFolder = fullfile(programRoot, 'UniformLowPrecision_Monthly_Raw');

highestReport = Voyager_Plot_HighestPrecision_Segments( ...
    'DataRoot', dataRoot, ...
    'OutputFolder', highestFolder, ...
    'CacheRoot', cacheRoot, ...
    'SegmentGapSeconds', 7200, ...
    'LineBreakSeconds', 240, ...
    'MinimumRecords', 2, ...
    'Overwrite', false, ...
    'Visible', false, ...
    'ExportDPI', 120);

lowReport = Voyager_Plot_COHO1h_Raw_Monthly( ...
    'DataRoot', dataRoot, ...
    'OutputFolder', lowFolder, ...
    'CacheRoot', cacheRoot, ...
    'Overwrite', false, ...
    'Visible', false, ...
    'ExportDPI', 150);

fprintf('\nTwo-group Voyager plotting completed.\n');
fprintf('Highest-precision segments: %d\n', height(highestReport));
fprintf('Uniform one-hour months: %d\n', height(lowReport));
fprintf('Highest-precision folder: %s\n', highestFolder);
fprintf('Uniform low-precision folder: %s\n', lowFolder);
