% RUN_VOYAGER_INTERSTELLAR_MONTHLY
% Generate one UTC-calendar-month overview per Voyager spacecraft after its
% accepted heliopause crossing. Edit the configuration values below.

voyagerProgramRoot = fileparts(mfilename('fullpath'));
voyagerDataRoot = 'Z:\SPART-WORK\Data\Voyager';
voyagerHelperRoot = 'C:\Users\Administrator\Documents\FWD_matlab\Voyager_fu';
voyagerOutputRoot = fullfile(voyagerProgramRoot, 'monthly_plots');

% Set true to call Voyager_Download.m for absent products in the requested
% interval. Existing files are size-checked and skipped by that downloader.
voyagerDownloadMissing = false;

addpath(voyagerProgramRoot);
report = Voyager_Plot_Interstellar_Monthly( ...
    'DataRoot', voyagerDataRoot, ...
    'HelperRoot', voyagerHelperRoot, ...
    'OutputRoot', voyagerOutputRoot, ...
    'Spacecraft', [1 2], ...
    'StartTime', [], ...
    'EndTime', 'auto', ...
    'DownloadMissing', voyagerDownloadMissing, ...
    'FillGaps', true, ...
    'MagCadenceSeconds', 48, ...
    'Overwrite', false, ...
    'Visible', false, ...
    'MakeEmptyFigures', true, ...
    'ExportDPI', 180, ...
    'SaveFormats', {'png'}, ...
    'MaxPlotPoints', 25000);

disp(report(:, {'Spacecraft', 'MonthUTC', 'Status', 'MAGRecords', ...
    'PLSRecords', 'LECPValidValues', 'CRSValidValues', ...
    'MAGLowPrecisionFilled', 'MAGInterpolated', 'COHOInterpolated'}));
fprintf('Monthly figures: %s\n', voyagerOutputRoot);
