% Plot the Voyager 1 LECP 0.57-1.78 MeV proton PAD on 2020-07-30
% (DOY 212) with the data treatment of Florinski et al. (2008):
%   * NASA Level-2 per-sector 24-h means for active S1-S7,
%   * arithmetic daily mean of complete COHO 1-h RTN MAG vectors,
%   * mu = vhat dot <B>/|<B>| using the complete three-component field,
%   * normalization by the largest active-sector intensity.
% The public Level-2 product is background-uncorrected. S8 is retained only
% as a diagnostic because the LECP-team correction used by the paper is not
% publicly distributed and cannot be reconstructed by blind S8 subtraction.
% No running average, interpolation, or PAD fit is applied.

programFolder = fileparts(mfilename('fullpath'));
monthlyRoot = fullfile(programFolder, 'Voyager_Interstellar_Monthly');
addpath(monthlyRoot);

dataRoot = fullfile(monthlyRoot, 'Voyager1_Selected_Event_Data');
lecpCDF = fullfile(monthlyRoot, 'Voyager1_LECP_Sectored_Daily', ...
    'voyager1_lecp_p1_sectored_daily_20200622_20200908.cdf');
magCDF = fullfile(dataRoot, 'voyager1', 'coho', '1hr', 'l2', ...
    'merged_mag_plasma', '2020', '07', ...
    'voyager1_coho1hr_merged_mag_plasma_20200701_v01.cdf');

assert(isfile(lecpCDF), 'VoyagerPAD:MissingLECP', ...
    'Missing LECP sectored CDF: %s', lecpCDF);
assert(isfile(magCDF), 'VoyagerPAD:MissingMAG', ...
    'Missing COHO 1-h MAG CDF: %s', magCDF);

outputFolder = fullfile(monthlyRoot, ...
    'Voyager1_Selected_Events_Florinski2008_DailyPAD');
derivedFolder = fullfile(dataRoot, 'derived', ...
    'lecp_pitch_angle_florinski2008_daily');
cacheRoot = fullfile(dataRoot, 'derived', 'cdf_cache');
if ~isfolder(outputFolder), mkdir(outputFolder); end
if ~isfolder(derivedFolder), mkdir(derivedFolder); end
if ~isfolder(cacheRoot), mkdir(cacheRoot); end

lecp = Voyager_Read_CDF_Product(lecpCDF, 'lecp_sector_daily', ...
    'CacheRoot', cacheRoot);
mag = Voyager_Read_CDF_Product(magCDF, 'coho', ...
    'CacheRoot', cacheRoot);

targetDay = datetime(2020, 7, 30, 'TimeZone', 'UTC');
targetEnd = targetDay + days(1);
targetDOY = day(targetDay, 'dayofyear');

energy = lecp.FHDU_Energy;
if size(energy, 1) == numel(lecp.Epoch)
    firstValid = find(any(isfinite(energy), 2), 1);
    assert(~isempty(firstValid), 'VoyagerPAD:MissingEnergy', ...
        'The LECP energy table has no finite record.');
    energy = energy(firstValid, :);
end
energy = energy(:);
[~, p1Index] = min(abs(energy - 0.73));

lecpUse = lecp.Epoch >= targetDay & lecp.Epoch < targetEnd;
dailyFluxRecords = squeeze(lecp.FHDU_SectoredFluxes( ...
    lecpUse, p1Index, 1:8));
dailyFluxRecords = reshape(double(dailyFluxRecords), nnz(lecpUse), 8);
dailyFluxRecords(~isfinite(dailyFluxRecords) | dailyFluxRecords <= 0) = nan;
sectorSampleCount = sum(isfinite(dailyFluxRecords), 1).';
assert(min(sectorSampleCount(1:7)) >= 1, ...
    'VoyagerPAD:LECPCoverage', ...
    'At least one active sector is absent from the Level-2 daily product.');
dailyPublicFlux = nan(8, 1);
for sectorIndex = 1:8
    validFlux = isfinite(dailyFluxRecords(:, sectorIndex));
    dailyPublicFlux(sectorIndex) = ...
        mean(dailyFluxRecords(validFlux, sectorIndex), 'omitnan');
end
if isfield(lecp, 'FHDU_SectoredFluxUncertainties')
    dailySigmaRecords = squeeze(lecp.FHDU_SectoredFluxUncertainties( ...
        lecpUse, p1Index, 1:8));
    dailySigmaRecords = reshape(double(dailySigmaRecords), nnz(lecpUse), 8);
    dailySigmaRecords(~isfinite(dailySigmaRecords) | ...
        dailySigmaRecords < 0) = nan;
    dailyPublicSigma = nan(8, 1);
    for sectorIndex = 1:8
        validFlux = isfinite(dailyFluxRecords(:, sectorIndex));
        current = dailySigmaRecords(validFlux, sectorIndex);
        if all(isfinite(current))
            dailyPublicSigma(sectorIndex) = ...
                sqrt(sum(current.^2)) / sectorSampleCount(sectorIndex);
        end
    end
else
    dailyPublicSigma = nan(8, 1);
end

% Keep the public Level-2 flux unchanged.  Sector 8 is shielded and does not
% represent a foreground look direction, so it is excluded from the PAD.
sectorFlux = dailyPublicFlux;
sectorSigma = dailyPublicSigma;
sectorFlux(8) = nan;
sectorSigma(8) = nan;

magUse = mag.Epoch >= targetDay & mag.Epoch < targetEnd & ...
    isfinite(mag.BR) & isfinite(mag.BT) & isfinite(mag.BN);
assert(any(magUse), 'VoyagerPAD:MissingMAGDay', ...
    'No valid COHO 1-h RTN magnetic-field records on %s.', ...
    string(targetDay, 'yyyy-MM-dd'));
br = mean(mag.BR(magUse), 'omitnan');
bt = mean(mag.BT(magUse), 'omitnan');
bn = mean(mag.BN(magUse), 'omitnan');
if isfield(mag, 'ABS_B')
    meanAbsB = mean(mag.ABS_B(magUse), 'omitnan');
else
    meanAbsB = mean(sqrt(mag.BR(magUse).^2 + ...
        mag.BT(magUse).^2 + mag.BN(magUse).^2), 'omitnan');
end
meanVectorMagnitude = sqrt(br.^2 + bt.^2 + bn.^2);
scanMagnitude = hypot(br, bt);
assert(isfinite(meanVectorMagnitude) && meanVectorMagnitude > 0, ...
    'VoyagerPAD:InvalidMAG', 'The daily mean magnetic-field vector is invalid.');

% Published LECP disk orientation: +T right and +R down.  The vectors below
% are telescope boresights; detected particles enter in the opposite
% direction.  The nominal scan-plane vectors have zero N component, while
% the complete daily mean B vector is retained in the normalization.
sector = (1:8).';
sectorPlotAngleDeg = 112.5 + (sector - 1) * 45;
telescopeUT = cosd(sectorPlotAngleDeg);
telescopeUR = -sind(sectorPlotAngleDeg);
particleUT = -telescopeUT;
particleUR = -telescopeUR;
particleUN = zeros(8, 1);
pitchCosine = (br * particleUR + bt * particleUT + ...
    bn * particleUN) / meanVectorMagnitude;
pitchCosine = max(-1, min(1, pitchCosine));
pitchAngleDeg = acosd(pitchCosine);

active = sector <= 7;
reliable = active & isfinite(sectorFlux) & sectorFlux > 0;
assert(nnz(reliable) == 7, 'VoyagerPAD:InsufficientSectors', ...
    'All seven active sectors are required for a Florinski-style PAD.');

normalizer = max(sectorFlux(reliable));
normalizedIntensity = sectorFlux / normalizer;
normalizedSigma = sectorSigma / normalizer;

quality = repmat( ...
    "valid 24-h active-sector mean; public Level-2 background uncorrected", ...
    8, 1);
quality(~reliable & active) = "excluded: invalid/nonpositive flux";
quality(8) = "excluded: S8 behind sun shield; diagnostic only";
values = table(repmat(targetDay, 8, 1), repmat(targetDOY, 8, 1), ...
    sector, active, reliable, sectorPlotAngleDeg, particleUR, particleUT, ...
    particleUN, pitchCosine, pitchAngleDeg, dailyPublicFlux, ...
    sectorSampleCount, ...
    sectorFlux, sectorSigma, ...
    normalizedIntensity, normalizedSigma, quality, ...
    'VariableNames', {'DateUTC', 'DOY', 'Sector', 'ActiveSector', ...
    'UsedInPAD', 'NominalDiskAngleDeg', 'ParticleUR', 'ParticleUT', ...
    'ParticleUN', 'PitchCosine_FullVectorB', ...
    'PitchAngleDeg_FullVectorB', 'PublicLevel2Flux', ...
    'DailySectorSampleCount', ...
    'Flux_per_cm2_s_sr_MeV', 'FluxUncertainty_1sigma', ...
    'NormalizedIntensity', 'NormalizedUncertainty_1sigma', 'Quality'});

summary = table(targetDay, targetDOY, nnz(magUse), br, bt, bn, ...
    meanAbsB, meanVectorMagnitude, atan2d(bn, scanMagnitude), ...
    mod(atan2d(bt, br), 360), energy(p1Index), normalizer, ...
    targetDay, targetEnd, min(sectorSampleCount(1:7)), ...
    "official NASA Level-2 per-sector 24-h flux; S1-S7 used", ...
    "none; public Level-2 background uncorrected; S8 diagnostic only", ...
    "arithmetic mean of valid COHO 1-h vectors in UTC day", ...
    "Florinski et al. (2008): mu=vhat dot <B>/|<B>|; nominal RT scan plane; no SEDR attitude correction", ...
    'VariableNames', {'DateUTC', 'DOY', 'MAGHourlyRecords', ...
    'BR_daily_nT', 'BT_daily_nT', 'BN_daily_nT', ...
    'MeanAbsB_daily_nT', 'MagnitudeOfMeanVector_nT', ...
    'BElevationDeg', 'BAzimuthDeg', 'P1NominalEnergy_MeV', ...
    'FluxNormalizer', 'LECPWindowStartUTC', 'LECPWindowEndUTC', ...
    'LECPCommonRecords', ...
    'LECPAveraging', 'BackgroundCorrection', ...
    'MAGAveraging', 'PitchAngleMethod'});

valuesCSV = fullfile(derivedFolder, ...
    ['V1_2020_DOY212_LECP_P1_PAD_Florinski2008_', ...
    'publicL2_uncorrected_values.csv']);
summaryCSV = fullfile(derivedFolder, ...
    ['V1_2020_DOY212_LECP_P1_PAD_Florinski2008_', ...
    'publicL2_uncorrected_summary.csv']);
matFile = fullfile(derivedFolder, ...
    ['V1_2020_DOY212_LECP_P1_PAD_Florinski2008_', ...
    'publicL2_uncorrected.mat']);
writetable(values, valuesCSV);
writetable(summary, summaryCSV);
save(matFile, 'values', 'summary', 'lecpCDF', 'magCDF');

figureName = 'Voyager 1 LECP P1 PAD: 2020 DOY 212';
oldFigure = findall(groot, 'Type', 'figure', 'Name', figureName);
if ~isempty(oldFigure), delete(oldFigure); end
fig = figure('Color', 'white', 'Visible', 'on', ...
    'Name', figureName, ...
    'Position', [180 100 510 650]);
ax = axes(fig, 'Position', [0.17 0.13 0.78 0.80]);
hold(ax, 'on');

plotSector = find(reliable);
if all(isfinite(normalizedSigma(plotSector)) & ...
        normalizedSigma(plotSector) > 0)
    errorbar(ax, pitchCosine(plotSector), ...
        normalizedIntensity(plotSector), normalizedSigma(plotSector), ...
        'o', 'Color', [0 0 0], 'MarkerFaceColor', [0 0 0], ...
        'MarkerEdgeColor', [0 0 0], 'MarkerSize', 6.2, ...
        'LineWidth', 1.05, 'CapSize', 7, 'LineStyle', 'none');
else
    plot(ax, pitchCosine(plotSector), normalizedIntensity(plotSector), ...
        'o', 'Color', [0 0 0], 'MarkerFaceColor', [0 0 0], ...
        'MarkerEdgeColor', [0 0 0], 'MarkerSize', 6.2, ...
        'LineStyle', 'none');
end

xlim(ax, [-1.05 1.05]);
ylim(ax, [0 1.12]);
xticks(ax, [-1 -0.5 0 0.5 1]);
yticks(ax, 0:0.2:1.0);
xlabel(ax, '\mu', 'Interpreter', 'tex');
ylabel(ax, 'Normalized intensity');
title(ax, sprintf('2020/%03d', targetDOY), ...
    'FontWeight', 'normal', 'FontSize', 12);
text(ax, 0.97, 0.965, '0.57-1.78 MeV H^+', ...
    'Units', 'normalized', 'HorizontalAlignment', 'right', ...
    'VerticalAlignment', 'top', 'FontSize', 10, 'Interpreter', 'tex');
text(ax, 0.03, 0.965, sprintf('J_{max}=%.3g', normalizer), ...
    'Units', 'normalized', 'HorizontalAlignment', 'left', ...
    'VerticalAlignment', 'top', 'FontSize', 9, 'Interpreter', 'tex');
text(ax, 0.03, 0.915, '24-h mean: 30 Jul; full vector B', ...
    'Units', 'normalized', 'HorizontalAlignment', 'left', ...
    'VerticalAlignment', 'top', 'FontSize', 8.5, ...
    'Interpreter', 'none');
text(ax, 0.03, 0.865, 'public Level-2 flux; background uncorrected', ...
    'Units', 'normalized', 'HorizontalAlignment', 'left', ...
    'VerticalAlignment', 'top', 'FontSize', 8.5, ...
    'Interpreter', 'none');
set(ax, 'Box', 'on', 'TickDir', 'in', 'FontSize', 11, ...
    'LineWidth', 1.0, 'XMinorTick', 'on', 'YMinorTick', 'on', ...
    'TickLength', [0.018 0.018]);
grid(ax, 'off');

pngFile = fullfile(outputFolder, ...
    ['Voyager1_LECP_P1_PAD_2020_DOY212_Florinski2008_', ...
    'publicL2_uncorrected.png']);
pdfFile = fullfile(outputFolder, ...
    ['Voyager1_LECP_P1_PAD_2020_DOY212_Florinski2008_', ...
    'publicL2_uncorrected.pdf']);
exportgraphics(fig, pngFile, 'Resolution', 260);
exportgraphics(fig, pdfFile, 'ContentType', 'vector');

fprintf('\nVoyager 1 2020 DOY 212 PAD completed.\n');
fprintf('Figure: %s\n', pngFile);
fprintf('Values: %s\n', valuesCSV);
fprintf('Summary: %s\n\n', summaryCSV);
disp(values(:, {'Sector', 'UsedInPAD', 'PitchCosine_FullVectorB', ...
    'PitchAngleDeg_FullVectorB', 'Flux_per_cm2_s_sr_MeV', ...
    'NormalizedIntensity', 'NormalizedUncertainty_1sigma'}));
disp(summary(:, {'DateUTC', 'DOY', 'MAGHourlyRecords', ...
    'MeanAbsB_daily_nT', 'BElevationDeg', 'BAzimuthDeg', ...
    'LECPWindowStartUTC', 'LECPWindowEndUTC'}));
