% Run all Voyager 1 intervals selected on slides 4-13 of 0809.pptx.
programRoot = fullfile(fileparts(mfilename('fullpath')), ...
    'Voyager_Interstellar_Monthly');
addpath(programRoot);

report = Voyager1_Plot_Selected_Events( ...
    'DataRoot', 'Z:\SPART-WORK\Data\Voyager', ...
    'OutputFolder', fullfile(programRoot, 'Voyager1_Selected_Events_1h'), ...
    'DatabaseFile', ['Z:\SPART-WORK\Data\Voyager\voyager1\events\', ...
    'Voyager1_Selected_Events_1h.sqlite'], ...
    'OverwriteFigures', true, ...
    'OverwriteDatabase', true, ...
    'Visible', false, ...
    'ExportDPI', 200);

disp(report(:, {'EventID', 'StartUTC', 'EndUTCInclusive', ...
    'EpochRecords', 'MagneticRecords', 'LECPValidValues', ...
    'CRSValidValues', 'Status'}));
