% Replot Voyager 1 event 2020-E01 with the bottom panel replaced by
% LECP P1 (0.57-1.78 MeV H) daily sectored flux, shown as 3-day averages.
% The three curves follow the sector-pair layout used in published LECP
% anisotropy figures. Missing days remain gaps; no interpolation is used.

programRoot = fullfile(fileparts(mfilename('fullpath')), ...
    'Voyager_Interstellar_Monthly');
addpath(programRoot);

outputFolder = fullfile(programRoot, 'Voyager1_Selected_Events_1h');
catalogFile = fullfile(outputFolder, ...
    'Voyager1_Selected_Events_1h_catalog.csv');
dataRoot = fullfile(programRoot, 'Voyager1_Selected_Event_Data');
sectorCDF = fullfile(programRoot, 'Voyager1_LECP_Sectored_Daily', ...
    'voyager1_lecp_hydrogen_sectored_daily_20130301_20220401.cdf');

report = Voyager1_Replot_Selected_Events_PaperStyle( ...
    'DataRoot', dataRoot, ...
    'OutputFolder', outputFolder, ...
    'CatalogFile', catalogFile, ...
    'EventIDs', {'2020-E01'}, ...
    'ContextMonths', 1, ...
    'ShowEventBoundaries', false, ...
    'Overwrite', true, ...
    'Visible', false, ...
    'ExportDPI', 200, ...
    'CRSDisplay', 'lecp_p1_sectors', ...
    'LECPSectoredDailyCDF', sectorCDF, ...
    'LECPSectorAverageDays', 3, ...
    'ReportTag', 'LECP_P1_Sectors_3d_2020E01');

disp(report(:, {'EventID', 'PlotStartUTC', 'PlotEndUTCExclusive', ...
    'MAG1hRecords', 'MAGDailyMeanDays', 'FigureFile', 'Status'}));
