% Plot the Decker et al. (2004) DOY 221 and 225 intervals with the existing
% Voyager event/pitch-angle spectrogram program.
%
% Each event is shown with five days of context on both sides.  The LECP
% 0.57-1.78 MeV sectored product is already averaged over 24 h.  A one-day
% setting therefore preserves the supplied daily records without further
% smoothing or interpolation.

programFolder = fileparts(mfilename('fullpath'));
monthlyRoot = fullfile(programFolder, 'Voyager_Interstellar_Monthly');
addpath(monthlyRoot);

dataRoot = fullfile(monthlyRoot, 'Voyager1_Selected_Event_Data');
outputFolder = fullfile(monthlyRoot, ...
    'Voyager1_2002_DOY221_225_PitchAngle_Spectrograms');
if ~isfolder(outputFolder), mkdir(outputFolder); end

sectorCDF = fullfile(dataRoot, 'voyager1', 'lecp', '1d', 'l2', ...
    'sectored_flux', '2002', '08', ...
    'voyager1_lecp_lev2_daily_sectored_20020801_20020831.cdf');
magCDF = fullfile(dataRoot, 'voyager1', 'coho', '1hr', 'l2', ...
    'merged_mag_plasma', '2002', '08', ...
    'voyager1_coho1hr_merged_mag_plasma_20020801_v01.cdf');
if ~isfile(sectorCDF) || ~isfile(magCDF)
    downloader = fullfile(programFolder, ...
        'download_voyager1_2002_pad_data.py');
    pythonExe = fullfile(getenv('USERPROFILE'), '.cache', ...
        'codex-runtimes', 'codex-primary-runtime', 'dependencies', ...
        'python', 'python.exe');
    if ~isfile(pythonExe), pythonExe = 'python'; end
    [status, output] = system(sprintf('"%s" "%s"', ...
        pythonExe, downloader));
    fprintf('%s\n', output);
    assert(status == 0, 'VoyagerSpectrogram:DownloadFailed', ...
        'Programmatic CDAWeb download failed.');
end

utc = 'UTC';
eventID = ["2002-DOY221"; "2002-DOY225"];
startUTC = [datetime(2002, 8, 9, 'TimeZone', utc); ...
    datetime(2002, 8, 13, 'TimeZone', utc)];
endUTCInclusive = startUTC;
endUTCExclusive = startUTC + days(1);
catalog = table(eventID, startUTC, endUTCInclusive, endUTCExclusive, ...
    'VariableNames', {'EventID', 'StartUTC', 'EndUTCInclusive', ...
    'EndUTCExclusive'});
catalogFile = fullfile(outputFolder, ...
    'Voyager1_2002_DOY221_225_spectrogram_catalog.csv');
writetable(catalog, catalogFile);

pitchAngleDataFolder = fullfile(dataRoot, 'derived', ...
    'lecp_pitch_angle_daily');
cacheRoot = fullfile(dataRoot, 'derived', 'cdf_cache');

report = Voyager1_Replot_Selected_Events_PaperStyle( ...
    'DataRoot', dataRoot, ...
    'OutputFolder', outputFolder, ...
    'CatalogFile', catalogFile, ...
    'EventIDs', cellstr(eventID), ...
    'ContextMonths', 0, ...
    'ContextDays', 5, ...
    'ShowEventBoundaries', false, ...
    'Overwrite', true, ...
    'Visible', true, ...
    'ExportDPI', 220, ...
    'LECPDailyAverage', true, ...
    'CRSDisplay', 'lecp_p1_pitch_angle', ...
    'LECPSectoredDailyCDF', sectorCDF, ...
    'LECPSectorAverageDays', 1, ...
    'PitchAngleMethod', 'florinski2008', ...
    'LECPBackgroundMode', 's8_daily_approx', ...
    'MinimumDailyCoverageFraction', 0.50, ...
    'MinimumPitchAngleSpanDeg', 45, ...
    'PitchAngleDataFolder', pitchAngleDataFolder, ...
    'CacheRoot', cacheRoot, ...
    'ReportTag', 'Decker2004_DOY221_225_PA_spectrogram_1d');

disp(report(:, {'EventID', 'PlotStartUTC', 'PlotEndUTCExclusive', ...
    'MAG1hRecords', 'MAGDailyMeanDays', 'FigureFile', ...
    'PitchAngleDataFile', 'Status'}));
