% Plot every vertical-line event marked in Case1.pptx.
%
% Event days were obtained from the PowerPoint line-shape x coordinates and
% the true January-1 to January-1 axes of the embedded annual plots.  Each
% coordinate was rounded to the nearest UTC calendar day.  Every output
% covers the event day and seven complete days on each side.
%
% Voyager 1: six-panel paper-style figure.  The LECP P1 pitch-angle panel
%             is drawn only where a time-matched reconstructed attitude /
%             sector-pointing file exists.  No nominal RT-plane fallback
%             is allowed in this run.
% Voyager 2: the same magnetic/particle layout, with the public CRS energy
%             spectrogram in the bottom panel.  The V1-only sector geometry
%             is deliberately not transferred to V2.

try
    feature('homeSessionManagerImpl', false);
catch
end

programFolder = fileparts(mfilename('fullpath'));
monthlyRoot = fullfile(programFolder, 'Voyager_Interstellar_Monthly');
addpath(monthlyRoot);

dataRoot = fullfile(monthlyRoot, 'Case1_Selected_Event_Data');
outputFolder = fullfile(monthlyRoot, ...
    'Case1_PPT_VerticalLine_Events_7d_AttitudeCorrected');
if ~isfolder(outputFolder), mkdir(outputFolder); end
pythonExe = fullfile(getenv('USERPROFILE'), '.cache', ...
    'codex-runtimes', 'codex-primary-runtime', 'dependencies', ...
    'python', 'python.exe');
if ~isfile(pythonExe), pythonExe = 'python'; end

% Download only the NASA COHO months touched by the requested windows.
downloadManifest = fullfile(dataRoot, ...
    'case1_ppt_coho_download_manifest.json');
if ~isfile(downloadManifest)
    downloader = fullfile(programFolder, ...
        'download_case1_ppt_event_data.py');
    [downloadStatus, downloadOutput] = system(sprintf( ...
        '"%s" "%s"', pythonExe, downloader));
    fprintf('%s\n', downloadOutput);
    assert(downloadStatus == 0 && isfile(downloadManifest), ...
        'VoyagerCase1:DownloadFailed', ...
        'Programmatic NASA COHO download failed.');
end

eventDates = [ ...
    % Slide 1, Voyager 1, year 2020
    1 1 1; 1 1 2; 1 1 3; ...
    % Slide 2, Voyager 1, year 2018
    1 2 1; 1 2 2; 1 2 3; 1 2 4; 1 2 5; 1 2 6; 1 2 7; 1 2 8; 1 2 9; ...
    % Slide 3, Voyager 1, year 2019
    1 3 1; 1 3 2; 1 3 3; 1 3 4; 1 3 5; 1 3 6; ...
    % Slide 4, Voyager 1, year 2021
    1 4 1; 1 4 2; 1 4 3; ...
    % Slide 5, Voyager 1, year 2017
    1 5 1; 1 5 2; 1 5 3; 1 5 4; 1 5 5; 1 5 6; 1 5 7; ...
    % Slide 6, Voyager 1, year 2016
    1 6 1; 1 6 2; ...
    % Slide 7, Voyager 1, year 2015
    1 7 1; 1 7 2; 1 7 3; 1 7 4; 1 7 5; ...
    % Slide 8, Voyager 1, year 2014
    1 8 1; 1 8 2; 1 8 3; 1 8 4; 1 8 5; 1 8 6; ...
    % Slide 9, Voyager 1, year 2013
    1 9 1; 1 9 2; 1 9 3; 1 9 4; ...
    % Slides 11--12, Voyager 2
    2 11 1; 2 11 2; 2 11 3; 2 12 1];

eventText = [ ...
    "2020-05-22"; "2020-09-23"; "2020-12-06"; ...
    "2018-01-08"; "2018-02-02"; "2018-04-24"; "2018-07-07"; ...
    "2018-08-03"; "2018-08-23"; "2018-10-30"; "2018-11-10"; ...
    "2018-12-12"; ...
    "2019-05-02"; "2019-05-27"; "2019-05-30"; "2019-06-13"; ...
    "2019-06-24"; "2019-08-26"; ...
    "2021-01-06"; "2021-05-06"; "2021-05-17"; ...
    "2017-01-15"; "2017-05-24"; "2017-07-18"; "2017-08-15"; ...
    "2017-09-16"; "2017-10-10"; "2017-12-06"; ...
    "2016-09-13"; "2016-09-22"; ...
    "2015-03-04"; "2015-10-04"; "2015-10-13"; "2015-12-19"; ...
    "2015-12-28"; ...
    "2014-04-17"; "2014-05-21"; "2014-08-12"; "2014-08-28"; ...
    "2014-09-21"; "2014-12-13"; ...
    "2013-01-09"; "2013-05-30"; "2013-09-11"; "2013-12-29"; ...
    "2019-02-24"; "2019-09-20"; "2019-11-13"; "2020-11-21"];

assert(size(eventDates, 1) == numel(eventText), ...
    'VoyagerCase1:CatalogLength', 'Event metadata lengths differ.');

spacecraft = eventDates(:, 1);
sourceSlide = eventDates(:, 2);
sourceLine = eventDates(:, 3);
startUTC = datetime(eventText, 'InputFormat', 'yyyy-MM-dd', ...
    'TimeZone', 'UTC');
endUTCInclusive = startUTC;
endUTCExclusive = startUTC + caldays(1);
eventID = strings(numel(startUTC), 1);
for ii = 1:numel(startUTC)
    eventID(ii) = sprintf('Case1-S%02d-L%02d', ...
        sourceSlide(ii), sourceLine(ii));
end

catalog = table(cellstr(eventID), startUTC, endUTCInclusive, ...
    endUTCExclusive, spacecraft, sourceSlide, sourceLine, ...
    'VariableNames', {'EventID', 'StartUTC', 'EndUTCInclusive', ...
    'EndUTCExclusive', 'Spacecraft', 'SourceSlide', 'SourceLine'});

allCatalogFile = fullfile(outputFolder, ...
    'Case1_PPT_vertical_line_event_catalog_all.csv');
v1CatalogFile = fullfile(outputFolder, ...
    'Case1_PPT_vertical_line_event_catalog_V1.csv');
v2CatalogFile = fullfile(outputFolder, ...
    'Case1_PPT_vertical_line_event_catalog_V2.csv');
writetable(catalog, allCatalogFile);
writetable(catalog(spacecraft == 1, :), v1CatalogFile);
writetable(catalog(spacecraft == 2, :), v2CatalogFile);

pitchAngleDataFolder = fullfile(dataRoot, 'derived', ...
    'lecp_pitch_angle_attitude_required_daily');
if ~isfolder(pitchAngleDataFolder), mkdir(pitchAngleDataFolder); end
cacheRoot = fullfile(dataRoot, 'derived', 'cdf_cache');
if ~isfolder(cacheRoot), mkdir(cacheRoot); end

v1SectoredCDF = fullfile(dataRoot, 'voyager1', 'lecp', '1d', 'l2', ...
    'sectored_flux', '2013-2021', ...
    'voyager1_lecp_p1_sectored_daily_case1_20130102_20210525.cdf');
if ~isfile(v1SectoredCDF)
    lecpDownloader = fullfile(programFolder, ...
        'download_case1_voyager1_lecp_daily.py');
    [lecpStatus, lecpOutput] = system(sprintf( ...
        '"%s" "%s"', pythonExe, lecpDownloader));
    fprintf('%s\n', lecpOutput);
    assert(lecpStatus == 0, 'VoyagerCase1:LECPDownloadFailed', ...
        'Programmatic NASA LECP daily-sector download failed.');
end
assert(isfile(v1SectoredCDF), 'VoyagerCase1:MissingV1SectorCDF', ...
    'Required Voyager 1 daily sectored CDF is unavailable.');

% Required schema is documented in ASSUMPTIONS_AND_DATA_AUDIT.txt.  The
% expected file is intentionally allowed to be absent: affected pitch-angle
% bins then remain NaN and panel (f) explicitly states that it is withheld.
% No fixed scan-plane vector is substituted.
v1SectorPointingFile = fullfile(dataRoot, 'voyager1', 'lecp', ...
    'attitude', 'voyager1_lecp_sector_pointing_sedr_aacs_2013_2021.csv');

reportV1 = Voyager1_Replot_Selected_Events_PaperStyle( ...
    'Spacecraft', 1, ...
    'DataRoot', dataRoot, ...
    'OutputFolder', outputFolder, ...
    'CatalogFile', v1CatalogFile, ...
    'ReportFolder', outputFolder, ...
    'ReportTag', 'Case1_PPT_V1_7d', ...
    'CacheRoot', cacheRoot, ...
    'ContextMonths', 0, ...
    'ContextDays', 7, ...
    'ShowEventBoundaries', false, ...
    'Overwrite', true, ...
    'Visible', false, ...
    'ExportDPI', 220, ...
    'LECPDailyAverage', false, ...
    'CRSDisplay', 'lecp_p1_pitch_angle', ...
    'LECPSectoredDailyCDF', v1SectoredCDF, ...
    'LECPSectorAverageDays', 1, ...
    'PitchAngleMethod', 'attitude_file', ...
    'LECPSectorPointingFile', v1SectorPointingFile, ...
    'LECPBackgroundMode', 'none', ...
    'MinimumDailyCoverageFraction', 0.50, ...
    'MinimumDailySectorSamples', 1, ...
    'MinimumPitchAngleSpanDeg', 45, ...
    'PitchAngleDataFolder', pitchAngleDataFolder, ...
    'LineYMarginFraction', 0.08);

reportV2 = Voyager1_Replot_Selected_Events_PaperStyle( ...
    'Spacecraft', 2, ...
    'DataRoot', dataRoot, ...
    'OutputFolder', outputFolder, ...
    'CatalogFile', v2CatalogFile, ...
    'ReportFolder', outputFolder, ...
    'ReportTag', 'Case1_PPT_V2_7d', ...
    'CacheRoot', cacheRoot, ...
    'ContextMonths', 0, ...
    'ContextDays', 7, ...
    'ShowEventBoundaries', false, ...
    'Overwrite', true, ...
    'Visible', false, ...
    'ExportDPI', 220, ...
    'LECPDailyAverage', false, ...
    'CRSDisplay', 'spectrogram', ...
    'LineYMarginFraction', 0.08);

report = [reportV1; reportV2];
combinedReportFile = fullfile(outputFolder, ...
    'Case1_PPT_vertical_line_event_plot_manifest_all.csv');
writetable(report, combinedReportFile);
save(fullfile(outputFolder, ...
    'Case1_PPT_vertical_line_event_plot_report_all.mat'), ...
    'report', 'catalog', 'reportV1', 'reportV2', '-v7.3');

auditFile = fullfile(outputFolder, 'ASSUMPTIONS_AND_DATA_AUDIT.txt');
writeCase1AssumptionAudit(auditFile, v1SectoredCDF, ...
    v1SectorPointingFile, outputFolder);

fprintf('\nCase1 vertical-line event plotting complete.\n');
fprintf('Catalog events: %d (V1=%d, V2=%d)\n', ...
    height(catalog), sum(spacecraft == 1), sum(spacecraft == 2));
fprintf('Successful/existing figures: %d\n', ...
    sum(ismember(report.Status, {'ok', 'existing'})));
fprintf('Plot errors: %d\n', sum(strcmp(report.Status, 'plot_error')));
fprintf('Output folder: %s\n', outputFolder);

function writeCase1AssumptionAudit(fileName, sectorFluxFile, ...
        pointingFile, outputFolder)
fid = fopen(fileName, 'wt');
assert(fid >= 0, 'VoyagerCase1:AuditWriteFailed', ...
    'Unable to write assumption audit: %s', fileName);
cleanup = onCleanup(@() fclose(fid));
lines = [ ...
"CASE1 VOYAGER EVENT FIGURES: ASSUMPTIONS AND DATA AUDIT";
"Generated by run_case1_ppt_all_vertical_line_events_7d.m";
"";
"A. Event definitions and time window";
"A1. Each event time is the nearest UTC calendar day inferred from a vertical-line x coordinate in Case1.pptx.";
"A2. Each plot covers that UTC event day plus seven complete calendar days before and seven complete calendar days after it.";
"A3. No event time finer than one day is claimed by the PowerPoint extraction.";
"";
"B. Magnetic field";
"B1. COHOWeb one-hour MAG records provide |B|, BR, BT, and BN in RTN coordinates.";
"B2. Black curves show valid one-hour source records. Gaps longer than 1.5 h are broken; no interpolation bridges them.";
"B3. Gray curves are arithmetic UTC-day means of the available one-hour values. Missing hours have zero weight and are never inserted as zeros.";
"B4. For a pitch-angle day, BR, BT, and BN are averaged over identical records for which all three components are finite.";
"B5. Daily B direction RMS is the root-mean-square angular separation of valid hourly B vectors from the daily vector mean.";
"";
"C. LECP line-flux panel";
"C1. The three public COHO LECP proton channels are plotted at their supplied cadence.";
"C2. Only finite positive fluxes are shown on the logarithmic axis. Missing records remain gaps.";
"C3. No background subtraction, smoothing, interpolation, or fit is applied to this panel.";
"";
"D. LECP 0.57-1.78 MeV sectored data";
"D1. Input is the public Voyager 1 daily Level-2 sectored-flux CDF listed below.";
"D2. The P1 channel is selected by the energy metadata value nearest 0.73 MeV; its nominal range is labelled 0.57-1.78 MeV.";
"D3. Sectors S1-S7 are treated as active viewing sectors. S8 is retained only as a blocked/background diagnostic.";
"D4. Public Level-2 values are retained without S8 subtraction because an event-specific LECP-team background series is absent.";
"D5. Daily input records are grouped by UTC day. Finite values are averaged sector by sector; NaN values have zero weight and zero values are not manufactured.";
"D6. A daily uncertainty is propagated as sqrt(sum(sigma_i^2))/N only when every contributing uncertainty is finite.";
"";
"E. Spacecraft attitude and pitch angles -- corrected rule";
"E1. No value of uN is imposed in this run.";
"E2. No fixed RT scan plane, fixed spacecraft clock angle, fixed 45-degree sector direction, or nominal attitude is used in this run.";
"E3. A pitch angle is accepted only from a time-matched external reconstructed pointing file.";
"E4. Accepted file schema 1: EpochUTC plus PA_S1_deg through PA_S8_deg.";
"E5. Accepted file schema 2: EpochUTC plus ParticleUR_Sn, ParticleUT_Sn, ParticleUN_Sn for n=1...8. These must be RTN particle-arrival vectors; the program normalizes each complete vector before dotting it with B/|B|.";
"E6. Telescope look/boresight vectors must be sign-reversed by the provider before they are named ParticleU*. The program performs no hidden sign choice.";
"E7. Exactly one pointing row must match each UTC day. Missing or duplicate rows are rejected. No attitude interpolation is performed.";
"E8. The current public daily CDF contains flux, uncertainty, energy, epoch, and sector fields; it contains no reconstructed attitude or sector-pitch-angle field.";
"E9. The configured reconstructed pointing file is currently absent. V1 panel (f) is therefore withheld and its exported PA/Mu values are NaN. This is intentional data-quality handling.";
"";
"F. PAD quality filters, applied only when real pointing is supplied";
"F1. All seven active sectors must have finite positive flux and finite pitch angle.";
"F2. The pitch-angle-center span must exceed 45 degrees.";
"F3. A valid daily mean vector B is required.";
"F4. Days with within-day B direction RMS above 20 degrees are excluded.";
"F5. Days with median relative sector-flux uncertainty above 1 are excluded.";
"F6. The spectrogram display merges pitch-angle centers separated by at most 2 degrees using an arithmetic mean for display only; original sector rows remain in CSV.";
"F7. Display-cell PA edges are midpoints between sorted sector-center PAs, extrapolated at the ends and clipped to 0-180 degrees. They are display bins and do not claim the physical angular response/FOV.";
"F8. Color values are log10 of positive differential flux. Color limits use robust percentiles of the retained values.";
"";
"G. Other plotting choices";
"G1. Grid lines are off. Event-boundary vertical lines are off.";
"G2. Linear y limits use the finite plotted values plus an 8 percent margin.";
"G3. Voyager 2 has no V1 LECP pointing calculation in this run; its bottom panel remains the public CRS proton spectrogram.";
"";
"Input daily sector flux CDF: " + string(sectorFluxFile);
"Configured pointing file: " + string(pointingFile);
"Pointing file exists at run time: " + string(isfile(pointingFile));
"Output folder: " + string(outputFolder)];
for ii = 1:numel(lines)
    fprintf(fid, '%s\n', char(lines(ii)));
end
end
