% Replot Voyager 1 event 2020-E01 using the PAD construction described by
% Florinski, Decker, and le Roux (2008), doi:10.1029/2007JA012859.
% Seven active LECP P1 sectors use NASA's Level-2 daily sector fluxes.
% Pitch cosine is the dot product of each nominal incoming sector axis with
% the complete daily mean MAG vector.  Public Level-2 values are retained
% without an extra S8 subtraction: the event-specific LECP-team penetrating-
% particle background series used by Florinski et al. is not public.  This
% limitation affects intensity, while the pitch angles remain determined by
% sector geometry and vector B.  No fit or interpolation is applied.

% Work around an R2026a Windows crash in the recent-artifacts/Home service
% observed on this machine.  This affects only the current MATLAB session.
try
    feature('homeSessionManagerImpl', false);
catch
    % Older MATLAB releases may not expose this internal feature switch.
end

programRoot = fullfile(fileparts(mfilename('fullpath')), ...
    'Voyager_Interstellar_Monthly');
addpath(programRoot);

catalogFolder = fullfile(programRoot, 'Voyager1_Selected_Events_1h');
outputFolder = fullfile(programRoot, ...
    'Voyager1_Selected_Events_Florinski2008_DailyPAD');
catalogFile = fullfile(catalogFolder, ...
    'Voyager1_Selected_Events_1h_catalog.csv');
dataRoot = fullfile(programRoot, 'Voyager1_Selected_Event_Data');
sectorCDF = fullfile(programRoot, 'Voyager1_LECP_Sectored_Daily', ...
    'voyager1_lecp_p1_sectored_daily_20200622_20200908.cdf');
if ~isfile(sectorCDF)
    downloader = fullfile(fileparts(mfilename('fullpath')), ...
        'download_voyager1_2020e01_lecp_daily.py');
    pythonExe = fullfile(getenv('USERPROFILE'), '.cache', ...
        'codex-runtimes', 'codex-primary-runtime', 'dependencies', ...
        'python', 'python.exe');
    if ~isfile(pythonExe), pythonExe = 'python'; end
    [downloadStatus, downloadOutput] = system(sprintf( ...
        '"%s" "%s"', pythonExe, downloader));
    fprintf('%s\n', downloadOutput);
    assert(downloadStatus == 0 && isfile(sectorCDF), ...
        'VoyagerPAD:Level2DailyDownload', ...
        'Programmatic download of LECP Level-2 daily sector flux failed.');
end
pitchAngleDataFolder = fullfile(dataRoot, 'derived', ...
    'lecp_pitch_angle_florinski2008_daily');

report = Voyager1_Replot_Selected_Events_PaperStyle( ...
    'DataRoot', dataRoot, ...
    'OutputFolder', outputFolder, ...
    'CatalogFile', catalogFile, ...
    'EventIDs', {'2020-E01'}, ...
    'ContextMonths', 1, ...
    'ShowEventBoundaries', false, ...
    'Overwrite', true, ...
    'Visible', true, ...
    'ExportDPI', 200, ...
    'CRSDisplay', 'lecp_p1_pitch_angle', ...
    'LECPSectoredDailyCDF', sectorCDF, ...
    'LECPSectorAverageDays', 1, ...
    'PitchAngleMethod', 'florinski2008', ...
    'LECPBackgroundMode', 'none', ...
    'MinimumDailyCoverageFraction', 0.50, ...
    'MinimumDailySectorSamples', 6, ...
    'MinimumPitchAngleSpanDeg', 45, ...
    'PitchAngleDataFolder', pitchAngleDataFolder, ...
    'ReportTag', ...
    'LECP_P1_PitchAngle_Florinski2008_1d_publicL2_uncorrected_2020E01');

disp(report(:, {'EventID', 'PlotStartUTC', 'PlotEndUTCExclusive', ...
    'MAG1hRecords', 'MAGDailyMeanDays', 'FigureFile', ...
    'PitchAngleDataFile', 'Status'}));
