% Replot Voyager 1 events with one point-line panel per CRS energy channel.
programRoot = fullfile(fileparts(mfilename('fullpath')), ...
    'Voyager_Interstellar_Monthly');
addpath(programRoot);

catalogFolder = fullfile(programRoot, 'Voyager1_Selected_Events_1h');
outputFolder = fullfile(programRoot, ...
    'Voyager1_Selected_Events_1h_LECP_DailyMean_CRS_ChannelPanels');
catalogFile = fullfile(catalogFolder, ...
    'Voyager1_Selected_Events_1h_catalog.csv');

report = Voyager1_Replot_Selected_Events_PaperStyle( ...
    'DataRoot', 'Z:\SPART-WORK\Data\Voyager', ...
    'OutputFolder', outputFolder, ...
    'CatalogFile', catalogFile, ...
    'ContextMonths', 1, ...
    'LECPDailyAverage', true, ...
    'CRSDisplay', 'channel_panels', ...
    'LineYMarginFraction', 0.06, ...
    'Overwrite', true, ...
    'Visible', false, ...
    'ExportDPI', 200);

disp(report(:, {'EventID', 'PlotStartUTC', 'PlotEndUTCExclusive', ...
    'MAG1hRecords', 'MAGDailyMeanDays', 'DirectPlasmaVariables', 'Status'}));
