% Replot Voyager 1 event 2020-E01 with a LECP P1 pitch-angle flux panel.
% Sector-center pitch angles use the nominal LECP scan plane parallel to RT.
% The sectored flux is a strict centered 3-day mean of daily measurements;
% gaps remain blank and no interpolation is used.

programRoot = fullfile(fileparts(mfilename('fullpath')), ...
    'Voyager_Interstellar_Monthly');
addpath(programRoot);

outputFolder = fullfile(programRoot, 'Voyager1_Selected_Events_1h');
catalogFile = fullfile(outputFolder, ...
    'Voyager1_Selected_Events_1h_catalog.csv');
dataRoot = fullfile(programRoot, 'Voyager1_Selected_Event_Data');
sectorCDF = fullfile(programRoot, 'Voyager1_LECP_Sectored_Daily', ...
    'voyager1_lecp_hydrogen_sectored_daily_20130301_20220401.cdf');
pitchAngleDataFolder = fullfile(dataRoot, 'derived', ...
    'lecp_pitch_angle_daily');

report = Voyager1_Replot_Selected_Events_PaperStyle( ...
    'DataRoot', dataRoot, ...
    'OutputFolder', outputFolder, ...
    'CatalogFile', catalogFile, ...
    'EventIDs', {'2020-E01'}, ...
    'ContextMonths', 1, ...
    'ShowEventBoundaries', false, ...
    'Overwrite', true, ...
    'Visible', true, ...
    'ExportDPI', 200, ...
    'CRSDisplay', 'lecp_p1_pitch_angle', ...
    'LECPSectoredDailyCDF', sectorCDF, ...
    'LECPSectorAverageDays', 3, ...
    'PitchAngleDataFolder', pitchAngleDataFolder, ...
    'ReportTag', 'LECP_P1_PitchAngle_nominalRT_3d_2020E01');

disp(report(:, {'EventID', 'PlotStartUTC', 'PlotEndUTCExclusive', ...
    'MAG1hRecords', 'MAGDailyMeanDays', 'FigureFile', ...
    'PitchAngleDataFile', 'Status'}));
