% Replot Voyager 1 event 2020-E01 with a native-cadence LECP P1 pitch-angle
% diagnostic.  It uses the complete hourly MAG vector and the same nominal
% sector geometry as the Florinski calculation, but deliberately keeps the
% NASA hourly cadence.  The public Level-2 flux is shown without an extra S8
% subtraction because the LECP-team background series is not public.  This
% remains a cadence diagnostic, not the paper's 24-h PAD product.  Gaps remain
% blank and no interpolation is used.

programRoot = fullfile(fileparts(mfilename('fullpath')), ...
    'Voyager_Interstellar_Monthly');
addpath(programRoot);

outputFolder = fullfile(programRoot, 'Voyager1_Selected_Events_1h');
catalogFile = fullfile(outputFolder, ...
    'Voyager1_Selected_Events_1h_catalog.csv');
dataRoot = fullfile(programRoot, 'Voyager1_Selected_Event_Data');
sectorCDF = fullfile(programRoot, 'Voyager1_LECP_Sectored_Hourly', ...
    'voyager1_lecp_p1_sectored_hourly_20200622_20200908.cdf');
pitchAngleDataFolder = fullfile(dataRoot, 'derived', ...
    'lecp_pitch_angle_hourly');

report = Voyager1_Replot_Selected_Events_PaperStyle( ...
    'DataRoot', dataRoot, ...
    'OutputFolder', outputFolder, ...
    'CatalogFile', catalogFile, ...
    'EventIDs', {'2020-E01'}, ...
    'ContextMonths', 1, ...
    'ShowEventBoundaries', false, ...
    'Overwrite', true, ...
    'Visible', true, ...
    'ExportDPI', 200, ...
    'CRSDisplay', 'lecp_p1_pitch_angle', ...
    'LECPSectoredDailyCDF', sectorCDF, ...
    'LECPSectorAverageDays', 0, ...
    'PitchAngleMethod', 'fullvector_native', ...
    'LECPBackgroundMode', 'none', ...
    'PitchAngleDataFolder', pitchAngleDataFolder, ...
    'ReportTag', ...
    'LECP_P1_PitchAngle_fullVector_native_publicL2_uncorrected_2020E01');

disp(report(:, {'EventID', 'PlotStartUTC', 'PlotEndUTCExclusive', ...
    'MAG1hRecords', 'MAGDailyMeanDays', 'FigureFile', ...
    'PitchAngleDataFile', 'Status'}));
