% Replot all Voyager 1 selected events with COHO one-hour magnetic panels.
programRoot = fullfile(fileparts(mfilename('fullpath')), ...
    'Voyager_Interstellar_Monthly');
addpath(programRoot);

report = Voyager1_Replot_Selected_Events_PaperStyle( ...
    'DataRoot', 'Z:\SPART-WORK\Data\Voyager', ...
    'OutputFolder', fullfile(programRoot, 'Voyager1_Selected_Events_1h'), ...
    'ContextMonths', 1, ...
    'ShowEventBoundaries', false, ...
    'Overwrite', true, ...
    'Visible', false, ...
    'ExportDPI', 200);

disp(report(:, {'EventID', 'PlotStartUTC', 'PlotEndUTCExclusive', ...
    'MAG1hRecords', 'MAGDailyMeanDays', 'DirectPlasmaVariables', 'Status'}));
