% Replot the four consecutive Figure 4 days in Florinski et al. (2008)
% with the revised full-vector daily pitch-angle program.
%
% Paper interval: 2004 DOY 221-224 (2004-08-08 through 2004-08-11 UTC)
% Plot interval:  2004 DOY 218-227 (2004-08-05 through 2004-08-14 UTC)
%
% Processing:
%   * black MAG: original COHO one-hour records
%   * light-gray MAG: daily means formed from the one-hour records
%   * LECP P1: separate 24 h averages of public Level-1 sectors S1-S7
%   * pitch angle: complete daily mean <BR,BT,BN> and nominal RT scan plane
%   * no interpolation, no PAD fit, and no S8 background subtraction

% Work around the R2026a recent-artifacts/Home-service crash seen on this PC.
% The setting applies only to the current MATLAB session.
try
    feature('homeSessionManagerImpl', false);
catch
end

programFolder = fileparts(mfilename('fullpath'));
monthlyRoot = fullfile(programFolder, 'Voyager_Interstellar_Monthly');
addpath(monthlyRoot);

dataRoot = fullfile(monthlyRoot, 'Voyager1_Selected_Event_Data');
outputFolder = fullfile(monthlyRoot, ...
    'Voyager1_2004_Florinski_Figure4_NewDailyPAD_NoFit');
if ~isfolder(outputFolder), mkdir(outputFolder); end

sectorCDF = fullfile(dataRoot, 'voyager1', 'lecp', 'level1', ...
    'sectored_rates', '2004', '08', ...
    'voyager1_lecp_lev1_sectored_rates_20040801_20040831.cdf');
magCDF = fullfile(dataRoot, 'voyager1', 'coho', '1hr', 'l2', ...
    'merged_mag_plasma', '2004', '08', ...
    'voyager1_coho1hr_merged_mag_plasma_20040801_v01.cdf');

if ~isfile(sectorCDF) || ~isfile(magCDF)
    downloader = fullfile(programFolder, ...
        'download_voyager1_2004_figure4_data.py');
    pythonExe = fullfile(getenv('USERPROFILE'), '.cache', ...
        'codex-runtimes', 'codex-primary-runtime', 'dependencies', ...
        'python', 'python.exe');
    if ~isfile(pythonExe), pythonExe = 'python'; end
    [status, output] = system(sprintf('"%s" "%s"', ...
        pythonExe, downloader));
    fprintf('%s\n', output);
    assert(status == 0 && isfile(sectorCDF) && isfile(magCDF), ...
        'VoyagerPAD:DownloadFailed', ...
        'Programmatic CDAWeb download failed.');
end

utc = 'UTC';
eventID = "2004-Fig4-DOY221-224";
startUTC = datetime(2004, 8, 8, 'TimeZone', utc);
endUTCInclusive = datetime(2004, 8, 11, 'TimeZone', utc);
endUTCExclusive = datetime(2004, 8, 12, 'TimeZone', utc);
catalog = table(eventID, startUTC, endUTCInclusive, endUTCExclusive, ...
    'VariableNames', {'EventID', 'StartUTC', 'EndUTCInclusive', ...
    'EndUTCExclusive'});
catalogFile = fullfile(outputFolder, ...
    'Voyager1_2004_Florinski_Figure4_catalog.csv');
writetable(catalog, catalogFile);

pitchAngleDataFolder = fullfile(dataRoot, 'derived', ...
    'lecp_pitch_angle_florinski2008_daily');
cacheRoot = fullfile(dataRoot, 'derived', 'cdf_cache');

report = Voyager1_Replot_Selected_Events_PaperStyle( ...
    'DataRoot', dataRoot, ...
    'OutputFolder', outputFolder, ...
    'CatalogFile', catalogFile, ...
    'EventIDs', {char(eventID)}, ...
    'ContextMonths', 0, ...
    'ContextDays', 3, ...
    'ShowEventBoundaries', false, ...
    'Overwrite', true, ...
    'Visible', true, ...
    'ExportDPI', 220, ...
    'LECPDailyAverage', true, ...
    'CRSDisplay', 'lecp_p1_pitch_angle', ...
    'LECPSectoredDailyCDF', sectorCDF, ...
    'LECPSectorAverageDays', 1, ...
    'PitchAngleMethod', 'florinski2008', ...
    'LECPBackgroundMode', 'none', ...
    'MinimumDailyCoverageFraction', 0.50, ...
    'MinimumDailySectorSamples', 6, ...
    'MinimumPitchAngleSpanDeg', 45, ...
    'PitchAngleDataFolder', pitchAngleDataFolder, ...
    'CacheRoot', cacheRoot, ...
    'ReportTag', ...
    'Florinski2008_Figure4_DOY221_224_NewDailyPAD_NoFit');

disp(report(:, {'EventID', 'PlotStartUTC', 'PlotEndUTCExclusive', ...
    'MAG1hRecords', 'MAGDailyMeanDays', 'FigureFile', ...
    'PitchAngleDataFile', 'Status'}));
