% Replot all Voyager 1 selected events with daily-mean LECP flux curves.
programRoot = fullfile(fileparts(mfilename('fullpath')), ...
    'Voyager_Interstellar_Monthly');
addpath(programRoot);

originalFolder = fullfile(programRoot, 'Voyager1_Selected_Events_1h');
outputFolder = fullfile(programRoot, ...
    'Voyager1_Selected_Events_1h_LECP_DailyMean');
catalogFile = fullfile(originalFolder, ...
    'Voyager1_Selected_Events_1h_catalog.csv');

report = Voyager1_Replot_Selected_Events_PaperStyle( ...
    'DataRoot', 'Z:\SPART-WORK\Data\Voyager', ...
    'OutputFolder', outputFolder, ...
    'CatalogFile', catalogFile, ...
    'ContextMonths', 1, ...
    'LECPDailyAverage', true, ...
    'LineYMarginFraction', 0.06, ...
    'Overwrite', true, ...
    'Visible', false, ...
    'ExportDPI', 200);

disp(report(:, {'EventID', 'PlotStartUTC', 'PlotEndUTCExclusive', ...
    'MAG1hRecords', 'MAGDailyMeanDays', 'DirectPlasmaVariables', 'Status'}));
