% Plot every vertical-line event marked in Case1.pptx.
%
% Event days were obtained from the PowerPoint line-shape x coordinates and
% the true January-1 to January-1 axes of the embedded annual plots.  Each
% coordinate was rounded to the nearest UTC calendar day.  Every output
% covers the event day and seven complete days on each side.
%
% Voyager 1: six-panel paper-style figure with the revised Florinski daily
%             LECP P1 pitch-angle panel.
% Voyager 2: the same magnetic/particle layout, with the public CRS energy
%             spectrogram in the bottom panel.  The V1-only sector geometry
%             is deliberately not transferred to V2.

try
    feature('homeSessionManagerImpl', false);
catch
end

programFolder = fileparts(mfilename('fullpath'));
monthlyRoot = fullfile(programFolder, 'Voyager_Interstellar_Monthly');
addpath(monthlyRoot);

dataRoot = fullfile(monthlyRoot, 'Case1_Selected_Event_Data');
outputFolder = fullfile(monthlyRoot, ...
    'Case1_PPT_VerticalLine_Events_7d');
if ~isfolder(outputFolder), mkdir(outputFolder); end
pythonExe = fullfile(getenv('USERPROFILE'), '.cache', ...
    'codex-runtimes', 'codex-primary-runtime', 'dependencies', ...
    'python', 'python.exe');
if ~isfile(pythonExe), pythonExe = 'python'; end

% Download only the NASA COHO months touched by the requested windows.
downloadManifest = fullfile(dataRoot, ...
    'case1_ppt_coho_download_manifest.json');
if ~isfile(downloadManifest)
    downloader = fullfile(programFolder, ...
        'download_case1_ppt_event_data.py');
    [downloadStatus, downloadOutput] = system(sprintf( ...
        '"%s" "%s"', pythonExe, downloader));
    fprintf('%s\n', downloadOutput);
    assert(downloadStatus == 0 && isfile(downloadManifest), ...
        'VoyagerCase1:DownloadFailed', ...
        'Programmatic NASA COHO download failed.');
end

eventDates = [ ...
    % Slide 1, Voyager 1, year 2020
    1 1 1; 1 1 2; 1 1 3; ...
    % Slide 2, Voyager 1, year 2018
    1 2 1; 1 2 2; 1 2 3; 1 2 4; 1 2 5; 1 2 6; 1 2 7; 1 2 8; 1 2 9; ...
    % Slide 3, Voyager 1, year 2019
    1 3 1; 1 3 2; 1 3 3; 1 3 4; 1 3 5; 1 3 6; ...
    % Slide 4, Voyager 1, year 2021
    1 4 1; 1 4 2; 1 4 3; ...
    % Slide 5, Voyager 1, year 2017
    1 5 1; 1 5 2; 1 5 3; 1 5 4; 1 5 5; 1 5 6; 1 5 7; ...
    % Slide 6, Voyager 1, year 2016
    1 6 1; 1 6 2; ...
    % Slide 7, Voyager 1, year 2015
    1 7 1; 1 7 2; 1 7 3; 1 7 4; 1 7 5; ...
    % Slide 8, Voyager 1, year 2014
    1 8 1; 1 8 2; 1 8 3; 1 8 4; 1 8 5; 1 8 6; ...
    % Slide 9, Voyager 1, year 2013
    1 9 1; 1 9 2; 1 9 3; 1 9 4; ...
    % Slides 11--12, Voyager 2
    2 11 1; 2 11 2; 2 11 3; 2 12 1];

eventText = [ ...
    "2020-05-22"; "2020-09-23"; "2020-12-06"; ...
    "2018-01-08"; "2018-02-02"; "2018-04-24"; "2018-07-07"; ...
    "2018-08-03"; "2018-08-23"; "2018-10-30"; "2018-11-10"; ...
    "2018-12-12"; ...
    "2019-05-02"; "2019-05-27"; "2019-05-30"; "2019-06-13"; ...
    "2019-06-24"; "2019-08-26"; ...
    "2021-01-06"; "2021-05-06"; "2021-05-17"; ...
    "2017-01-15"; "2017-05-24"; "2017-07-18"; "2017-08-15"; ...
    "2017-09-16"; "2017-10-10"; "2017-12-06"; ...
    "2016-09-13"; "2016-09-22"; ...
    "2015-03-04"; "2015-10-04"; "2015-10-13"; "2015-12-19"; ...
    "2015-12-28"; ...
    "2014-04-17"; "2014-05-21"; "2014-08-12"; "2014-08-28"; ...
    "2014-09-21"; "2014-12-13"; ...
    "2013-01-09"; "2013-05-30"; "2013-09-11"; "2013-12-29"; ...
    "2019-02-24"; "2019-09-20"; "2019-11-13"; "2020-11-21"];

assert(size(eventDates, 1) == numel(eventText), ...
    'VoyagerCase1:CatalogLength', 'Event metadata lengths differ.');

spacecraft = eventDates(:, 1);
sourceSlide = eventDates(:, 2);
sourceLine = eventDates(:, 3);
startUTC = datetime(eventText, 'InputFormat', 'yyyy-MM-dd', ...
    'TimeZone', 'UTC');
endUTCInclusive = startUTC;
endUTCExclusive = startUTC + caldays(1);
eventID = strings(numel(startUTC), 1);
for ii = 1:numel(startUTC)
    eventID(ii) = sprintf('Case1-S%02d-L%02d', ...
        sourceSlide(ii), sourceLine(ii));
end

catalog = table(cellstr(eventID), startUTC, endUTCInclusive, ...
    endUTCExclusive, spacecraft, sourceSlide, sourceLine, ...
    'VariableNames', {'EventID', 'StartUTC', 'EndUTCInclusive', ...
    'EndUTCExclusive', 'Spacecraft', 'SourceSlide', 'SourceLine'});

allCatalogFile = fullfile(outputFolder, ...
    'Case1_PPT_vertical_line_event_catalog_all.csv');
v1CatalogFile = fullfile(outputFolder, ...
    'Case1_PPT_vertical_line_event_catalog_V1.csv');
v2CatalogFile = fullfile(outputFolder, ...
    'Case1_PPT_vertical_line_event_catalog_V2.csv');
writetable(catalog, allCatalogFile);
writetable(catalog(spacecraft == 1, :), v1CatalogFile);
writetable(catalog(spacecraft == 2, :), v2CatalogFile);

pitchAngleDataFolder = fullfile(dataRoot, 'derived', ...
    'lecp_pitch_angle_florinski2008_daily');
if ~isfolder(pitchAngleDataFolder), mkdir(pitchAngleDataFolder); end
cacheRoot = fullfile(dataRoot, 'derived', 'cdf_cache');
if ~isfolder(cacheRoot), mkdir(cacheRoot); end

v1SectoredCDF = fullfile(dataRoot, 'voyager1', 'lecp', '1d', 'l2', ...
    'sectored_flux', '2013-2021', ...
    'voyager1_lecp_p1_sectored_daily_case1_20130102_20210525.cdf');
if ~isfile(v1SectoredCDF)
    lecpDownloader = fullfile(programFolder, ...
        'download_case1_voyager1_lecp_daily.py');
    [lecpStatus, lecpOutput] = system(sprintf( ...
        '"%s" "%s"', pythonExe, lecpDownloader));
    fprintf('%s\n', lecpOutput);
    assert(lecpStatus == 0, 'VoyagerCase1:LECPDownloadFailed', ...
        'Programmatic NASA LECP daily-sector download failed.');
end
assert(isfile(v1SectoredCDF), 'VoyagerCase1:MissingV1SectorCDF', ...
    'Required Voyager 1 daily sectored CDF is unavailable.');

reportV1 = Voyager1_Replot_Selected_Events_PaperStyle( ...
    'Spacecraft', 1, ...
    'DataRoot', dataRoot, ...
    'OutputFolder', outputFolder, ...
    'CatalogFile', v1CatalogFile, ...
    'ReportFolder', outputFolder, ...
    'ReportTag', 'Case1_PPT_V1_7d', ...
    'CacheRoot', cacheRoot, ...
    'ContextMonths', 0, ...
    'ContextDays', 7, ...
    'ShowEventBoundaries', false, ...
    'Overwrite', true, ...
    'Visible', false, ...
    'ExportDPI', 220, ...
    'LECPDailyAverage', false, ...
    'CRSDisplay', 'lecp_p1_pitch_angle', ...
    'LECPSectoredDailyCDF', v1SectoredCDF, ...
    'LECPSectorAverageDays', 1, ...
    'PitchAngleMethod', 'florinski2008', ...
    'LECPBackgroundMode', 'none', ...
    'MinimumDailyCoverageFraction', 0.50, ...
    'MinimumDailySectorSamples', 1, ...
    'MinimumPitchAngleSpanDeg', 45, ...
    'PitchAngleDataFolder', pitchAngleDataFolder, ...
    'LineYMarginFraction', 0.08);

reportV2 = Voyager1_Replot_Selected_Events_PaperStyle( ...
    'Spacecraft', 2, ...
    'DataRoot', dataRoot, ...
    'OutputFolder', outputFolder, ...
    'CatalogFile', v2CatalogFile, ...
    'ReportFolder', outputFolder, ...
    'ReportTag', 'Case1_PPT_V2_7d', ...
    'CacheRoot', cacheRoot, ...
    'ContextMonths', 0, ...
    'ContextDays', 7, ...
    'ShowEventBoundaries', false, ...
    'Overwrite', true, ...
    'Visible', false, ...
    'ExportDPI', 220, ...
    'LECPDailyAverage', false, ...
    'CRSDisplay', 'spectrogram', ...
    'LineYMarginFraction', 0.08);

report = [reportV1; reportV2];
combinedReportFile = fullfile(outputFolder, ...
    'Case1_PPT_vertical_line_event_plot_manifest_all.csv');
writetable(report, combinedReportFile);
save(fullfile(outputFolder, ...
    'Case1_PPT_vertical_line_event_plot_report_all.mat'), ...
    'report', 'catalog', 'reportV1', 'reportV2', '-v7.3');

fprintf('\nCase1 vertical-line event plotting complete.\n');
fprintf('Catalog events: %d (V1=%d, V2=%d)\n', ...
    height(catalog), sum(spacecraft == 1), sum(spacecraft == 2));
fprintf('Successful/existing figures: %d\n', ...
    sum(ismember(report.Status, {'ok', 'existing'})));
fprintf('Plot errors: %d\n', sum(strcmp(report.Status, 'plot_error')));
fprintf('Output folder: %s\n', outputFolder);
