function result = run_kh005_preview()
%RUN_KH005_PREVIEW Generate only the first user-review FOTE/FOTE-V figure.
thisDir = fileparts(mfilename('fullpath'));
addpath(thisDir);
outputRoot = 'C:\Users\Administrator\Documents\Codex\2026-08-03\c-users-administrator-documents-kh-figures\outputs';
result = kh_fote_event('KH005','2015-10-01T18:01:24Z', ...
    '2015-10-01T18:09:00Z', ...
    'OutputRoot',outputRoot, ...
    'VelocityField','Vi', ...
    'SmoothSamples',7, ...
    'FigureVisible','on');
disp(result);
end
