function result = plot_ace_mfi_hourly_full_timespan(inputDir)
%PLOT_ACE_MFI_HOURLY_FULL_TIMESPAN Plot the complete ACE/MFI hourly record.
%
% Run directly with no input:
%   plot_ace_mfi_hourly_full_timespan
%
% Or specify another results directory:
%   plot_ace_mfi_hourly_full_timespan('D:\my_results')
%
% The program automatically selects the result file with the longest date
% span.  MAT is preferred over CSV because it is much faster to load.  NaN
% values are retained, so genuine data gaps remain blank and are never
% interpolated.  The output contains two panels (hourly mean and hourly
% maximum) plus an H3/H0/H1/H2/missing source strip.

    if nargin < 1 || isempty(inputDir)
        inputDir = 'C:\Users\Administrator\Documents\FWD_matlab\ACE_fu\ACE_MFI_hourly_output';
    end
    inputDir = char(string(inputDir));

    if ~isfolder(inputDir)
        error('ACE:Plot:InputDirectoryNotFound', ...
            '结果文件夹不存在：%s', inputDir);
    end

    dataPath = selectLongestResult(inputDir);
    fprintf('正在读取：%s\n', dataPath);
    Hourly = loadHourlyResult(dataPath);

    required = {'B_mean_nT', 'B_max_nT'};
    missingVariables = setdiff(required, Hourly.Properties.VariableNames);
    if ~isempty(missingVariables)
        error('ACE:Plot:MissingVariables', ...
            '结果中缺少字段：%s', strjoin(missingVariables, ', '));
    end

    timeUTC = Hourly.Properties.RowTimes;
    if isempty(timeUTC)
        error('ACE:Plot:MissingTime', '结果中没有 TimeUTC 行时间。');
    end
    timeUTC.TimeZone = 'UTC';

    bMean = double(Hourly.B_mean_nT(:));
    bMax = double(Hourly.B_max_nT(:));
    if numel(timeUTC) ~= numel(bMean) || numel(timeUTC) ~= numel(bMax)
        error('ACE:Plot:SizeMismatch', '时间、平均值和最大值的长度不一致。');
    end

    % Keep chronological order even if a manually edited CSV was supplied.
    [timeUTC, order] = sort(timeUTC);
    bMean = bMean(order);
    bMax = bMax(order);
    Hourly = Hourly(order, :);

    finiteBoth = isfinite(bMean) & isfinite(bMax);
    if ~any(finiteBoth)
        error('ACE:Plot:NoValidData', '结果中没有可绘制的有效磁场数据。');
    end

    if ismember('Source', Hourly.Properties.VariableNames)
        source = upper(strtrim(string(Hourly.Source)));
    else
        source = repmat("MISSING", height(Hourly), 1);
        source(finiteBoth) = "UNKNOWN";
    end

    % Use serial UTC time on every axes so the source image and both curves
    % share exactly the same horizontal coordinate system.
    timeForPlot = timeUTC;
    timeForPlot.TimeZone = '';
    t = datenum(timeForPlot); %#ok<DATNM>

    meanColor = [0, 86, 180] / 255;
    maxColor = [220, 70, 35] / 255;
    sourceColors = [ ...
        224, 226, 231; ... % missing
         55, 112, 190; ... % H3
        235, 145,  35; ... % H0
        126,  86, 170; ... % H1
         40, 150, 115] / 255; % H2

    sourceCode = ones(height(Hourly), 1, 'uint8');
    sourceCode(finiteBoth & source == "H3") = 2;
    sourceCode(finiteBoth & source == "H0") = 3;
    sourceCode(finiteBoth & source == "H1") = 4;
    sourceCode(finiteBoth & source == "H2") = 5;

    fig = figure( ...
        'Color', 'w', ...
        'Name', 'ACE/MFI 全时段每小时磁场强度', ...
        'NumberTitle', 'off', ...
        'Units', 'inches', ...
        'Position', [0.5, 0.5, 16, 10], ...
        'PaperUnits', 'inches', ...
        'PaperPosition', [0, 0, 16, 10], ...
        'PaperSize', [16, 10]);

    axMean = axes(fig, 'Position', [0.075, 0.565, 0.895, 0.345]);
    axMax = axes(fig, 'Position', [0.075, 0.175, 0.895, 0.345]);
    axSource = axes(fig, 'Position', [0.075, 0.102, 0.895, 0.025]);

    hMean = plot(axMean, t, bMean, ...
        'Color', meanColor, 'LineWidth', 0.55);
    hMean.DisplayName = '小时平均值';
    hMax = plot(axMax, t, bMax, ...
        'Color', maxColor, 'LineWidth', 0.50);
    hMax.DisplayName = '小时最大值';

    meanUpper = niceUpperLimit(max(bMean, [], 'omitnan'));
    maxUpper = niceUpperLimit(max(bMax, [], 'omitnan'));
    configureFieldAxes(axMean, t, meanUpper, meanColor, '每小时平均值');
    configureFieldAxes(axMax, t, maxUpper, maxColor, '每小时最大值');

    % One pixel column per hourly record.  This does not modify or aggregate
    % the statistics; it only encodes the selected source for the thin strip.
    % Convert to double before direct colormap indexing.  Integer CData uses
    % zero-based direct indices in MATLAB and would shift every source color.
    image(axSource, [t(1), t(end)], [0, 1], ...
        reshape(double(sourceCode), 1, []), ...
        'CDataMapping', 'direct');
    colormap(axSource, sourceColors);
    set(axSource, ...
        'YLim', [0, 1], ...
        'YTick', [], ...
        'XLim', [t(1), t(end)], ...
        'Box', 'on', ...
        'Layer', 'top', ...
        'LineWidth', 0.7, ...
        'FontName', 'Microsoft YaHei', ...
        'FontSize', 11, ...
        'TickDir', 'out', ...
        'XColor', [0.36, 0.39, 0.44], ...
        'YColor', [0.55, 0.57, 0.62]);

    startYear = year(timeUTC(1));
    endYear = year(timeUTC(end));
    firstTickYear = startYear + mod(1998 - startYear, 4);
    tickYears = firstTickYear:4:endYear;
    if isempty(tickYears)
        tickYears = unique([startYear, endYear]);
    end
    tickDates = datetime(tickYears, 1, 1);
    tickNumbers = datenum(tickDates); %#ok<DATNM>
    inside = tickNumbers >= t(1) & tickNumbers <= t(end);
    tickYears = tickYears(inside);
    tickNumbers = tickNumbers(inside);

    set(axMean, 'XTick', tickNumbers, 'XTickLabel', []);
    set(axMax, 'XTick', tickNumbers, 'XTickLabel', []);
    set(axSource, 'XTick', tickNumbers, ...
        'XTickLabel', compose('%d', tickYears));
    xlabel(axSource, '时间（UTC）', ...
        'FontName', 'Microsoft YaHei', 'FontSize', 13, ...
        'Color', [0.14, 0.16, 0.19]);

    linkaxes([axMean, axMax, axSource], 'x');
    xlim(axMean, [t(1), t(end)]);

    startText = datestr(t(1), 'yyyy-mm-dd'); %#ok<DATST>
    endText = datestr(t(end), 'yyyy-mm-dd'); %#ok<DATST>
    sgtitle(fig, sprintf('ACE/MFI （%s—%s）', ...
        startText, endText), ...
        'FontName', 'Microsoft YaHei', ...
        'FontSize', 20, ...
        'FontWeight', 'bold', ...
        'Color', [0.14, 0.16, 0.19]);

    ylabel(axMean, '|B|（nT）', ...
        'FontName', 'Microsoft YaHei', 'FontSize', 13);
    ylabel(axMax, '|B|（nT）', ...
        'FontName', 'Microsoft YaHei', 'FontSize', 13);
    text(axSource, -0.012, 0.5, '有效数据来源', ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'right', ...
        'VerticalAlignment', 'middle', ...
        'FontName', 'Microsoft YaHei', ...
        'FontSize', 11, ...
        'Color', [0.14, 0.16, 0.19]);

    [meanPeak, meanIndex] = max(bMean, [], 'omitnan');
    [maxPeak, maxIndex] = max(bMax, [], 'omitnan');
    markPeak(axMean, t(meanIndex), meanPeak, timeUTC(meanIndex), ...
        meanColor, '');
    markPeak(axMax, t(maxIndex), maxPeak, timeUTC(maxIndex), ...
        maxColor, '');

    addLineLegend(fig, meanColor, maxColor);
    addSourceLegend(fig, sourceColors);

    totalHours = numel(t);
    validHours = nnz(finiteBoth);
    coveragePercent = 100 * validHours / totalHours;
    note = sprintf(['有效小时：%s / %s（%.3f%%）'], ...
        formatInteger(validHours), formatInteger(totalHours), coveragePercent);
    annotation(fig, 'textbox', [0.075, 0.010, 0.895, 0.040], ...
        'String', note, ...
        'EdgeColor', 'none', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'FontName', 'Microsoft YaHei', ...
        'FontSize', 9.5, ...
        'Color', [0.42, 0.45, 0.50]);

    drawnow;

    [~, inputBase] = fileparts(dataPath);
    outputBase = fullfile(inputDir, inputBase + "_2panel_full_timespan");
    pngPath = char(outputBase + ".png");
    figPath = char(outputBase + ".fig");

    savefig(fig, figPath);
    print(fig, pngPath, '-dpng', '-r300');

    counts = struct( ...
        'H3', nnz(sourceCode == 2), ...
        'H0', nnz(sourceCode == 3), ...
        'H1', nnz(sourceCode == 4), ...
        'H2', nnz(sourceCode == 5), ...
        'Missing', nnz(sourceCode == 1));

    result = struct( ...
        'InputFile', dataPath, ...
        'PNG', pngPath, ...
        'FIG', figPath, ...
        'StartUTC', timeUTC(1), ...
        'EndUTC', timeUTC(end), ...
        'TotalHours', totalHours, ...
        'ValidHours', validHours, ...
        'CoveragePercent', coveragePercent, ...
        'SourceHourCounts', counts, ...
        'MeanPeak_nT', meanPeak, ...
        'MeanPeakUTC', timeUTC(meanIndex), ...
        'MaximumPeak_nT', maxPeak, ...
        'MaximumPeakUTC', timeUTC(maxIndex));

    fprintf('绘图完成：%s\n', pngPath);
    fprintf('有效小时：%s / %s（%.3f%%）\n', ...
        formatInteger(validHours), formatInteger(totalHours), coveragePercent);
    fprintf('来源小时：H3=%s, H0=%s, H1=%s, H2=%s, 缺失=%s\n', ...
        formatInteger(counts.H3), formatInteger(counts.H0), ...
        formatInteger(counts.H1), formatInteger(counts.H2), ...
        formatInteger(counts.Missing));
end


function path = selectLongestResult(inputDir)
    candidates = [ ...
        dir(fullfile(inputDir, 'ACE_MFI_hourly_????????_????????.mat')); ...
        dir(fullfile(inputDir, 'ACE_MFI_hourly_????????_????????.csv'))];
    if isempty(candidates)
        error('ACE:Plot:NoResultFile', ...
            '文件夹中没有 ACE_MFI_hourly_YYYYMMDD_YYYYMMDD.mat/csv。');
    end

    bestIndex = 0;
    bestSpan = -Inf;
    bestStart = Inf;
    bestEnd = -Inf;
    bestIsMat = false;
    for k = 1:numel(candidates)
        token = regexp(candidates(k).name, ...
            '^ACE_MFI_hourly_(\d{8})_(\d{8})\.(mat|csv)$', ...
            'tokens', 'once');
        if isempty(token)
            continue;
        end
        startNumber = datenum(token{1}, 'yyyymmdd'); %#ok<DATNM>
        endNumber = datenum(token{2}, 'yyyymmdd'); %#ok<DATNM>
        span = endNumber - startNumber;
        isMat = strcmpi(token{3}, 'mat');
        better = span > bestSpan || ...
            (span == bestSpan && startNumber < bestStart) || ...
            (span == bestSpan && startNumber == bestStart && endNumber > bestEnd) || ...
            (span == bestSpan && startNumber == bestStart && ...
             endNumber == bestEnd && isMat && ~bestIsMat);
        if better
            bestIndex = k;
            bestSpan = span;
            bestStart = startNumber;
            bestEnd = endNumber;
            bestIsMat = isMat;
        end
    end

    if bestIndex == 0
        error('ACE:Plot:NoValidResultName', '没有识别出有效的结果文件名。');
    end
    path = fullfile(candidates(bestIndex).folder, candidates(bestIndex).name);
end


function Hourly = loadHourlyResult(path)
    [~, ~, extension] = fileparts(path);
    if strcmpi(extension, '.mat')
        loaded = load(path, 'Hourly');
        if ~isfield(loaded, 'Hourly') || ~istimetable(loaded.Hourly)
            error('ACE:Plot:InvalidMAT', ...
                'MAT 文件中没有 timetable 变量 Hourly：%s', path);
        end
        Hourly = loaded.Hourly;
        return;
    end

    tableData = readtable(path, 'VariableNamingRule', 'preserve');
    if ~ismember('TimeUTC', tableData.Properties.VariableNames)
        error('ACE:Plot:InvalidCSV', 'CSV 中没有 TimeUTC 字段：%s', path);
    end

    rawTime = tableData.TimeUTC;
    if isdatetime(rawTime)
        timeUTC = rawTime;
        timeUTC.TimeZone = 'UTC';
    else
        timeUTC = datetime(string(rawTime), ...
            'InputFormat', 'yyyy-MM-dd''T''HH:mm:ss''Z''', ...
            'TimeZone', 'UTC');
    end
    tableData.TimeUTC = [];
    Hourly = table2timetable(tableData, 'RowTimes', timeUTC);
    Hourly.Properties.DimensionNames{1} = 'TimeUTC';
end


function configureFieldAxes(ax, t, upperLimit, labelColor, panelLabel)
    set(ax, ...
        'XLim', [t(1), t(end)], ...
        'YLim', [0, upperLimit], ...
        'YTick', 0:20:upperLimit, ...
        'Box', 'on', ...
        'Layer', 'top', ...
        'LineWidth', 0.7, ...
        'FontName', 'Microsoft YaHei', ...
        'FontSize', 11, ...
        'TickDir', 'out', ...
        'XGrid', 'off', ...
        'YGrid', 'off', ...
        'GridColor', [0.83, 0.85, 0.88], ...
        'GridAlpha', 0.68, ...
        'MinorGridAlpha', 0.20, ...
        'XColor', [0.36, 0.39, 0.44], ...
        'YColor', [0.36, 0.39, 0.44]);
    text(ax, 0.006, 0.965, panelLabel, ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'top', ...
        'FontName', 'Microsoft YaHei', ...
        'FontSize', 12, ...
        'FontWeight', 'bold', ...
        'Color', labelColor);
end


function upper = niceUpperLimit(peak)
    if ~isfinite(peak) || peak <= 0
        upper = 10;
    else
        upper = max(10, ceil(peak / 10) * 10);
    end
end


function markPeak(ax, peakTimeNumber, peakValue, peakTimeUTC, color, prefix)
    hold(ax, 'on');
    plot(ax, peakTimeNumber, peakValue, 'o', ...
        'MarkerSize', 4.5, ...
        'MarkerFaceColor', color, ...
        'MarkerEdgeColor', 'w', ...
        'LineWidth', 0.7, ...
        'HandleVisibility', 'off');
    text(ax, 0.985, 0.952, sprintf('%s %.2f nT', prefix, peakValue), ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'right', ...
        'VerticalAlignment', 'top', ...
        'FontName', 'Microsoft YaHei', ...
        'FontSize', 9.5, ...
        'FontWeight', 'bold', ...
        'Color', color);
    timeCopy = peakTimeUTC;
    timeCopy.TimeZone = 'UTC';
    timeCopy.Format = 'yyyy-MM-dd HH:mm';
    text(ax, 0.985, 0.902, sprintf('%s UTC', char(timeCopy)), ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'right', ...
        'VerticalAlignment', 'top', ...
        'FontName', 'Microsoft YaHei', ...
        'FontSize', 8.5, ...
        'Color', [0.42, 0.45, 0.50]);
end


function addLineLegend(fig, meanColor, maxColor)
    entries = {meanColor, '小时平均值'; maxColor, '小时最大值'};
    x0 = 0.790;
    y = 0.928;
    for k = 1:size(entries, 1)
        x = x0 + (k - 1) * 0.095;
        annotation(fig, 'line', [x, x + 0.018], [y, y], ...
            'Color', entries{k, 1}, 'LineWidth', 2.2);
        annotation(fig, 'textbox', [x + 0.021, y - 0.014, 0.072, 0.028], ...
            'String', entries{k, 2}, ...
            'EdgeColor', 'none', ...
            'VerticalAlignment', 'middle', ...
            'FontName', 'Microsoft YaHei', ...
            'FontSize', 8.5, ...
            'Color', [0.20, 0.22, 0.26]);
    end
end


function addSourceLegend(fig, colors)
    labels = {'H3 (1s)', 'H0 (16s)', 'H1 (4m)', 'H2 (1h)', '缺失'};
    rows = [2, 3, 4, 5, 1];
    x0 = 0.660;
    y = 0.132;
    step = 0.060;
    for k = 1:numel(labels)
        x = x0 + (k - 1) * step;
        annotation(fig, 'rectangle', [x, y, 0.011, 0.011], ...
            'FaceColor', colors(rows(k), :), ...
            'EdgeColor', [0.55, 0.57, 0.62], ...
            'LineWidth', 0.4);
        annotation(fig, 'textbox', [x + 0.014, y - 0.007, 0.043, 0.025], ...
            'String', labels{k}, ...
            'EdgeColor', 'none', ...
            'VerticalAlignment', 'middle', ...
            'FontName', 'Microsoft YaHei', ...
            'FontSize', 8.5, ...
            'Color', [0.20, 0.22, 0.26]);
    end
end


function textValue = formatInteger(value)
    digits = sprintf('%.0f', value);
    expression = '(?<=\d)(?=(\d{3})+$)';
    textValue = regexprep(digits, expression, ',');
end
