function result = plot_sunspot_dst_full_timespan(dataRoot, outputDir)
%PLOT_SUNSPOT_DST_FULL_TIMESPAN Plot daily sunspot number and hourly Dst.
%
%   RESULT = PLOT_SUNSPOT_DST_FULL_TIMESPAN() reads the prepared data in
%   Z:\SPART-WORK\Data\Solar_Indices\processed and creates a two-panel
%   full-timespan figure.  The original daily/hourly values are plotted;
%   this function does not aggregate or interpolate either data set.
%
%   RESULT = PLOT_SUNSPOT_DST_FULL_TIMESPAN(DATAROOT, OUTPUTDIR) overrides
%   the input and output folders.

    if nargin < 1 || isempty(dataRoot)
        dataRoot = 'Z:\SPART-WORK\Data\Solar_Indices\processed';
    end
    if nargin < 2 || isempty(outputDir)
        scriptDir = fileparts(mfilename('fullpath'));
        outputDir = fullfile(scriptDir, 'Solar_Indices_plot_output');
    end

    rangeTag = '19970902_20260515';
    sunspotPath = fullfile(dataRoot, ...
        ['sunspot_daily_', rangeTag, '.csv']);
    dstPath = fullfile(dataRoot, ...
        ['dst_hourly_', rangeTag, '.csv']);
    assertFileExists(sunspotPath, '太阳黑子');
    assertFileExists(dstPath, 'Dst');

    Sunspot = readtable(sunspotPath, ...
        'Delimiter', ',', 'ReadVariableNames', true, ...
        'TextType', 'string', 'VariableNamingRule', 'preserve');
    Dst = readtable(dstPath, ...
        'Delimiter', ',', 'ReadVariableNames', true, ...
        'TextType', 'string', 'VariableNamingRule', 'preserve');
    requireVariables(Sunspot, ...
        {'TimeUTC', 'SunspotNumber', 'DefinitiveFlag'}, '太阳黑子');
    requireVariables(Dst, {'TimeUTC', 'Dst_nT', 'Status'}, 'Dst');

    sunspotTimeUTC = parseUtcTime(Sunspot.TimeUTC);
    dstTimeUTC = parseUtcTime(Dst.TimeUTC);
    sunspotNumber = numericColumn(Sunspot.SunspotNumber);
    dst_nT = numericColumn(Dst.Dst_nT);

    [sunspotTimeUTC, order] = sort(sunspotTimeUTC);
    sunspotNumber = sunspotNumber(order);
    sunspotDefinitive = numericColumn(Sunspot.DefinitiveFlag(order));
    [dstTimeUTC, order] = sort(dstTimeUTC);
    dst_nT = dst_nT(order);
    dstStatus = string(Dst.Status(order));

    validateTimeline(sunspotTimeUTC, days(1), '太阳黑子');
    validateTimeline(dstTimeUTC, hours(1), 'Dst');
    expectedStartUTC = datetime(1997, 9, 2, 0, 0, 0, 'TimeZone', 'UTC');
    expectedSunspotEndUTC = datetime(2026, 5, 15, 0, 0, 0, ...
        'TimeZone', 'UTC');
    expectedDstEndUTC = datetime(2026, 5, 15, 23, 0, 0, ...
        'TimeZone', 'UTC');
    validateExactCoverage(sunspotTimeUTC, expectedStartUTC, ...
        expectedSunspotEndUTC, 10483, '太阳黑子');
    validateExactCoverage(dstTimeUTC, expectedStartUTC, ...
        expectedDstEndUTC, 251592, 'Dst');

    % Use numeric serial dates for a lightweight plot of 251,592 Dst hours.
    sunspotTimeForPlot = sunspotTimeUTC;
    sunspotTimeForPlot.TimeZone = '';
    dstTimeForPlot = dstTimeUTC;
    dstTimeForPlot.TimeZone = '';
    tSunspot = datenum(sunspotTimeForPlot); %#ok<DATNM>
    tDst = datenum(dstTimeForPlot); %#ok<DATNM>

    plotStart = max(tSunspot(1), tDst(1));
    plotEndExclusive = min(tSunspot(end) + 1, tDst(end) + 1 / 24);
    if plotStart >= plotEndExclusive
        error('SolarIndices:NoCommonTime', ...
            '太阳黑子与 Dst 数据没有共同时间范围。');
    end

    sunspotColor = [232, 135, 25] / 255;
    dstColor = [38, 101, 170] / 255;
    neutralColor = [0.36, 0.39, 0.44];

    fig = figure( ...
        'Color', 'w', ...
        'Name', '太阳黑子数与 Dst 指数全时段图', ...
        'NumberTitle', 'off', ...
        'Units', 'inches', ...
        'Position', [0.5, 0.5, 16, 9], ...
        'PaperUnits', 'inches', ...
        'PaperPosition', [0, 0, 16, 9], ...
        'PaperSize', [16, 9]);

    axSunspot = axes(fig, 'Position', [0.075, 0.555, 0.895, 0.345]);
    axDst = axes(fig, 'Position', [0.075, 0.145, 0.895, 0.345]);

    plot(axSunspot, tSunspot, sunspotNumber, ...
        'Color', sunspotColor, 'LineWidth', 0.55);
    plot(axDst, tDst, dst_nT, ...
        'Color', dstColor, 'LineWidth', 0.45);
    hold(axDst, 'on');
    yline(axDst, 0, '-', 'Color', [0.52, 0.54, 0.58], ...
        'LineWidth', 0.65, 'HandleVisibility', 'off');
    hold(axDst, 'off');

    sunspotMax = max(sunspotNumber, [], 'omitnan');
    sunspotUpper = max(50, ceil(sunspotMax / 50) * 50);
    dstMin = min(dst_nT, [], 'omitnan');
    dstMax = max(dst_nT, [], 'omitnan');
    dstLower = min(-50, floor(dstMin / 50) * 50);
    dstUpper = max(50, ceil(dstMax / 50) * 50);

    configureAxes(axSunspot, plotStart, plotEndExclusive, ...
        [0, sunspotUpper], neutralColor);
    configureAxes(axDst, plotStart, plotEndExclusive, ...
        [dstLower, dstUpper], neutralColor);
    ylabel(axSunspot, '太阳黑子数', ...
        'FontName', 'Microsoft YaHei', 'FontSize', 13);
    ylabel(axDst, 'Dst（nT）', ...
        'FontName', 'Microsoft YaHei', 'FontSize', 13);
    xlabel(axDst, '时间（UTC）', ...
        'FontName', 'Microsoft YaHei', 'FontSize', 13);

    text(axSunspot, 0.008, 0.965, '每日太阳黑子数（SILSO V2.0）', ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'top', ...
        'FontName', 'Microsoft YaHei', ...
        'FontSize', 12, ...
        'FontWeight', 'bold', ...
        'Color', sunspotColor);
    text(axDst, 0.008, 0.965, '逐小时 Dst 指数（WDC Kyoto / OMNI2）', ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'top', ...
        'FontName', 'Microsoft YaHei', ...
        'FontSize', 12, ...
        'FontWeight', 'bold', ...
        'Color', dstColor);

    firstYear = year(sunspotTimeUTC(1));
    finalYear = year(dstTimeUTC(end));
    firstTickYear = firstYear + mod(1998 - firstYear, 4);
    tickYears = firstTickYear:4:finalYear;
    tickDates = datetime(tickYears, 1, 1);
    tickNumbers = datenum(tickDates); %#ok<DATNM>
    inside = tickNumbers >= plotStart & tickNumbers <= plotEndExclusive;
    tickYears = tickYears(inside);
    tickNumbers = tickNumbers(inside);
    set(axSunspot, 'XTick', tickNumbers, 'XTickLabel', []);
    set(axDst, 'XTick', tickNumbers, ...
        'XTickLabel', compose('%d', tickYears));
    linkaxes([axSunspot, axDst], 'x');
    xlim(axSunspot, [plotStart, plotEndExclusive]);

    startText = datestr(plotStart, 'yyyy-mm-dd'); %#ok<DATST>
    endText = datestr(plotEndExclusive - 1 / 24, 'yyyy-mm-dd'); %#ok<DATST>
    sgtitle(fig, sprintf('太阳黑子数与 Dst 指数（%s—%s）', ...
        startText, endText), ...
        'FontName', 'Microsoft YaHei', ...
        'FontSize', 19, ...
        'FontWeight', 'bold', ...
        'Color', [0.14, 0.16, 0.19]);

    validSunspot = nnz(isfinite(sunspotNumber));
    validDst = nnz(isfinite(dst_nT));
    provisionalSunspot = nnz(sunspotDefinitive == 0);
    finalDst = nnz(dstStatus == "FINAL");
    provisionalDst = nnz(dstStatus == "PROVISIONAL");
    quicklookDst = nnz(dstStatus == "QUICKLOOK");
    note = sprintf([ ...
        '原始分辨率：太阳黑子每日、Dst逐小时；未聚合、未插值。', ...
        ' 有效记录：太阳黑子 %s/%s，Dst %s/%s。', ...
        ' 暂定太阳黑子 %s 日；Dst FINAL/PROVISIONAL/QUICKLOOK = %s/%s/%s 小时。'], ...
        formatInteger(validSunspot), formatInteger(numel(sunspotNumber)), ...
        formatInteger(validDst), formatInteger(numel(dst_nT)), ...
        formatInteger(provisionalSunspot), formatInteger(finalDst), ...
        formatInteger(provisionalDst), formatInteger(quicklookDst));
    annotation(fig, 'textbox', [0.075, 0.018, 0.895, 0.050], ...
        'String', note, ...
        'Interpreter', 'none', ...
        'EdgeColor', 'none', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'FontName', 'Microsoft YaHei', ...
        'FontSize', 8.8, ...
        'Color', [0.42, 0.45, 0.50]);

    if ~isfolder(outputDir)
        mkdir(outputDir);
    end
    baseName = sprintf('Solar_Indices_%s_%s_2panel_full_timespan', ...
        datestr(plotStart, 'yyyymmdd'), ... %#ok<DATST>
        datestr(plotEndExclusive - 1 / 24, 'yyyymmdd')); %#ok<DATST>
    figPath = fullfile(outputDir, [baseName, '.fig']);
    pngPath = fullfile(outputDir, [baseName, '.png']);
    savefig(fig, figPath);
    print(fig, pngPath, '-dpng', '-r300');

    result = struct( ...
        'SunspotCSV', sunspotPath, ...
        'DstCSV', dstPath, ...
        'PNG', pngPath, ...
        'FIG', figPath, ...
        'StartUTC', sunspotTimeUTC(1), ...
        'EndUTC', dstTimeUTC(end), ...
        'SunspotRows', height(Sunspot), ...
        'DstRows', height(Dst), ...
        'SunspotMinimum', min(sunspotNumber, [], 'omitnan'), ...
        'SunspotMaximum', sunspotMax, ...
        'DstMinimum_nT', dstMin, ...
        'DstMaximum_nT', dstMax);

    fprintf('太阳黑子数与 Dst 全时段图已保存：\n%s\n%s\n', ...
        pngPath, figPath);
end


function timeUTC = parseUtcTime(rawTime)
    if isdatetime(rawTime)
        timeUTC = rawTime;
        timeUTC.TimeZone = 'UTC';
        return;
    end
    timeUTC = datetime(string(rawTime), ...
        'InputFormat', 'yyyy-MM-dd''T''HH:mm:ss''Z''', ...
        'TimeZone', 'UTC');
end


function validateTimeline(timeUTC, expectedStep, label)
    if isempty(timeUTC)
        error('SolarIndices:EmptyData', '%s 数据为空。', label);
    end
    if any(isnat(timeUTC))
        error('SolarIndices:InvalidTime', '%s 包含无法解析的时间。', label);
    end
    timeDifference = diff(timeUTC);
    if any(timeDifference <= seconds(0))
        error('SolarIndices:TimeOrder', ...
            '%s 时间不严格递增或存在重复。', label);
    end
    if any(timeDifference ~= expectedStep)
        error('SolarIndices:TimeGap', ...
            '%s 时间网格不是连续的 %s。', label, char(expectedStep));
    end
end


function validateExactCoverage(timeUTC, expectedStart, expectedEnd, ...
        expectedRows, label)
    if numel(timeUTC) ~= expectedRows || timeUTC(1) ~= expectedStart ...
            || timeUTC(end) ~= expectedEnd
        error('SolarIndices:CoverageMismatch', ...
            ['%s 数据范围或记录数与 ACE 不一致。', ...
            '期望 %s 至 %s，共 %s 条；实际 %s 至 %s，共 %s 条。'], ...
            label, char(expectedStart), char(expectedEnd), ...
            formatInteger(expectedRows), char(timeUTC(1)), ...
            char(timeUTC(end)), formatInteger(numel(timeUTC)));
    end
end


function configureAxes(ax, startNumber, endNumber, yLimits, axisColor)
    set(ax, ...
        'XLim', [startNumber, endNumber], ...
        'YLim', yLimits, ...
        'Box', 'on', ...
        'Layer', 'top', ...
        'LineWidth', 0.7, ...
        'FontName', 'Microsoft YaHei', ...
        'FontSize', 11, ...
        'TickDir', 'out', ...
        'XGrid', 'off', ...
        'YGrid', 'off', ...
        'XColor', axisColor, ...
        'YColor', axisColor);
end


function assertFileExists(path, label)
    if ~isfile(path)
        error('SolarIndices:MissingFile', ...
            '%s 数据文件不存在：%s', label, path);
    end
end


function requireVariables(tableData, required, label)
    missing = setdiff(required, tableData.Properties.VariableNames);
    if ~isempty(missing)
        error('SolarIndices:MissingVariable', ...
            '%s 数据缺少字段：%s', label, strjoin(missing, ', '));
    end
end


function textValue = formatInteger(value)
    textValue = regexprep(sprintf('%.0f', value), ...
        '(?<=\d)(?=(\d{3})+$)', ',');
end


function values = numericColumn(rawValues)
    if isnumeric(rawValues) || islogical(rawValues)
        values = double(rawValues);
    else
        values = str2double(string(rawValues));
    end
end
