function result = run_kh005_matlab_irfu(figureVisible)
%RUN_KH005_MATLAB_IRFU 示例模块：复现已确认的KH005 5 s结果。
%
% 输入figureVisible可为'on'或'off'。本模块仅固定事件参数和输出目录，
% 实际数据处理、FOTE/FOTE-V、特征值稳定度和持续时间筛选均由主程序完成。
if nargin<1, figureVisible = 'on'; end
thisDir = fileparts(mfilename('fullpath'));
addpath(thisDir);

result = kh_fote_event('KH005', ...
    '2015-10-01T18:01:24Z','2015-10-01T18:09:00Z', ...
    'SmoothSeconds',5, ...
    'QualityPercent',40, ...
    'EigenvalueStabilityThreshold',0.5, ...
    'MinQualityDurationSeconds',5, ...
    'VelocityField','Vi', ...
    'FigureVisible',figureVisible, ...
    'OutputRoot',fullfile( ...
      'C:\Users\Administrator\Documents\FWD_matlab\MMS_fu\codex\kh_events', ...
      'KH005','matlab_irfu_q40_eig0p5'));
disp(result);
end
