function results = run_kh005_eigenstability_compare(figureVisible)
%RUN_KH005_EIGENSTABILITY_COMPARE 比较有/无持续5 s判据的KH005结果。
%
% 两次运行共同采用：
%   5 s原生物理时间平均；40% FOTE/FOTE-V误差；M_lambda>=0.5。
% 第一张图要求As和Bs分别连续合格至少5 s；第二张图使用逐点合格结果。
if nargin<1, figureVisible = 'off'; end
thisDir = fileparts(mfilename('fullpath'));
addpath(thisDir);

outputRoot = fullfile( ...
    'C:\Users\Administrator\Documents\FWD_matlab\MMS_fu\codex\kh_events', ...
    'KH005','eigenvalue_stability_0p5_compare');
commonArguments = { ...
    'SmoothSeconds',5, ...
    'QualityPercent',40, ...
    'EigenvalueStabilityThreshold',0.5, ...
    'VelocityField','Vi', ...
    'FigureVisible',figureVisible, ...
    'OutputRoot',outputRoot};

fprintf('KH005 comparison 1/2: M_lambda>=0.5 and type-specific run>=5 s.\n');
with5s = kh_fote_event('KH005', ...
    '2015-10-01T18:01:24Z','2015-10-01T18:09:00Z', ...
    commonArguments{:},'MinQualityDurationSeconds',5);

fprintf('KH005 comparison 2/2: M_lambda>=0.5, pointwise without duration.\n');
pointwise = kh_fote_event('KH005', ...
    '2015-10-01T18:01:24Z','2015-10-01T18:09:00Z', ...
    commonArguments{:},'MinQualityDurationSeconds',0);

results = struct('With5s',with5s,'Pointwise',pointwise);
disp(results);
end
