import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {pathToFileURL} from 'node:url';
import {PresentationFile,FileBlob} from '@oai/artifact-tool';
const CODE=String.raw`C:\Users\Administrator\Documents\FWD_matlab\MMS_fu`;
const OUT=String.raw`C:\Users\Administrator\Documents\KH\MMS_events_original_style_20260924_v2`;
const AUDIT=String.raw`Z:\SPART-WORK\Data\MMS\derived\events_original_style_20260924_v2`;
const SKILL=String.raw`C:\Users\Administrator\.codex\plugins\cache\openai-primary-runtime\presentations\26.904.11930\skills\presentations`;
const source=String.raw`C:\Users\Administrator\Documents\KH\MMS_events_original_style_20260924\MMS_20_events_original_style_20260924.pptx`;
const oldIndexPath=String.raw`Z:\SPART-WORK\Data\MMS\derived\events_original_style_20260924\ppt_slide_index.json`;
const WORK=path.join(process.env.TEMP,'MMS_original_style_20260924_v2','ppt_build');
const PYTHON=String.raw`C:\Users\Administrator\.cache\codex-runtimes\codex-primary-runtime\dependencies\python\python.exe`;
const name='MMS_20_events_original_style_20260924_v2.pptx';
process.env.RUNTIME_NODE_MODULES=path.resolve(path.dirname(process.execPath),'..','node_modules');
const {finalizePresentation}=await import(pathToFileURL(path.join(SKILL,'container_tools/artifact_tool_utils.mjs')).href);
await fs.mkdir(path.join(WORK,'output'),{recursive:true});
const p=await PresentationFile.importPptx(await FileBlob.load(source));
const snapshot=await p.inspect({kind:'slide,image,textbox,notes',maxChars:2000000});
await fs.writeFile(path.join(WORK,'source_inspect.ndjson'),snapshot.ndjson);
const index=JSON.parse(await fs.readFile(oldIndexPath,'utf8'));
const events=JSON.parse(await fs.readFile(path.join(CODE,'MMS_event_overview_20260924_events.json'),'utf8'));
if(p.slides.items.length!==127||index.length!==127)throw Error('Source slide count mismatch');
if(process.argv.includes('--inspect')) {
 console.log(snapshot.ndjson.slice(0,8000));
 process.exit(0);
}
for(const [i,item] of index.entries()){
 const slide=p.slides.items[i];
 if(item.kind==='cover'){
  for(const shape of slide.shapes.items){
   shape.text.replace('B and V use GSM. MMS1–3 E uses GSM. MMS4 E retains native DSL XY.','Redrawn vectors use GSM. E available only in DSL is omitted.');
   shape.text.replace('B, Vi, Ve, E, N, Ti, Te, Ei and Ee follow the labels in the original scripts.','FEEPS spectra and HPCA species data are appended where available.');
   shape.text.replace('Burst data take priority where available. Particle moments use available fast data.','Burst data take priority. FPI moments use available fast data.');
   shape.text.replace('11 August: only B could be redrawn from the required public L2 products.','11 August: FGM, FEEPS and HPCA are shown where available.');
   shape.text.replace('MMS4 electron data gaps remain blank.','MMS4 FPI electron data gaps remain blank.');
   shape.text.replace('Public-data availability was checked on 23 September 2026.','FEEPS and HPCA availability was checked on 24 September 2026.');
  }
  slide.speakerNotes.textFrame.setText('Scientific plotting scripts: Overview_events_original_style_20260924_v2.m and MMS_orbit_original_style_20260924_v2.m. Both are direct MATLAB scripts without new function definitions. They call the installed IRFU library and use the original overview panel labels. Original CDF database: Z:\\SPART-WORK\\Data\\MMS. Figures are images and can be regenerated using the supplied MATLAB source. FEEPS and HPCA files were queried on 24 September 2026 and downloaded to the same local database before the final rerun.');
 }
 if(item.kind==='orbit'){
  for(const shape of slide.shapes.items)shape.text.replace('GSM     ','');
 }
 if(!['native','orbit'].includes(item.kind))continue;
 if(slide.images.items.length!==1)throw Error('Unexpected figure count at slide '+item.slide);
 const record=JSON.parse(await fs.readFile(path.join(AUDIT,item.event+(item.kind==='native'?'_MMS'+item.spacecraft+'_overview.json':'_orbit.json')),'utf8'));
 if(!record.complete||!record.png)throw Error('Incomplete figure '+item.event);
 if(item.kind==='native'&&!record.particlePanelsChecked)throw Error('FEEPS/HPCA rerun missing '+item.event+' MMS'+item.spacecraft);
 const image=slide.images.items[0];
 const frame=image.frame;
 image.replace({blob:new Uint8Array(await fs.readFile(record.png)),contentType:'image/png',fit:'contain',alt:item.kind==='native'?item.event+' MMS'+item.spacecraft+' overview generated with the original MATLAB script format':item.event+' MMS1–4 positions generated by mms.mms4_pl_conf'});
 image.frame=frame;
 item.image=record.png;
 const ev=events.find(e=>e.id===item.event);
 if(item.kind==='native'){
  slide.speakerNotes.textFrame.setText([
   item.event+' MMS'+item.spacecraft+' '+ev.label,
   'UTC interval: '+record.startUTC+' to '+record.endUTC,
   'Scientific source: original MMS L2 CDFs archived in Z:\\SPART-WORK\\Data\\MMS.',
   'Plot script: Overview_events_original_style_20260924_v2.m. Reference scripts: Overview_download.m and Overview_download_mms4.m.',
   'Direct IRFU calls: mms.get_data, mms.db_get_ts, mms.db_get_variable, mms.variable2ts, irf.ts2mat, irf_gse2gsm, irf_subplot, irf_plot, irf_spectrogram, irf_zoom and irf_plot_axis_align.',
   'Burst is plotted where present. Survey/fast fills intervals without burst. No smoothing or interpolation of measurements. Gaps remain blank.',
   'Dense electric-field display uses the installed IRFU reduce_to_width utility. Its min/max bins are for display only.',
   'Coordinates: '+record.coordinateSystem+'. DSL-only electric-field data are excluded. Event marker lines are omitted. Time labels are horizontal.',
   'Native sample counts: '+JSON.stringify({names:record.nativeCountNames,modes:record.modeOrder,counts:record.nativeCounts,electric:record.electricCounts}),
   'Panel availability B,Vi,Ve,E,N,Ti,Te,Ei,Ee: '+JSON.stringify(record.panelAvailable),
   'FEEPS and HPCA data read with existing mms.get_data and PDist.specrec methods. Additional valid panels are appended to the same overview.',
   'Extra instrument names: '+JSON.stringify(record.extraSpectraNames)+'. Native counts (burst, survey): '+JSON.stringify(record.extraCounts),
   'Local IRFU compatibility fixes: HPCA He++ survey interface spelling and the exact FEEPS inactive-eye sentinel (-2147483648). Existing sensor means are retained; supplied code and diff document the changes.',
   'HPCA density counts, H+, He+, He++, O+: '+JSON.stringify(record.hpcaDensityCounts)+'. CDF flux units: '+JSON.stringify(record.extraUnits),
   'FEEPS/HPCA official original CDF files are archived under Z:\\SPART-WORK\\Data\\MMS. Source: https://lasp.colorado.edu/mms/sdc/public/',
  ].join('\n'));
 } else {
  slide.speakerNotes.textFrame.setText([
   ev.id+' '+ev.label,
   'Plot script: MMS_orbit_original_style_20260924_v2.m, following the original MMS_orbit.m.',
   'Plotter: mms.mms4_pl_conf. Only two date display format strings in the installed routine were corrected from HH:MM:SS.mmm to HH:MM:SS. The original file is backed up.',
   'Snapshot UTC: '+record.snapshotUTC+'. Single specified times are used directly. Time intervals use the midpoint.',
   'Panels: XY, XZ, YZ, X-rho; corresponding relative-position panels follow. XY and XZ have vertically centered Earth and margins around all spacecraft. Coordinates GSM. Position in km: '+JSON.stringify(record.positionKm)+'. Earth radius 6372 km follows the existing routine.',
   'Source: '+record.sourceType+'. MEC CDFs or SSCWeb original JSON are archived under Z:\\SPART-WORK\\Data\\MMS.',
   'SSCWeb JSON native GSE samples and timestamps are passed directly to mms.mms4_pl_conf. Existing IRFU routines handle position interpolation and GSM conversion.',
   'Model magnetopause and bow shock follow the original routine. Parameter sources and any assumed values are printed in the figure.',
   'Ephemeris services: https://lasp.colorado.edu/mms/sdc/public/ and https://sscweb.gsfc.nasa.gov/WebServices/REST/',
  ].join('\n'));
 }
}
await fs.writeFile(path.join(AUDIT,'ppt_slide_index.json'),JSON.stringify(index,null,2));
const candidate=path.join(WORK,'candidate.pptx');
console.log('EXPORT',p.slides.items.length);
await(await PresentationFile.exportPptx(p)).save(candidate);
const final=path.join(WORK,'output',name);
await finalizePresentation({
 workspaceDir:WORK,candidatePath:candidate,finalPath:final,explicitTotalSlideCount:127,
 requiredNativeTableOwnerSlides:[],requiredNativeChartOwnerSlides:[],pythonExecutable:PYTHON,
 integrityValidatorPath:path.join(SKILL,'container_tools/inspect_presentation_package_integrity.py'),
 layoutValidatorPath:path.join(SKILL,'container_tools/inspect_presentation_layout_geometry.py'),
 layoutArgs:['--expected-slide-size-emu','12192000,9144000','--validate-heading-fit'],
 fontPolicy:{basis:'reference',families:['Arial'],referencePath:source,referenceSha256:crypto.createHash('sha256').update(await fs.readFile(source)).digest('hex')},
 verifyArtifactToolImport:true,receiptPath:path.join(WORK,'validation.json')
});
await fs.copyFile(final,path.join(OUT,name));
console.log('FINALIZED',path.join(OUT,name));
