function Report = Case1_Audit_Figure4_Old_New_CDF
%Case1_Audit_Figure4_Old_New_CDF Read-only audit of Figure 4 source coverage.
%   Compare the old CDAWeb monthly L1/L2 subsets and current original
%   annual L2 daily/hourly CDFs for 2004 DOY 221-224 only. No averaging,
%   calibration, interpolation, flux replacement or source modification.

%% paths and the existing IRFU reader
Root = 'C:/Users/Administrator/Documents/FWD_matlab/Voyager_fu';
Case1_Add_IRFU_Path('C:/Users/Administrator/Documents/irfu-matlab-master');
Old = fullfile(Root,'Voyager_Interstellar_Monthly', ...
    'Voyager1_Selected_Event_Data','voyager1','lecp');
DataRoot = 'Z:/SPART-WORK/Data/Voyager';
Files = [string(fullfile(Old,'level1','sectored_rates','2004','08', ...
    'voyager1_lecp_lev1_sectored_rates_20040801_20040831.cdf')); ...
    string(fullfile(Old,'1d','l2','sectored_flux','2004','08', ...
    'voyager1_lecp_lev2_daily_sectored_20040801_20040831.cdf')); ...
    string(fullfile(DataRoot,'voyager1','lecp','1d','l2','sectored_flux','2004', ...
    'voyager-1_lecp_lev-2-daily-avg_20040101_v1.1.1-01.cdf')); ...
    string(fullfile(DataRoot,'voyager1','lecp','1h','l2','sectored_flux','2004', ...
    'voyager-1_lecp_lev-2-hourly-avg_20040101_v1.1.1-01.cdf'))];
Names = ["Old_CDAWeb_L1_rates";"Old_CDAWeb_L2_daily"; ...
    "Current_original_L2_daily";"Current_original_L2_hourly"];
Start = datetime(2004,8,8,'TimeZone','UTC');
Stop = datetime(2004,8,12,'TimeZone','UTC');
Report = struct('Scope','2004 DOY 221-224 only', ...
    'StartUTC',Start,'StopExclusiveUTC',Stop,'Summary',table, ...
    'Method','Read original Epoch and P1; current CDF fill/valid-range screen only.');

%% compare original records and independent time conversions
for ii = 1:numel(Files)
    P = Voyager_Read_CDF_Product(Files(ii),'lecp_sector_daily');
    if isfield(P,'FHDU_SectoredFluxes')
        Variable = 'FHDU_SectoredFluxes';
    else
        Variable = 'FHDU_SectoredRates';
    end
    Meta = P.variable_meta.(Variable);
    assert(contains(Meta.attributes.CATDESC,'PL01-PL08, P32, P1') || ...
        (isfield(P,'Hydrogen_Channels_Label') && ...
        strtrim(string(P.Hydrogen_Channels_Label(10,:))) == "P1"), ...
        'P1 channel index could not be verified from metadata.');
    F = P.(Variable);
    assert(size(F,2)==16 && size(F,3)==8,'Unexpected sector array.');
    Native = spdfcdfread(char(Files(ii)),'Variables',{'Epoch'}, ...
        'ConvertEpochToDatenum',true,'Validate',true);
    if iscell(Native), Native = Native{1}; end
    Native = datetime(Native(:),'ConvertFrom','datenum','TimeZone','UTC');
    assert(numel(Native)==numel(P.Epoch));
    EpochDifference = max(abs(seconds(Native-P.Epoch)));
    assert(EpochDifference<0.001,'IRFU and NASA Epoch conversions differ.');
    Selected = P.Epoch>=Start & P.Epoch<Stop;
    N = nnz(Selected);
    P1 = reshape(F(Selected,10,1:7),N,7);
    All7 = all(isfinite(P1)&P1>0,2);
    Source = struct('Name',Names(ii),'File',Files(ii), ...
        'SHA256',Case1_File_SHA256(Files(ii)), ...
        'GlobalAttributes',P.global_attributes,'Variable',Variable, ...
        'VariableMetadata',Meta,'Energy',P.FHDU_Energy, ...
        'TotalRecords',numel(P.Epoch),'FirstEpochUTC',min(P.Epoch), ...
        'LastEpochUTC',max(P.Epoch), ...
        'NASA_IRFU_EpochDifferenceMaxSeconds',EpochDifference, ...
        'HasDeltaT',isfield(P,'DeltaT'));
    if isfield(P,'FHDU_EnergyRange'), Source.EnergyRange=P.FHDU_EnergyRange; end
    if isfield(P,'DeltaT'), DeltaT=P.DeltaT(Selected); else, DeltaT=nan(N,1); end
    Source.WindowRecords=table(find(Selected),P.Epoch(Selected),P1,All7,DeltaT, ...
        'VariableNames',{'SourceRecord','EpochUTC','P1S1ToS7', ...
        'All7Positive','DeltaT_s'});
    for iday=0:3
        Begin=Start+days(iday);
        OnDay=P.Epoch>=Begin & P.Epoch<Begin+days(1);
        V=reshape(F(OnDay,10,1:7),nnz(OnDay),7);
        Row=table(Names(ii),Begin,nnz(OnDay), ...
            nnz(any(isfinite(V)&V>0,2)), ...
            nnz(all(isfinite(V)&V>0,2)), ...
            nnz(all(isfinite(V),2)), ...
            'VariableNames',{'Source','DayUTC','EpochRecords', ...
            'AnyP1Positive','All7P1Positive','All7P1Finite'});
        Report.Summary=[Report.Summary;Row]; %#ok<AGROW>
    end
    Report.(char(Names(ii)))=Source;
end

%% save only a diagnostic MAT in the Voyager data tree
Folder=fullfile(DataRoot,'voyager1','lecp','validation', ...
    'florinski2008_figure4','2004');
if ~isfolder(Folder), mkdir(Folder); end
RunID=char(datetime('now','TimeZone','UTC','Format','yyyyMMdd_HHmmss_SSS'));
Report.AuditFile=fullfile(Folder,['old_new_source_comparison_',RunID,'.mat']);
Report.CodeFile=[mfilename('fullpath'),'.m'];
Report.CodeSHA256=Case1_File_SHA256(Report.CodeFile);
save(Report.AuditFile,'Report');
disp(Report.Summary);
fprintf('AUDIT=%s\n',Report.AuditFile);
end
