function result = Case1_Audit_LECP_Archive(ParentDir)
%Case1_Audit_LECP_Archive Audit official yearly LECP CDFs without modifying data.
%   Reads NASA/SPDF original daily and hourly CDF files with IRFU dataobj.
%   Reports raw interval boundaries, P1 availability, metadata and SHA256.
%   No averaging, interpolation, splitting, rebinning or quality selection
%   is applied to the source data. Boolean columns are audit diagnostics.
%
%   Author: Codex, following the manual MATLAB style in MMS_fu
%   Modified: 2026-09-03

%% directories and existing readers
if nargin < 1, ParentDir = 'Z:/SPART-WORK/Data/Voyager'; end
IRFDir = 'C:/Users/Administrator/Documents/irfu-matlab-master';
addpath(IRFDir, fullfile(IRFDir,'irf'), ...
    fullfile(IRFDir,'contrib','nasa_cdf_patch'));
RunUTC = datetime('now','TimeZone','UTC');
RunStamp = char(string(RunUTC,'yyyyMMdd_HHmmss'));
OutputDir = fullfile(ParentDir,'derived','source_audit', ...
    'lecp_official_cdf_archive',RunStamp);
if ~isfolder(OutputDir), mkdir(OutputDir); end

%% read original yearly products
Manifest = struct([]);
Summary = table;
RecordList = {};
k = 0;
for ic = 1:2
    if ic == 1, Years = 2013:2021; else, Years = 2019:2020; end
    for iCadence = 1:2
        if iCadence == 1
            Cadence = '1d'; ProductName = 'daily'; LimitSeconds = 36*3600;
        else
            Cadence = '1h'; ProductName = 'hourly'; LimitSeconds = 1.5*3600;
        end
        for Year = Years
            k = k+1;
            FileName = sprintf( ...
                'voyager-%d_lecp_lev-2-%s-avg_%d0101_v1.1.1-01.cdf', ...
                ic,ProductName,Year);
            SourceFile = fullfile(ParentDir,sprintf('voyager%d',ic), ...
                'lecp',Cadence,'l2','sectored_flux',num2str(Year),FileName);
            SourceURL = sprintf(['https://spdf.gsfc.nasa.gov/pub/data/' ...
                'voyager/voyager%d/particle/lecp/final-cdf/' ...
                'lev-2-%s-avg/%s'],ic,ProductName,FileName);
            if ~isfile(SourceFile)
                error('LECPAudit:MissingFile','Original CDF missing: %s',SourceFile);
            end
            fprintf('Audit V%d %d %s\n',ic,Year,Cadence);
            CDF = dataobj(SourceFile);
            EpochRaw = getv(CDF,'Epoch');
            DeltaRaw = getv(CDF,'DeltaT');
            FluxRaw = getv(CDF,'FHDU_SectoredFluxes');
            UncertaintyRaw = getv(CDF,'FHDU_SectoredFluxUncertainties');
            EnergyRaw = getv(CDF,'FHDU_Energy');
            RangeRaw = getv(CDF,'FHDU_EnergyRange');
            LabelRaw = getv(CDF,'Hydrogen_Channels_Label');
            SectorRaw = getv(CDF,'SectorIterator');
            QualityRaw = getv(CDF,'FHDU_SectoredQuality');
            Labels = strtrim(string(LabelRaw.data));
            P1Index = find(Labels == "P1");
            assert(isscalar(P1Index),'P1 label must identify exactly one channel.');
            assert(isequal(double(SectorRaw.data(:))',(1:8)), ...
                'Unexpected sector order in original CDF.');
            N = EpochRaw.nrec;
            assert(size(FluxRaw.data,1)==N && size(FluxRaw.data,2)==16 ...
                && size(FluxRaw.data,3)==8,'Unexpected IRFU flux shape.');
            Epoch = datetime(EpochTT(int64(EpochRaw.data(:))).epochUnix, ...
                'ConvertFrom','posixtime','TimeZone','UTC');
            DeltaT = double(DeltaRaw.data(:));
            EndUTC = Epoch + seconds(DeltaT);
            P1 = reshape(double(FluxRaw.data(:,P1Index,1:7)),N,7);
            P1Uncertainty = reshape(double( ...
                UncertaintyRaw.data(:,P1Index,1:7)),N,7);
            FiniteNotFill = isfinite(P1) & P1 ~= double(FluxRaw.FILLVAL);
            WithinBounds = FiniteNotFill & P1 >= double(FluxRaw.VALIDMIN) ...
                & P1 <= double(FluxRaw.VALIDMAX);
            UncertaintyValid = isfinite(P1Uncertainty) ...
                & P1Uncertainty ~= double(UncertaintyRaw.FILLVAL) ...
                & P1Uncertainty >= double(UncertaintyRaw.VALIDMIN) ...
                & P1Uncertainty <= double(UncertaintyRaw.VALIDMAX);
            All7 = all(WithinBounds,2);
            All7Finite = all(FiniteNotFill,2);
            All7WithUncertainty = All7 & all(UncertaintyValid,2);
            Duration = DeltaT(All7);
            if isempty(Duration)
                Percentiles = nan(1,7);
            else
                Percentiles = prctile(Duration,[0,25,50,75,90,95,100]);
            end
            OneDay = DeltaT >= 0 & EndUTC <= dateshift(Epoch,'start','day')+days(1);
            OneHour = DeltaT >= 0 & EndUTC <= dateshift(Epoch,'start','hour')+hours(1);
            P1Quality = reshape(double(QualityRaw.data(:,P1Index,1:7)),N,7);
            QualityText = strings(N,1);
            for ii = 1:N, QualityText(ii) = strjoin(string(P1Quality(ii,:)),','); end
            Records = table(repmat(ic,N,1),repmat(string(Cadence),N,1), ...
                repmat(Year,N,1),(1:N)',string(EpochRaw.data(:)), ...
                string(Epoch,'yyyy-MM-dd''T''HH:mm:ss.SSSSSSSSS''Z'''), ...
                string(EndUTC,'yyyy-MM-dd''T''HH:mm:ss.SSSSSSSSS''Z'''), ...
                DeltaT,All7Finite,All7,All7WithUncertainty,OneDay,OneHour, ...
                QualityText,repmat(string(SourceFile),N,1), ...
                'VariableNames',{'Spacecraft','Cadence','Year','Record', ...
                'EpochTT2000','EpochUTC','EndUTC','DeltaTSeconds', ...
                'P1All7FiniteNotFill','P1All7WithinValidBounds', ...
                'P1All7WithValidUncertainty','IntervalWithinOneUTCDay', ...
                'IntervalWithinOneUTCHour','P1QualityS1ToS7','SourceFile'});
            RecordList{k} = Records; %#ok<AGROW>
            Row = table(ic,string(Cadence),Year,N, ...
                numel(unique(dateshift(Epoch,'start','day'))),nnz(All7), ...
                nnz(All7WithUncertainty),Percentiles(1),Percentiles(2), ...
                Percentiles(3),Percentiles(4),Percentiles(5),Percentiles(6), ...
                Percentiles(7),nnz(All7 & DeltaT > LimitSeconds), ...
                nnz(All7 & ~OneDay),nnz(All7 & ~OneHour), ...
                Records.EpochUTC(1),Records.EpochUTC(end), ...
                'VariableNames',{'Spacecraft','Cadence','Year','Records', ...
                'DistinctStartDays','P1All7ValidRecords','P1All7WithUncertainty', ...
                'DurationMinSeconds','DurationP25Seconds','DurationMedianSeconds', ...
                'DurationP75Seconds','DurationP90Seconds','DurationP95Seconds', ...
                'DurationMaxSeconds','ValidRecordsAboveCadenceAuditLimit', ...
                'ValidRecordsCrossingUTCDay','ValidRecordsCrossingUTCHour', ...
                'FirstEpochUTC','LastEpochUTC'});
            Summary = [Summary;Row]; %#ok<AGROW>
            D = dir(SourceFile);
            Entry = struct('spacecraft',ic,'cadence',Cadence,'year',Year, ...
                'source_url',SourceURL,'local_file',SourceFile,'bytes',D.bytes, ...
                'sha256',fileSHA256(SourceFile),'file_version','v1.1.1-01', ...
                'audit_utc',char(string(RunUTC)), ...
                'cdf_epoch_meta',withoutData(EpochRaw), ...
                'cdf_delta_t_meta',withoutData(DeltaRaw), ...
                'cdf_flux_meta',withoutData(FluxRaw), ...
                'cdf_uncertainty_meta',withoutData(UncertaintyRaw), ...
                'cdf_energy_meta',withoutData(EnergyRaw), ...
                'cdf_energy_range_meta',withoutData(RangeRaw), ...
                'cdf_quality_meta',withoutData(QualityRaw), ...
                'irfu_flux_shape',size(FluxRaw.data), ...
                'irfu_energy_shape',size(EnergyRaw.data), ...
                'sector_order',double(SectorRaw.data(:))', ...
                'hydrogen_channel_labels',Labels(:)', ...
                'p1_index',P1Index, ...
                'p1_energy_values',unique(double(EnergyRaw.data(:,P1Index)))', ...
                'p1_range_first_record',reshape(double(RangeRaw.data(1,:,P1Index)),1,[]));
            if k == 1, Manifest = Entry; else, Manifest(k) = Entry; end %#ok<AGROW>
        end
    end
end

%% record-level and event-window diagnostics
Records = vertcat(RecordList{:});
Catalog = Case1_Event_Catalog();
EventAudit = table;
for ii = 1:height(Catalog)
    WindowStart = Catalog.StartUTC(ii)-days(7);
    WindowEnd = Catalog.StartUTC(ii)+days(8);
    for Cadence = ["1d","1h"]
        Select = Records.Spacecraft == Catalog.Spacecraft(ii) & Records.Cadence == Cadence;
        R = Records(Select,:);
        T = datetime(R.EpochUTC,'InputFormat', ...
            'yyyy-MM-dd''T''HH:mm:ss.SSSSSSSSS''Z''','TimeZone','UTC');
        Stop = datetime(R.EndUTC,'InputFormat', ...
            'yyyy-MM-dd''T''HH:mm:ss.SSSSSSSSS''Z''','TimeZone','UTC');
        Starts = T >= WindowStart & T < WindowEnd;
        Overlaps = T < WindowEnd & Stop > WindowStart;
        Center = T >= Catalog.StartUTC(ii) & T < Catalog.StartUTC(ii)+days(1);
        V = R.P1All7WithinValidBounds;
        Row = table(Catalog.EventID(ii),Catalog.Spacecraft(ii), ...
            string(Catalog.StartUTC(ii),'yyyy-MM-dd'),Cadence, ...
            nnz(Starts),nnz(Overlaps),nnz(Starts & V),nnz(Overlaps & V), ...
            nnz(Starts & V & R.IntervalWithinOneUTCDay), ...
            nnz(Starts & V & R.IntervalWithinOneUTCHour), ...
            nnz(Center & V),nnz(Center & V & R.IntervalWithinOneUTCDay), ...
            'VariableNames',{'EventID','Spacecraft','EventDate','Cadence', ...
            'RecordsStartingInWindow','RecordsOverlappingWindow', ...
            'ValidP1StartingInWindow','ValidP1OverlappingWindow', ...
            'ValidP1StartingInWindowWithinUTCDay', ...
            'ValidP1StartingInWindowWithinUTCHour', ...
            'ValidP1StartingOnCenterDay','ValidP1CenterDayWithinUTCDay'});
        EventAudit = [EventAudit;Row]; %#ok<AGROW>
    end
end

%% audit products only; original CDFs remain unchanged
ManifestFile = fullfile(OutputDir,'LECP_Original_CDF_Manifest.json');
SummaryFile = fullfile(OutputDir,'LECP_Duration_Summary.csv');
RecordsFile = fullfile(OutputDir,'LECP_Record_Interval_Audit.csv');
EventsFile = fullfile(OutputDir,'LECP_49_Event_Availability_Audit.csv');
ComparisonFile = fullfile(OutputDir,'LECP_Old_Subset_Comparison.json');
WriteJSON(ManifestFile,Manifest);
writetable(Summary,SummaryFile);
writetable(Records,RecordsFile);
writetable(EventAudit,EventsFile);
Comparison = compareOldSubset(ParentDir,Manifest);
WriteJSON(ComparisonFile,Comparison);
result = struct('OutputDir',OutputDir,'ManifestFile',ManifestFile, ...
    'SummaryFile',SummaryFile,'RecordsFile',RecordsFile,'EventsFile',EventsFile, ...
    'ComparisonFile',ComparisonFile);
disp(Summary);
disp(result);
end

function Report = compareOldSubset(ParentDir,Manifest)
OldFile = fullfile(ParentDir,'voyager1','lecp','1d','l2','sectored_flux', ...
    '2013-2021','voyager1_lecp_p1_sectored_daily_case1_20130102_20210525.cdf');
OldCDF = dataobj(OldFile);
OldEpoch = getv(OldCDF,'Epoch');
OldFlux = getv(OldCDF,'FHDU_SectoredFluxes');
OldSigma = getv(OldCDF,'FHDU_SectoredFluxUncertainties');
assert(strcmp(OldEpoch.type,'tt2000'),'Exact comparison requires TT2000.');
E = int64([]); F = []; S = [];
for ii = 1:numel(Manifest)
    if Manifest(ii).spacecraft ~= 1 || ~strcmp(Manifest(ii).cadence,'1d'), continue, end
    CDF = dataobj(Manifest(ii).local_file);
    Epoch = getv(CDF,'Epoch'); Flux = getv(CDF,'FHDU_SectoredFluxes');
    Sigma = getv(CDF,'FHDU_SectoredFluxUncertainties');
    E = [E;int64(Epoch.data(:))]; %#ok<AGROW>
    F = cat(1,F,Flux.data); S = cat(1,S,Sigma.data);
end
[Matched,Location] = ismember(int64(OldEpoch.data(:)),E);
Start = EpochTT('2013-01-02T00:00:00Z');
Stop = EpochTT('2021-05-26T00:00:00Z');
InRequest = E >= Start.ttns & E < Stop.ttns;
Extra = ~ismember(E,int64(OldEpoch.data(:)));
Report = struct('old_file',OldFile,'old_sha256',fileSHA256(OldFile), ...
    'requested_start_utc','2013-01-02T00:00:00Z', ...
    'requested_stop_exclusive_utc','2021-05-26T00:00:00Z', ...
    'old_records',numel(OldEpoch.data),'original_full_year_records',numel(E), ...
    'original_records_in_requested_interval',nnz(InRequest), ...
    'old_epochs_matched_exact_tt2000',nnz(Matched), ...
    'old_epochs_absent_from_original',nnz(~Matched), ...
    'all_hydrogen_fluxes_exact_equal', ...
        isequaln(OldFlux.data(Matched,:,:),F(Location(Matched),:,:)), ...
    'all_hydrogen_uncertainties_exact_equal', ...
        isequaln(OldSigma.data(Matched,:,:),S(Location(Matched),:,:)), ...
    'extra_original_records_in_requested_interval',nnz(Extra & InRequest), ...
    'extra_original_records_before_requested_start',nnz(Extra & E < Start.ttns), ...
    'extra_original_records_after_requested_stop',nnz(Extra & E >= Stop.ttns), ...
    'processing','Exact TT2000 and array-value comparison; no averaging or filling.');
disp(Report);
end

function meta = withoutData(raw)
meta = rmfield(raw,'data');
end

function hash = fileSHA256(FileName)
fid = fopen(FileName,'rb');
assert(fid >= 0,'Cannot read source file for checksum.');
Clean = onCleanup(@() fclose(fid)); %#ok<NASGU>
Digest = java.security.MessageDigest.getInstance('SHA-256');
while ~feof(fid)
    Bytes = fread(fid,1024*1024,'*uint8');
    Digest.update(Bytes);
end
HashBytes = typecast(Digest.digest(),'uint8');
hash = lower(reshape(dec2hex(HashBytes,2).',1,[]));
end

function WriteJSON(FileName,Value)
fid = fopen(FileName,'w','n','UTF-8');
assert(fid >= 0,'Cannot write audit manifest.');
Clean = onCleanup(@() fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(Value,'PrettyPrint',true));
end
