function Report = Case1_Audit_L1_Source_Readiness
%Case1_Audit_L1_Source_Readiness Audit the requested L1 annual CDF sources.
%   Read only 2004 and 2013-2021 official annual L1 files. Validate fields,
%   labels, sector order, source hashes, and original DeltaT availability.
%   Detailed particle diagnostics are limited to Figure 4, 2004 DOY 221-224.
%   No averaging, calibration, interpolation, filtering of stored sources,
%   or changes to production figures/programs are performed.

%% requested source files and existing reader
DataRoot='Z:/SPART-WORK/Data/Voyager';
CodeRoot='C:/Users/Administrator/Documents/FWD_matlab/Voyager_fu';
Case1_Add_IRFU_Path('C:/Users/Administrator/Documents/irfu-matlab-master');
Years=[2004,2013:2021];
Report=struct('Scope','Requested years: 2004 and 2013-2021 only', ...
    'SourceManifest',table,'SourceMetadata',struct([]));
Start=datetime(2004,8,8,'TimeZone','UTC');
Stop=datetime(2004,8,12,'TimeZone','UTC');
Report.Figure4Summary=table;

%% annual source validation
for ii=1:numel(Years)
    Year=Years(ii);
    Name=sprintf('voyager-1_lecp_lev-1-rates_%d0101_v1.1.1-01.cdf',Year);
    Source=fullfile(DataRoot,'voyager1','lecp','native','l1', ...
        'sectored_rates',num2str(Year),Name);
    URL=['https://spdf.gsfc.nasa.gov/pub/data/voyager/voyager1/', ...
        'particle/lecp/final-cdf/lev-1-rates/',Name];
    assert(isfile(Source),'Missing requested annual source: %s',Source);
    P=Voyager_Read_CDF_Product(Source,'lecp_sector_daily');
    Needed={'Epoch','DeltaT','FHDU_SectoredRates', ...
        'FHDU_SectoredRateUncertainties','FHDU_EnergyRange', ...
        'Hydrogen_Channels_Label','SectorIterator'};
    assert(all(isfield(P,Needed)),'Missing L1 source fields: %s',Source);
    Labels=strtrim(string(P.Hydrogen_Channels_Label));
    Channel=find(Labels=="P1");
    assert(isequal(Channel,10),'P1 label mismatch.');
    assert(isequal(double(P.SectorIterator(:))',1:8),'Sector order mismatch.');
    N=numel(P.Epoch);
    assert(isequal(size(P.FHDU_SectoredRates),[N,16,8]));
    Info=dir(Source);
    Hash=Case1_File_SHA256(Source);
    Row=table(Year,string(Source),string(URL),Info.bytes,string(Hash),N, ...
        min(P.Epoch),max(P.Epoch),true,nnz(P.DeltaT<0), ...
        string(P.variable_meta.FHDU_SectoredRates.attributes.UNITS), ...
        'VariableNames',{'Year','SourceFile','SourceURL','Bytes','SHA256', ...
        'Records','FirstEpochUTC','LastEpochUTC','HasOriginalDeltaT', ...
        'NegativeDeltaTRecordsInAnnualFile','RateUnits'});
    Report.SourceManifest=[Report.SourceManifest;Row]; %#ok<AGROW>
    Metadata=struct('Year',Year,'GlobalAttributes',P.global_attributes, ...
        'VariableMetadata',P.variable_meta,'P1ChannelIndex',Channel, ...
        'P1Energy',unique(P.FHDU_Energy(:,Channel)), ...
        'P1EnergyRange',unique(P.FHDU_EnergyRange(:,:,Channel),'rows'), ...
        'SectorOrder',double(P.SectorIterator(:))');
    if ii==1
        Report.SourceMetadata=Metadata;
    else
        Report.SourceMetadata(ii)=Metadata;
    end
    fprintf('L1_SOURCE %d: %d records, DeltaT present, %d bytes\n',Year,N,Info.bytes);
    if Year~=2004, continue, end
    Native=spdfcdfread(Source,'Variables',{'Epoch'}, ...
        'ConvertEpochToDatenum',true,'Validate',true);
    if iscell(Native), Native=Native{1}; end
    Native=datetime(Native(:),'ConvertFrom','datenum','TimeZone','UTC');
    Difference=max(abs(seconds(Native-P.Epoch)));
    assert(numel(Native)==N && Difference<0.001, ...
        'NASA and IRFU Epoch readers disagree.');
    Report.Figure4EpochReaderDifferenceMaxSeconds=Difference;
    Within=P.Epoch>=Start & P.Epoch<Stop;
    Rows=find(Within);
    Rates=reshape(P.FHDU_SectoredRates(Within,Channel,1:7),nnz(Within),7);
    Sigma=reshape(P.FHDU_SectoredRateUncertainties(Within,Channel,1:7),nnz(Within),7);
    DT=P.DeltaT(Within);
    All7=all(isfinite(Rates)&Rates>0,2);
    T=table(Rows,P.Epoch(Within),DT,Rates,Sigma,All7, ...
        ~(DT<0),All7 & ~(DT<0),'VariableNames', ...
        {'SourceRecord','EpochUTC','DeltaT_s','P1RateS1ToS7', ...
        'P1SigmaS1ToS7','All7Positive','TimeRetained','All7PositiveRetained'});
    T.Properties.UserData=struct('SourceFile',Source,'SourceURL',URL, ...
        'SourceSHA256',Hash,'OriginalEnergyMetadata',Metadata, ...
        'Method','Original rate and sigma; only count validity and DeltaT<0 flags; no calibration.');
    Report.Figure4Records=T;
    for iday=0:3
        Begin=Start+days(iday);
        OnDay=T.EpochUTC>=Begin & T.EpochUTC<Begin+days(1);
        R=T.P1RateS1ToS7(OnDay,:); D=T.DeltaT_s(OnDay);
        Row=table(Begin,nnz(OnDay),nnz(D<0), ...
            nnz(T.All7Positive(OnDay)),nnz(T.All7PositiveRetained(OnDay)), ...
            sum(isfinite(R),1),sum(isfinite(R)&R>0,1), ...
            min(D),median(D),max(D),'VariableNames', ...
            {'DayUTC','Records','NegativeDeltaT','All7Positive', ...
            'All7PositiveRetained','FiniteS1ToS7','PositiveS1ToS7', ...
            'MinDeltaT_s','MedianDeltaT_s','MaxDeltaT_s'});
        Report.Figure4Summary=[Report.Figure4Summary;Row]; %#ok<AGROW>
    end
    Annual2004=P;
end

%% validate the older CDAWeb subset against the annual parent for these days
OldFile=fullfile(CodeRoot,'Voyager_Interstellar_Monthly', ...
    'Voyager1_Selected_Event_Data','voyager1','lecp','level1', ...
    'sectored_rates','2004','08', ...
    'voyager1_lecp_lev1_sectored_rates_20040801_20040831.cdf');
Old=Voyager_Read_CDF_Product(OldFile,'lecp_sector_daily');
OldRows=find(Old.Epoch>=Start & Old.Epoch<Stop);
NewRows=find(Annual2004.Epoch>=Start & Annual2004.Epoch<Stop);
assert(numel(OldRows)==numel(NewRows),'Old subset record count differs.');
TimeDifference=abs(seconds(Old.Epoch(OldRows)-Annual2004.Epoch(NewRows)));
assert(all(TimeDifference<0.001),'Old subset Epochs differ beyond CDF precision.');
SameRates=isequaln(Old.FHDU_SectoredRates(OldRows,:,:), ...
    Annual2004.FHDU_SectoredRates(NewRows,:,:));
SameSigma=isequaln(Old.FHDU_SectoredRateUncertainties(OldRows,:,:), ...
    Annual2004.FHDU_SectoredRateUncertainties(NewRows,:,:));
assert(SameRates && SameSigma,'Old subset rate or uncertainty differs.');
Report.OldSubsetComparison=struct('OldSourceFile',OldFile, ...
    'OldSourceSHA256',Case1_File_SHA256(OldFile), ...
    'OldSourceGlobalAttributes',Old.global_attributes, ...
    'OldSubsetHasDeltaT',isfield(Old,'DeltaT'), ...
    'ComparedRecords',numel(OldRows), ...
    'EpochDifferenceMaxSeconds',max(TimeDifference), ...
    'All16ChannelsAll8SectorsRatesIdentical',SameRates, ...
    'All16ChannelsAll8SectorsSigmaIdentical',SameSigma, ...
    'OldSourceRecord',OldRows,'AnnualSourceRecord',NewRows);

%% conversion provenance: the previous implementation is not a L2 calibration
Report.LegacyConversionEvidence=struct( ...
    'CodeFile',fullfile(CodeRoot,'Voyager_Interstellar_Monthly', ...
    'Voyager1_Replot_Selected_Events_PaperStyle.m'), ...
    'CodeLine',1022,'Expression','1/(0.44*(1.78-0.57))', ...
    'Factor',1/(0.44*(1.78-0.57)), ...
    'Status',['Found in previous plotting code and its Florinski comment; ', ...
    'this audit does not establish an official L2-equivalent calibration. ', ...
    'Original annual L1 metadata retains 0.57-0.89 MeV and rates in counts/s.']);
Report.Download2004=struct('SourceURL',Report.SourceManifest.SourceURL(1), ...
    'SourceFile',Report.SourceManifest.SourceFile(1), ...
    'Method','curl direct HTTPS NASA/SPDF; original response bytes; no re-encoding', ...
    'RawCDFReadVerified',true,'CopiedOldSubsetToDataRoot',false);

%% diagnostic MAT only; no production edits
Folder=fullfile(DataRoot,'voyager1','lecp','validation', ...
    'l1_source_readiness');
if ~isfolder(Folder), mkdir(Folder); end
RunID=char(datetime('now','TimeZone','UTC','Format','yyyyMMdd_HHmmss_SSS'));
Report.AuditFile=fullfile(Folder,['l1_source_readiness_',RunID,'.mat']);
Report.CodeFile=[mfilename('fullpath'),'.m'];
Report.CodeSHA256=Case1_File_SHA256(Report.CodeFile);
Report.Passed=true;
save(Report.AuditFile,'Report');
disp(Report.Figure4Summary);
disp(Report.OldSubsetComparison);
fprintf('AUDIT=%s\n',Report.AuditFile);
end
