function result = Case1_Audit_LECP_Level1(ParentDir, OutputDir, Spacecraft, Year)
%Case1_Audit_LECP_Level1 Audit original yearly rates without calibration.
%   Counts records and reports their original interval boundaries, P1 sector
%   availability and event-window coverage. No rate-to-flux conversion,
%   averaging, interpolation, splitting, rebinning or quality selection.
%
%   Author: Codex, following the manual MATLAB style in MMS_fu
%   Modified: 2026-09-03

%% directories and existing reader
if nargin < 1, ParentDir = 'Z:/SPART-WORK/Data/Voyager'; end
if nargin < 3, Spacecraft = 1; end
if nargin < 4, Year = 2016; end
if nargin < 2
    OutputDir = fullfile(ParentDir,'derived','source_audit', ...
        'lecp_official_cdf_archive','20260902_173114');
end
assert(isfolder(OutputDir),'Existing audit directory required.');
IRFDir = 'C:/Users/Administrator/Documents/irfu-matlab-master';
addpath(IRFDir,fullfile(IRFDir,'irf'), ...
    fullfile(IRFDir,'contrib','nasa_cdf_patch'));
FileName = sprintf('voyager-%d_lecp_lev-1-rates_%d0101_v1.1.1-01.cdf',Spacecraft,Year);
SourceFile = fullfile(ParentDir,sprintf('voyager%d',Spacecraft),'lecp','native','l1', ...
    'sectored_rates',num2str(Year),FileName);
SourceURL = sprintf(['https://spdf.gsfc.nasa.gov/pub/data/voyager/voyager%d/' ...
    'particle/lecp/final-cdf/lev-1-rates/%s'],Spacecraft,FileName);
CDF = dataobj(SourceFile);

%% original variables; identify P1 from the official label
E = getv(CDF,'Epoch'); D = getv(CDF,'DeltaT');
R = getv(CDF,'FHDU_SectoredRates');
U = getv(CDF,'FHDU_SectoredRateUncertainties');
Q = getv(CDF,'FHDU_SectoredQuality');
Energy = getv(CDF,'FHDU_Energy');
EnergyRange = getv(CDF,'FHDU_EnergyRange');
Label = getv(CDF,'Hydrogen_Channels_Label');
Sector = getv(CDF,'SectorIterator');
StartET = getv(CDF,'StartET'); StopET = getv(CDF,'StopET');
Labels = strtrim(string(Label.data));
P1Index = find(Labels == "P1");
assert(isscalar(P1Index),'P1 must identify exactly one channel.');
assert(isequal(double(Sector.data(:))',1:8),'Unexpected sector order.');
N = E.nrec;
assert(isequal(size(R.data),[N,16,8]),'Unexpected original rate shape.');
T = datetime(EpochTT(int64(E.data(:))).epochUnix, ...
    'ConvertFrom','posixtime','TimeZone','UTC');
DeltaT = double(D.data(:));
Stop = T + seconds(DeltaT);
P1 = reshape(double(R.data(:,P1Index,1:7)),N,7);
Sigma = reshape(double(U.data(:,P1Index,1:7)),N,7);
Valid = isfinite(P1) & P1 ~= double(R.FILLVAL) ...
    & P1 >= double(R.VALIDMIN) & P1 <= double(R.VALIDMAX);
SigmaValid = isfinite(Sigma) & Sigma ~= double(U.FILLVAL) ...
    & Sigma >= double(U.VALIDMIN) & Sigma <= double(U.VALIDMAX);
Any7 = any(Valid,2); All7 = all(Valid,2);
WithinDay = DeltaT >= 0 & Stop <= dateshift(T,'start','day')+days(1);
WithinHour = DeltaT >= 0 & Stop <= dateshift(T,'start','hour')+hours(1);
P1Quality = reshape(double(Q.data(:,P1Index,1:7)),N,7);
QualityText = strings(N,1);
for ii = 1:N, QualityText(ii) = strjoin(string(P1Quality(ii,:)),','); end
Records = table((1:N)',string(E.data(:)),utcText(T),utcText(Stop), ...
    DeltaT,sum(Valid,2),Any7,All7,All7 & all(SigmaValid,2), ...
    WithinDay,WithinHour,QualityText, ...
    'VariableNames',{'Record','EpochTT2000','EpochUTC','EndUTC', ...
    'DeltaTSeconds','ValidP1SectorsAmongS1ToS7','P1Any7Valid', ...
    'P1All7Valid','P1All7WithUncertainty','IntervalWithinOneUTCDay', ...
    'IntervalWithinOneUTCHour','P1QualityS1ToS7'});

%% availability diagnostics; these flags are not science selections
Summary = table;
for Group = ["AllRecords","AnyP1Sector","All7P1Sectors"]
    if Group == "AllRecords", V = true(N,1);
    elseif Group == "AnyP1Sector", V = Any7;
    else, V = All7;
    end
    P = prctile(DeltaT(V),[0,25,50,75,90,95,99,100]);
    Row = table(Group,nnz(V),P(1),P(2),P(3),P(4),P(5),P(6),P(7),P(8), ...
        nnz(V & DeltaT < 0),nnz(V & DeltaT == 0), ...
        nnz(V & DeltaT > 3600),nnz(V & DeltaT > 86400), ...
        nnz(V & DeltaT > 7*86400),nnz(V & WithinDay),nnz(V & WithinHour), ...
        'VariableNames',{'Group','Records','MinSeconds','P25Seconds', ...
        'MedianSeconds','P75Seconds','P90Seconds','P95Seconds','P99Seconds', ...
        'MaxSeconds','NegativeDuration','ZeroDuration','Above1Hour', ...
        'Above1Day','Above7Days','WithinUTCDay','WithinUTCHour'});
    Summary = [Summary;Row]; %#ok<AGROW>
end
Catalog = Case1_Event_Catalog();
Catalog = Catalog(Catalog.Spacecraft == Spacecraft & year(Catalog.StartUTC) == Year,:);
Events = table;
for ii = 1:height(Catalog)
    Begin = Catalog.StartUTC(ii)-days(7); End = Catalog.StartUTC(ii)+days(8);
    Starts = T >= Begin & T < End;
    Overlap = T < End & Stop > Begin;
    Center = T >= Catalog.StartUTC(ii) & T < Catalog.StartUTC(ii)+days(1);
    WholeWindow = Starts & DeltaT >= 0 & Stop <= End;
    WindowDuration = DeltaT(Starts & All7);
    WindowPercentiles = nan(1,3);
    if ~isempty(WindowDuration), WindowPercentiles = prctile(WindowDuration,[0,50,100]); end
    Row = table(Catalog.EventID(ii),utcText(Catalog.StartUTC(ii)), ...
        utcText(Begin),utcText(End),nnz(Starts),nnz(Overlap), ...
        nnz(Starts & Any7),nnz(Starts & All7),nnz(Overlap & All7), ...
        nnz(WholeWindow & All7),nnz(Starts & All7 & WithinDay), ...
        nnz(Starts & All7 & WithinHour),nnz(Center & Any7), ...
        nnz(Center & All7),nnz(Center & All7 & WithinDay), ...
        WindowPercentiles(1),WindowPercentiles(2), ...
        WindowPercentiles(3),nnz(Starts & All7 & DeltaT < 0), ...
        'VariableNames',{'EventID','CenterDayUTC','WindowStartUTC', ...
        'WindowStopExclusiveUTC','RecordsStartingInWindow', ...
        'RecordsOverlappingWindow','AnyP1StartingInWindow', ...
        'All7P1StartingInWindow','All7P1OverlappingWindow', ...
        'All7P1WhollyInsideWindow','All7P1WithinUTCDay', ...
        'All7P1WithinUTCHour','AnyP1StartingOnCenterDay', ...
        'All7P1StartingOnCenterDay','All7P1CenterDayWithinUTCDay', ...
        'All7P1DurationMinSeconds','All7P1DurationMedianSeconds', ...
        'All7P1DurationMaxSeconds','All7P1NegativeDuration'});
    Events = [Events;Row]; %#ok<AGROW>
end
FileInfo = dir(SourceFile);
Manifest = struct('spacecraft',Spacecraft,'year',Year, ...
    'source_url',SourceURL,'local_file',SourceFile, ...
    'bytes',FileInfo.bytes,'sha256',fileSHA256(SourceFile), ...
    'file_version','v1.1.1-01','audit_utc',char(utcText(datetime('now','TimeZone','UTC'))), ...
    'processing','Read-only audit; no calibration, rebinning, averaging or filling.', ...
    'records',N,'distinct_start_days',numel(unique(dateshift(T,'start','day'))), ...
    'first_epoch_utc',char(utcText(min(T))),'last_epoch_utc',char(utcText(max(T))), ...
    'rate_shape',size(R.data),'all_variable_names',{fieldnames(CDF.data)}, ...
    'p1_index',P1Index,'hydrogen_labels',Labels(:)', ...
    'p1_energy_values',unique(double(Energy.data(:,P1Index)))', ...
    'p1_energy_ranges',unique(reshape(double(EnergyRange.data(:,:,P1Index)),N,2),'rows'), ...
    'sector_order',double(Sector.data(:))', ...
    'p1_valid_record_counts_by_sector',sum(Valid,1), ...
    'record_counts_for_0_to_7_valid_sectors',histcounts(sum(Valid,2),-0.5:7.5), ...
    'deltat_minus_stopet_startet_max_abs_seconds', ...
        max(abs(DeltaT-(double(StopET.data(:))-double(StartET.data(:))))), ...
    'epoch_meta',rmfield(E,'data'),'delta_t_meta',rmfield(D,'data'), ...
    'rate_meta',rmfield(R,'data'),'uncertainty_meta',rmfield(U,'data'), ...
    'quality_meta',rmfield(Q,'data'),'energy_meta',rmfield(Energy,'data'), ...
    'energy_range_meta',rmfield(EnergyRange,'data'));

%% save diagnostics alongside the completed original-CDF audit
Stem = sprintf('LECP_V%d_%d_Level1',Spacecraft,Year);
ManifestFile = fullfile(OutputDir,[Stem '_Manifest.json']);
fid = fopen(ManifestFile,'w','n','UTF-8');
assert(fid >= 0,'Cannot write audit manifest.');
Clean = onCleanup(@() fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(Manifest,'PrettyPrint',true));
writetable(Summary,fullfile(OutputDir,[Stem '_Duration_Summary.csv']));
writetable(Records,fullfile(OutputDir,[Stem '_Record_Audit.csv']));
writetable(Events,fullfile(OutputDir,[Stem '_Event_Audit.csv']));
result = struct('OutputDir',OutputDir,'ManifestFile',ManifestFile, ...
    'Manifest',Manifest,'Summary',Summary,'Events',Events);
fprintf('V%d %d: %d records; %d any-P1; %d all-7-P1\n', ...
    Spacecraft,Year,N,nnz(Any7),nnz(All7));
end

function Text = utcText(Time)
Text = string(Time,'yyyy-MM-dd''T''HH:mm:ss.SSSSSSSSS''Z''');
end

function Hash = fileSHA256(FileName)
fid = fopen(FileName,'rb');
assert(fid >= 0,'Cannot read source file for checksum.');
Clean = onCleanup(@() fclose(fid)); %#ok<NASGU>
Digest = java.security.MessageDigest.getInstance('SHA-256');
while ~feof(fid), Digest.update(fread(fid,1024*1024,'*uint8')); end
HashBytes = typecast(Digest.digest(),'uint8');
Hash = lower(reshape(dec2hex(HashBytes,2).',1,[]));
end
