function files = Case1_Attitude_Files(cfg)
%Case1_Attitude_Files Official raw kernels for Voyager 1 predicted attitude.
%   Existing trajectory and leap-second kernels are reused on Z:.

%% classified archive
attitudeRoot = fullfile(cfg.DataRoot, 'voyager1', 'attitude', 'spice');
ckRoot = fullfile(attitudeRoot, 'ck', '7d_predicted', '1977-2027');
supportRoot = fullfile(attitudeRoot, 'support');
positionRoot = fullfile(cfg.DataRoot, 'voyager1', 'ephemeris', ...
    'spice', 'kernels');
base = "https://naif.jpl.nasa.gov/pub/naif/";

%% exact sources; the CSV interface is not used here
Role = ["CK"; "SCLK"; "FK"; "PCK"; "LSK"; "SPK"; "COMMENT"];
SourceFile = string({ ...
    fullfile(ckRoot, 'vgr1_super.bc'); ...
    fullfile(supportRoot, 'sclk', 'vg100051.tsc'); ...
    fullfile(supportRoot, 'fk', 'vg1_v02.tf'); ...
    fullfile(supportRoot, 'pck', 'pck00011.tpc'); ...
    fullfile(positionRoot, 'naif0012.tls'); ...
    fullfile(positionRoot, 'vgr1.x2100.bsp'); ...
    fullfile(ckRoot, 'vgr1_super_v2.cmt')});
SourceURL = base + [ ...
    "VOYAGER/kernels/ck/vgr1_super.bc"; ...
    "VOYAGER/kernels/sclk/vg100051.tsc"; ...
    "VOYAGER/kernels/fk/vg1_v02.tf"; ...
    "generic_kernels/pck/pck00011.tpc"; ...
    "generic_kernels/lsk/naif0012.tls"; ...
    "VOYAGER/kernels/spk/vgr1.x2100.bsp"; ...
    "VOYAGER/kernels/ck/vgr1_super_v2.cmt"];
files = table(Role, SourceFile, SourceURL);
end
