function result = Run_Case1_PPT_VerticalLine_Events_7d(varargin)
%Run_Case1_PPT_VerticalLine_Events_7d Validate or plot Case 1 events.
%   RESULT = Run_Case1_PPT_VerticalLine_Events_7d performs a non-plotting
%   preflight by default. It writes the event catalog, full source manifest,
%   and assumption audit into the requested output folder.
%
%   Add 'RunPlots',true only after the documented scientific settings have
%   been reviewed. Existing PNG files are preserved unless 'Overwrite',true
%   is also supplied.
%
%   Author: Codex, following the manual MATLAB style in MMS_fu
%   Modified: 2026-09-02

%% input parser
parser = inputParser;
parser.CaseSensitive = false;
addParameter(parser, 'RunPlots', false, @isLogicalScalar);
addParameter(parser, 'Overwrite', false, @isLogicalScalar);
addParameter(parser, 'Visible', false, @isLogicalScalar);
addParameter(parser, 'PADCadence', 'day', @(x) ischar(x) || isstring(x));
addParameter(parser, 'ExportPeakPAD', true, @isLogicalScalar);
addParameter(parser, 'ContextDays', [], ...
    @(x) isempty(x) || (isnumeric(x) && isscalar(x) && ...
    isfinite(x) && x>=0 && fix(x)==x));
addParameter(parser, 'LECPSourcePriority', '', @(x) ischar(x) || isstring(x));
addParameter(parser, 'EventIDs', {}, ...
    @(x) ischar(x) || isstring(x) || iscellstr(x));
parse(parser, varargin{:});
opts = parser.Results;

%% configuration and IRFU-MATLAB
cfg = Case1_Config;
if ~isempty(opts.ContextDays), cfg.ContextDays = opts.ContextDays; end
if strlength(string(opts.LECPSourcePriority))>0
    cfg.LECPSourcePriority = validatestring(opts.LECPSourcePriority, ...
        {'l2_first','l1_first'});
end
cfg.PADCadence = validatestring(opts.PADCadence, {'day', 'hour'});
cfg.ExportPeakPAD = logical(opts.ExportPeakPAD) && strcmp(cfg.PADCadence, 'hour');
nativeCDFs = cfg.LECPNativeDailyCDFs;
outputGroup = 'Epoch_daily';
if strcmp(cfg.PADCadence, 'hour')
    nativeCDFs = cfg.LECPNativeHourlyCDFs;
    outputGroup = 'Epoch_hourly';
    cfg.PitchAngleDataFolder = fullfile(cfg.DataRoot, 'voyager1', 'lecp', ...
        '1h', 'derived', 'pitch_angle', '2013-2021');
end
% Preserve previous figures and keep day/hour manifests separate.
cfg.OutputRoot = fullfile(cfg.OutputRoot, outputGroup);
cfg.CatalogFile = fullfile(cfg.OutputRoot, 'Case1_event_catalog_refactored.csv');
cfg.SourceManifestFile = fullfile(cfg.OutputRoot, 'Case1_source_manifest_refactored.csv');
cfg.RunAuditFile = fullfile(cfg.OutputRoot, 'Case1_data_processing_assumptions_refactored.txt');
cfg.ReadmeCopy = fullfile(cfg.OutputRoot, 'README_数据处理与假设_refactored.md');
Case1_Add_IRFU_Path(cfg.IRFURoot);
if ~isfolder(cfg.OutputRoot)
    [ok, message] = mkdir(cfg.OutputRoot);
    if ~ok
        error('VoyagerCase1:OutputCreate', '%s', message);
    end
end

%% event catalog
catalog = Case1_Event_Catalog;
if ~isempty(opts.EventIDs)
    requestedIDs = string(opts.EventIDs);
    selected = ismember(string(catalog.EventID), requestedIDs(:));
    catalog = catalog(selected, :);
    if isempty(catalog)
        error('VoyagerCase1:EventSelection', ...
            'No requested EventID occurs in the Case 1 catalog.');
    end
end
catalog.StartUTC.Format = 'yyyy-MM-dd';
catalog.EndUTCInclusive.Format = 'yyyy-MM-dd';
catalog.EndUTCExclusive.Format = 'yyyy-MM-dd';
writetable(catalog, cfg.CatalogFile);

catalogV1 = catalog(catalog.Spacecraft == 1, :);
catalogV2 = catalog(catalog.Spacecraft == 2, :);
cfg.LECPNativeDailyCDFs = Case1_Restrict_Source_Years( ...
    cfg.LECPNativeDailyCDFs,catalogV1,cfg.ContextDays);
cfg.LECPNativeHourlyCDFs = Case1_Restrict_Source_Years( ...
    cfg.LECPNativeHourlyCDFs,catalogV1,cfg.ContextDays);
cfg.LECPLevel1CDFs = Case1_Restrict_Source_Years( ...
    cfg.LECPLevel1CDFs,catalogV1,cfg.ContextDays);
nativeCDFs = cfg.LECPNativeDailyCDFs;
if strcmp(cfg.PADCadence,'hour'), nativeCDFs = cfg.LECPNativeHourlyCDFs; end
v1CatalogFile = fullfile(cfg.OutputRoot, ...
    'Case1_event_catalog_V1_refactored.csv');
v2CatalogFile = fullfile(cfg.OutputRoot, ...
    'Case1_event_catalog_V2_refactored.csv');
if ~isempty(catalogV1), writetable(catalogV1, v1CatalogFile); end
if ~isempty(catalogV2), writetable(catalogV2, v2CatalogFile); end

%% source-data preflight and reproducibility record
sourceManifest = Case1_Check_Data(cfg, catalog);
writetable(sourceManifest, cfg.SourceManifestFile);
copyfile(cfg.ReadmeSource, cfg.ReadmeCopy, 'f');
copyfile(fullfile(cfg.CodeRoot,'README_Level1补充通路.md'), ...
    fullfile(cfg.OutputRoot,'README_Level1补充通路.md'),'f');
copyfile(fullfile(cfg.CodeRoot,'README_三天窗口_L1优先.md'), ...
    fullfile(cfg.OutputRoot,'README_三天窗口_L1优先.md'),'f');
copyfile(fullfile(cfg.CodeRoot, 'README_预测姿态与扇区几何.md'), ...
    fullfile(cfg.OutputRoot, 'README_预测姿态与扇区几何.md'), 'f');
Case1_Write_Audit(cfg.RunAuditFile, cfg, catalog, ...
    sourceManifest, opts.RunPlots);

fprintf('Case 1 preflight: %d events, %d source rows.\n', ...
    height(catalog), height(sourceManifest));
fprintf('Required sources missing: %d\n', ...
    nnz(sourceManifest.Required & ~sourceManifest.Exists));
fprintf('LECP pointing policy: %s\n', cfg.PitchAngleMethod);

%% optional plotting
reportV1 = table;
reportV2 = table;
if logical(opts.RunPlots)
    if ~isempty(catalogV1)
        reportV1 = Voyager_Case1_Plot_Events( ...
            'Spacecraft', 1, ...
            'DataRoot', cfg.DataRoot, ...
            'OutputFolder', cfg.OutputRoot, ...
            'CatalogFile', v1CatalogFile, ...
            'ReportFolder', cfg.OutputRoot, ...
            'ReportTag', 'Case1_PPT_V1_7d_refactored', ...
            'ContextMonths', 0, ...
            'ContextDays', cfg.ContextDays, ...
            'ShowEventBoundaries', cfg.ShowEventBoundaries, ...
            'Overwrite', opts.Overwrite, ...
            'Visible', opts.Visible, ...
            'ExportDPI', cfg.ExportDPI, ...
            'MAGGapHours', cfg.MAGGapHours, ...
            'FluxGapHours', cfg.FluxGapHours, ...
            'LECPDailyAverage', cfg.LECPDailyAverage, ...
            'CRSDisplay', 'lecp_p1_pitch_angle', ...
            'LECPSectoredDailyCDF', cfg.LECPSectoredDailyCDF, ...
            'LECPNativeCDFs', nativeCDFs, ...
            'LECPLevel1Fallback', cfg.LECPLevel1Fallback, ...
            'LECPLevel1CDFs', cfg.LECPLevel1CDFs, ...
            'LECPSourcePriority', cfg.LECPSourcePriority, ...
            'PADCadence', cfg.PADCadence, ...
            'HourlyAttitudeApproved', cfg.HourlyAttitudeApproved, ...
            'AccumulationPolicy', cfg.AccumulationPolicy, ...
            'LECPSectorAverageDays', cfg.LECPSectorAverageDays, ...
            'PitchAngleMethod', cfg.PitchAngleMethod, ...
            'PredictedAttitudeApproved', cfg.PredictedAttitudeApproved, ...
            'NominalLECPGeometryApproved', cfg.NominalLECPGeometryApproved, ...
            'AttitudeDailyHourUTC', cfg.AttitudeDailyHourUTC, ...
            'LECPSectorPointingFile', cfg.LECPSectorPointingFile, ...
            'LECPBackgroundMode', cfg.LECPBackgroundMode, ...
            'PitchMergeToleranceDeg', cfg.PitchMergeToleranceDeg, ...
            'ColorPercentiles', cfg.ColorPercentiles, ...
            'ExportPitchAngleTable', cfg.ExportPitchAngleTable, ...
            'PitchAngleDataFolder', cfg.PitchAngleDataFolder, ...
            'P1DisplayEnergyMeV', cfg.P1DisplayEnergyMeV, ...
            'ExportPeakPAD', cfg.ExportPeakPAD, ...
            'PeakPADFolder', cfg.PeakPADFolder, ...
            'PeakPADDataFolder', cfg.PeakPADDataFolder, ...
            'LineYMarginFraction', cfg.LineYMarginFraction, ...
            'CRSColorLimits', cfg.CRSColorLimits);
    end

    if ~isempty(catalogV2)
        reportV2 = Voyager_Case1_Plot_Events( ...
            'Spacecraft', 2, ...
            'DataRoot', cfg.DataRoot, ...
            'OutputFolder', cfg.OutputRoot, ...
            'CatalogFile', v2CatalogFile, ...
            'ReportFolder', cfg.OutputRoot, ...
            'ReportTag', 'Case1_PPT_V2_7d_refactored', ...
            'ContextMonths', 0, ...
            'ContextDays', cfg.ContextDays, ...
            'ShowEventBoundaries', cfg.ShowEventBoundaries, ...
            'Overwrite', opts.Overwrite, ...
            'Visible', opts.Visible, ...
            'ExportDPI', cfg.ExportDPI, ...
            'MAGGapHours', cfg.MAGGapHours, ...
            'FluxGapHours', cfg.FluxGapHours, ...
            'LECPDailyAverage', cfg.LECPDailyAverage, ...
            'CRSDisplay', cfg.CRSDisplay, ...
            'LineYMarginFraction', cfg.LineYMarginFraction, ...
            'CRSColorLimits', cfg.CRSColorLimits, ...
            'ColorPercentiles', cfg.ColorPercentiles);
    end

    report = [reportV1; reportV2];
    writetable(report, fullfile(cfg.OutputRoot, ...
        'Case1_plot_manifest_all_refactored.csv'));
    save(fullfile(cfg.OutputRoot, ...
        'Case1_plot_report_all_refactored.mat'), ...
        'report', 'reportV1', 'reportV2', 'catalog', ...
        'sourceManifest', 'cfg', '-v7.3');
end

%% return
result = struct;
result.Config = cfg;
result.Catalog = catalog;
result.SourceManifest = sourceManifest;
result.ReportV1 = reportV1;
result.ReportV2 = reportV2;
result.PlotsExecuted = logical(opts.RunPlots);
end

function tf = isLogicalScalar(value)
tf = (islogical(value) || isnumeric(value)) && isscalar(value);
end
