function result = Run_Case1_2020E01_Current3D_NoSectorMerge(varargin)
%Run_Case1_2020E01_Current3D_NoSectorMerge Replot 2020-E01 with current code.
%   The current Voyager_Case1_Plot_Events renderer reads the original 2020
%   annual LECP CDFs and monthly COHO CDFs.  It uses the approved predicted
%   CK attitude and nominal LECP geometry in full 3-D.  S1--S7 remain seven
%   independent display cells; no pitch-angle or flux merging is permitted.
%
%   All generated figures, reports, audits and logs are written below the
%   Recovery-Work-Voyager_betatron result tree.  The Z: archive is read-only
%   for this run.
%
%   Author: Codex, following the manual MATLAB style in MMS_fu
%   Modified: 2026-09-07

%% options and formal project paths
parser = inputParser;
addParameter(parser, 'Overwrite', true, ...
    @(x) islogical(x) && isscalar(x));
addParameter(parser, 'Visible', false, ...
    @(x) islogical(x) && isscalar(x));
parse(parser, varargin{:});
runOptions = parser.Results;

cfg = Case1_Config;
Case1_Add_IRFU_Path(cfg.IRFURoot);
resultRoot = fullfile('C:\Users\Administrator\Documents', ...
    'Recovery-Work-Voyager_betatron', ...
    'Case1_PPT_VerticalLine_Events_7d', ...
    'Current_2020E01_NoSectorMerge');
figureFolder = fullfile(resultRoot, 'figure');
reportFolder = fullfile(resultRoot, 'report');
pitchAngleFolder = fullfile(resultRoot, 'audit', 'pitch_angle');
peakFolder = fullfile(resultRoot, 'figure', 'peak_pad_unused');
peakDataFolder = fullfile(resultRoot, 'audit', 'peak_pad_unused');
folders = {resultRoot, figureFolder, reportFolder, pitchAngleFolder};
for ii = 1:numel(folders)
    if ~isfolder(folders{ii}), mkdir(folders{ii}); end
end

logFile = fullfile(reportFolder, 'Run_Case1_2020E01_Current3D_NoSectorMerge.log');
diary('off');
diary(logFile);
logCleanup = onCleanup(@() diary('off'));

%% exact historical event interval and one-month context
eventID = "2020-E01";
startUTC = datetime(2020, 7, 22, 'TimeZone', 'UTC');
endUTCInclusive = datetime(2020, 8, 7, 'TimeZone', 'UTC');
endUTCExclusive = datetime(2020, 8, 8, 'TimeZone', 'UTC');
catalog = table(eventID, startUTC, endUTCInclusive, endUTCExclusive, ...
    1, NaN, NaN, 'VariableNames', {'EventID', 'StartUTC', ...
    'EndUTCInclusive', 'EndUTCExclusive', 'Spacecraft', ...
    'SourceSlide', 'SourceLine'});
catalog.StartUTC.Format = 'yyyy-MM-dd';
catalog.EndUTCInclusive.Format = 'yyyy-MM-dd';
catalog.EndUTCExclusive.Format = 'yyyy-MM-dd';
catalogFile = fullfile(reportFolder, '2020-E01_event_catalog.csv');
writetable(catalog, catalogFile);

%% original website CDF inputs and pre-run byte hashes
dailyCDFs = selectYear(cfg.LECPNativeDailyCDFs, 2020);
l1CDFs = selectYear(cfg.LECPLevel1CDFs, 2020);
assert(numel(dailyCDFs) == 1 && isfile(dailyCDFs), ...
    'Exactly one original 2020 LECP Level-2 daily CDF is required.');
assert(numel(l1CDFs) == 1 && isfile(l1CDFs), ...
    'Exactly one original 2020 LECP Level-1 rates CDF is required.');

cohoCDFs = strings(4, 1);
for ii = 1:4
    month = ii + 5;
    cohoCDFs(ii) = string(fullfile(cfg.DataRoot, 'voyager1', 'coho', ...
        '1hr', 'l2', 'merged_mag_plasma', '2020', ...
        sprintf('%02d', month), sprintf([ ...
        'voyager1_coho1hr_merged_mag_plasma_2020%02d01_v01.cdf'], month)));
end
assert(all(isfile(cohoCDFs)), ...
    'One or more original June--September 2020 COHO CDFs are missing.');

rawSourceFiles = [dailyCDFs; l1CDFs; cohoCDFs];
rawSourceRole = ["LECP L2 daily"; "LECP L1 native rates"; ...
    repmat("COHO L2 1 h", numel(cohoCDFs), 1)];
rawHashBefore = strings(numel(rawSourceFiles), 1);
for ii = 1:numel(rawSourceFiles)
    rawHashBefore(ii) = string(Case1_File_SHA256(char(rawSourceFiles(ii))));
end

%% current formal 3-D renderer
report = Voyager_Case1_Plot_Events( ...
    'Spacecraft', 1, ...
    'DataRoot', cfg.DataRoot, ...
    'CatalogFile', catalogFile, ...
    'OutputFolder', figureFolder, ...
    'ReportFolder', reportFolder, ...
    'ReportTag', '2020E01_current3D_no_sector_merge', ...
    'ContextMonths', 1, ...
    'ContextDays', [], ...
    'ShowEventBoundaries', false, ...
    'Overwrite', runOptions.Overwrite, ...
    'Visible', runOptions.Visible, ...
    'ExportDPI', cfg.ExportDPI, ...
    'MAGGapHours', cfg.MAGGapHours, ...
    'FluxGapHours', cfg.FluxGapHours, ...
    'LECPDailyAverage', false, ...
    'CRSDisplay', 'lecp_p1_pitch_angle', ...
    'LECPSectoredDailyCDF', cfg.LECPSectoredDailyCDF, ...
    'LECPNativeCDFs', dailyCDFs, ...
    'LECPLevel1Fallback', true, ...
    'LECPSourcePriority', 'l1_first', ...
    'LECPLevel1CDFs', l1CDFs, ...
    'PADCadence', 'day', ...
    'HourlyAttitudeApproved', cfg.HourlyAttitudeApproved, ...
    'AccumulationPolicy', 'epoch_drop_negative_deltat', ...
    'LECPSectorAverageDays', 0, ...
    'PitchAngleMethod', 'predicted_ck', ...
    'PredictedAttitudeApproved', true, ...
    'NominalLECPGeometryApproved', true, ...
    'AttitudeDailyHourUTC', 12, ...
    'LECPSectorPointingFile', '', ...
    'LECPBackgroundMode', 'none', ...
    'PitchMergeToleranceDeg', 0, ...
    'ColorPercentiles', cfg.ColorPercentiles, ...
    'ExportPitchAngleTable', false, ...
    'PitchAngleDataFolder', pitchAngleFolder, ...
    'P1DisplayEnergyMeV', [0.57 1.78], ...
    'ExportPeakPAD', false, ...
    'PeakPADFolder', peakFolder, ...
    'PeakPADDataFolder', peakDataFolder, ...
    'LineYMarginFraction', cfg.LineYMarginFraction, ...
    'CRSColorLimits', cfg.CRSColorLimits);

%% output and no-merge validation
assert(height(report) == 1, 'The current renderer must return one event row.');
assert(~contains(string(report.Status(1)), 'error'), ...
    'The current renderer reported an error: %s', string(report.Notes(1)));
expectedStart = datetime(2020, 6, 22, 'TimeZone', 'UTC');
expectedEnd = datetime(2020, 9, 8, 'TimeZone', 'UTC');
assert(report.PlotStartUTC(1) == expectedStart, ...
    'The plotted start differs from 2020-06-22 00:00 UTC.');
assert(report.PlotEndUTCExclusive(1) == expectedEnd, ...
    'The plotted exclusive end differs from 2020-09-08 00:00 UTC.');

figureFile = string(report.FigureFile(1));
pitchAngleAuditFile = string(report.PitchAngleAuditFile(1));
assert(isfile(figureFile), 'The overview PNG was not created.');
assert(isfile(pitchAngleAuditFile), ...
    'The current predicted-CK pitch-angle audit was not created.');
assert(startsWith(figureFile, string(resultRoot), 'IgnoreCase', true), ...
    'Figure escaped the formal Recovery result folder.');
assert(startsWith(pitchAngleAuditFile, string(resultRoot), 'IgnoreCase', true), ...
    'Pitch-angle audit escaped the formal Recovery result folder.');

saved = load(pitchAngleAuditFile, 'pitchAngleTable', 'sourceLECP', ...
    'sourceMAG', 'opts', 'codeManifest');
pitchAngleTable = saved.pitchAngleTable;
userData = pitchAngleTable.Properties.UserData;
assert(isfield(userData, 'SectorMergeApplied') && ...
    isequal(userData.SectorMergeApplied, false), ...
    'The saved audit does not certify that sector merging is disabled.');
assert(strcmp(saved.opts.PitchAngleMethod, 'predicted_ck') && ...
    strcmp(saved.opts.PADCadence, 'day') && ...
    strcmp(saved.opts.LECPSourcePriority, 'l1_first'), ...
    'The saved calculation options differ from the requested current path.');

paNames = cellstr(compose('PA_S%d_deg', 1:7));
fluxNames = cellstr(compose('Flux_S%d_1d', 1:7));
displayPANames = cellstr(compose('DisplayPA_S%d_deg', 1:7));
displayFluxNames = cellstr(compose('DisplayFlux_S%d', 1:7));
displayOrderNames = cellstr(compose('DisplayOrder_S%d', 1:7));
lowerNames = cellstr(compose('DisplayLowerEdge_S%d_deg', 1:7));
upperNames = cellstr(compose('DisplayUpperEdge_S%d_deg', 1:7));
requiredNames = [paNames, fluxNames, displayPANames, displayFluxNames, ...
    displayOrderNames, lowerNames, upperNames];
assert(all(ismember(requiredNames, pitchAngleTable.Properties.VariableNames)), ...
    'The current audit lacks one or more seven-sector display fields.');

usable = logical(pitchAngleTable.PADUsable);
assert(any(usable), 'No usable daily PAD record exists in the plotted window.');
pa = pitchAngleTable{:, paNames};
flux = pitchAngleTable{:, fluxNames};
displayPA = pitchAngleTable{:, displayPANames};
displayFlux = pitchAngleTable{:, displayFluxNames};
displayOrder = pitchAngleTable{:, displayOrderNames};
lowerEdge = pitchAngleTable{:, lowerNames};
upperEdge = pitchAngleTable{:, upperNames};
assert(isequaln(pa(usable, :), displayPA(usable, :)), ...
    'A displayed pitch angle differs from its original sector pitch angle.');
assert(isequaln(flux(usable, :), displayFlux(usable, :)), ...
    'A displayed flux differs from its original sector flux.');
assert(all(sum(isfinite(displayFlux(usable, :)), 2) == 7), ...
    'A usable record does not retain seven independent displayed fluxes.');
assert(all(sum(isfinite(lowerEdge(usable, :)) & ...
    isfinite(upperEdge(usable, :)), 2) == 7), ...
    'A usable record does not retain seven independent display cells.');
sortedOrder = sort(displayOrder(usable, :), 2);
assert(isequal(sortedOrder, repmat(1:7, size(sortedOrder, 1), 1)), ...
    'The display order is not a seven-sector permutation.');
assert(all(upperEdge(usable, :) >= lowerEdge(usable, :), 'all'), ...
    'A display cell has a negative pitch-angle width.');

validCellCount = sum(isfinite(displayFlux), 2);
displayMin = min(lowerEdge, [], 2, 'omitnan');
displayMax = max(upperEdge, [], 2, 'omitnan');
paMin = min(pa, [], 2, 'omitnan');
paMax = max(pa, [], 2, 'omitnan');
validation = table(pitchAngleTable.EpochUTC, ...
    pitchAngleTable.PADUsable, validCellCount, paMin, paMax, ...
    displayMin, displayMax, pitchAngleTable.SourceProduct, ...
    'VariableNames', {'EpochUTC', 'PADUsable', ...
    'IndependentDisplayCellCount', 'MinimumSectorPA_deg', ...
    'MaximumSectorPA_deg', 'DisplayLowerBound_deg', ...
    'DisplayUpperBound_deg', 'SourceProduct'});
validationFile = fullfile(reportFolder, ...
    '2020-E01_daily_seven_sector_display_validation.csv');
writetable(validation, validationFile);

%% verify source bytes and save a self-contained run audit
rawHashAfter = strings(numel(rawSourceFiles), 1);
for ii = 1:numel(rawSourceFiles)
    rawHashAfter(ii) = string(Case1_File_SHA256(char(rawSourceFiles(ii))));
end
assert(all(rawHashAfter == rawHashBefore), ...
    'At least one original CDF changed during the read-only calculation.');
rawSourceManifest = table(rawSourceRole, rawSourceFiles, rawHashBefore, ...
    rawHashAfter, rawHashAfter == rawHashBefore, ...
    'VariableNames', {'Role', 'SourceFile', 'SHA256Before', ...
    'SHA256After', 'BytesUnchanged'});
sourceManifestFile = fullfile(reportFolder, ...
    '2020-E01_original_CDF_source_manifest.csv');
writetable(rawSourceManifest, sourceManifestFile);

codeFiles = string({[mfilename('fullpath'), '.m']; ...
    fullfile(cfg.CodeRoot, 'Voyager_Case1_Plot_Events.m'); ...
    fullfile(cfg.CodeRoot, 'Case1_Config.m'); ...
    fullfile(cfg.CodeRoot, 'Case1_Predicted_LECP_Pointing.m'); ...
    fullfile(cfg.CodeRoot, 'Case1_LECP_Geometry.m')});
codeSHA256 = strings(numel(codeFiles), 1);
for ii = 1:numel(codeFiles)
    codeSHA256(ii) = string(Case1_File_SHA256(char(codeFiles(ii))));
end
codeManifest = table(codeFiles, codeSHA256, ...
    'VariableNames', {'SourceFile', 'SHA256'});

targetDay = datetime(2020, 7, 30, 'TimeZone', 'UTC');
targetRows = find(usable & ...
    dateshift(pitchAngleTable.EpochUTC, 'start', 'day') == targetDay);
july30 = struct('Found', false);
if ~isempty(targetRows)
    row = targetRows(1);
    july30.Found = true;
    july30.EpochUTC = pitchAngleTable.EpochUTC(row);
    july30.SectorPA_deg = pa(row, :);
    july30.DisplayLowerEdge_deg = lowerEdge(row, :);
    july30.DisplayUpperEdge_deg = upperEdge(row, :);
    july30.IndependentDisplayCellCount = validCellCount(row);
    july30.DisplayOverallRange_deg = [displayMin(row), displayMax(row)];
end

result = struct;
result.GeneratedUTC = datetime('now', 'TimeZone', 'UTC');
result.EntryPoint = string([mfilename('fullpath'), '.m']);
result.CurrentCoreRenderer = string(fullfile(cfg.CodeRoot, ...
    'Voyager_Case1_Plot_Events.m'));
result.Legacy2020ProgramUsed = false;
result.DirectOriginalCDFInput = true;
result.PitchAngleMethod = "predicted_ck full 3-D";
result.SourcePriority = "l1_first with complete-bin L2 fallback";
result.SectorMergeApplied = false;
result.SectorPolicy = [ ...
    "S1-S7 kept independently; no angle grouping, angle averaging, " + ...
    "flux averaging, or artificial angular offset."];
result.PlotStartUTC = expectedStart;
result.PlotEndUTCExclusive = expectedEnd;
result.FigureFile = figureFile;
result.FigureSHA256 = string(Case1_File_SHA256(char(figureFile)));
result.PitchAngleAuditFile = pitchAngleAuditFile;
result.ValidationFile = string(validationFile);
result.SourceManifestFile = string(sourceManifestFile);
result.LogFile = string(logFile);
result.Report = report;
result.Validation = validation;
result.July30 = july30;
result.RawSourceManifest = rawSourceManifest;
result.CodeManifest = codeManifest;
result.RendererCodeManifest = saved.codeManifest;
result.SourceLECP = saved.sourceLECP;
result.SourceMAG = saved.sourceMAG;
resultFile = fullfile(reportFolder, ...
    'Run_Case1_2020E01_Current3D_NoSectorMerge_result.mat');
result.ResultFile = string(resultFile);
save(resultFile, 'result', '-v7.3');

copyfile(fullfile(cfg.CodeRoot, 'README_数据处理与假设.md'), ...
    fullfile(reportFolder, 'README_数据处理与假设.md'), 'f');
copyfile(fullfile(cfg.CodeRoot, 'README_预测姿态与扇区几何.md'), ...
    fullfile(reportFolder, 'README_预测姿态与扇区几何.md'), 'f');

fprintf('Current 3-D no-merge figure: %s\n', figureFile);
fprintf('Usable PAD records checked: %d; each contains seven independent cells.\n', ...
    nnz(usable));
fprintf('Run audit: %s\n', resultFile);
clear logCleanup
diary('off');
end

function files = selectYear(files, year)
files = string(files(:));
yearFolder = [filesep, sprintf('%04d', year), filesep];
files = files(contains(files, yearFolder));
end
