function result = Run_Florinski2008_Figure4(varargin)
%Run_Florinski2008_Figure4 Plot the four Figure 4 days with the current method.
%   Voyager 1, 2004 DOY 221--224 = 2004-08-08 through 2004-08-11 UTC.
%   Calls the existing event program for daily/hourly overview figures. A
%   adapter plots the four daily PADs together. Missing L2 bins may use
%   approved L1 per-sector rate means with historical G*dE conversion.
%   Magnetic matching and 3-D geometry are unchanged. No paper-specific
%   background removal or fitting is introduced.
%
%   Run_Florinski2008_Figure4('Overwrite',true) regenerates only these outputs.
%   Reference: https://doi.org/10.1029/2007JA012859, Figure 4 and section 5.

%% options and the exact requested interval
parser = inputParser;
addParameter(parser, 'RunPlots', true, @isLogicalScalar);
addParameter(parser, 'Overwrite', false, @isLogicalScalar);
addParameter(parser, 'Visible', false, @isLogicalScalar);
parse(parser, varargin{:});
opts = parser.Results;
cfg = Case1_Config;
Case1_Add_IRFU_Path(cfg.IRFURoot);
cfg.ContextDays = 0;
cfg.LECPSourcePriority = 'l2_first'; % Preserve the fixed four-day reference protocol.
cfg.ExportPeakPAD = false;
cfg.OutputRoot = fullfile(cfg.OutputRoot, 'Florinski2008_Figure4');
cfg.LECPNativeDailyCDFs = annualFiles(cfg.DataRoot, '1d', 'daily');
cfg.LECPNativeHourlyCDFs = annualFiles(cfg.DataRoot, '1h', 'hourly');
if ~isfolder(cfg.OutputRoot), mkdir(cfg.OutputRoot); end
copyfile(fullfile(cfg.CodeRoot,'README_Level1补充通路.md'), ...
    fullfile(cfg.OutputRoot,'README_Level1补充通路.md'),'f');

eventID = "Florinski2008-Figure4";
startUTC = datetime(2004, 8, 8, 'TimeZone', 'UTC');
endUTCInclusive = datetime(2004, 8, 11, 'TimeZone', 'UTC');
endUTCExclusive = datetime(2004, 8, 12, 'TimeZone', 'UTC');
catalog = table(eventID, startUTC, endUTCInclusive, endUTCExclusive, 1, ...
    'VariableNames', {'EventID','StartUTC','EndUTCInclusive', ...
    'EndUTCExclusive','Spacecraft'});
catalog.StartUTC.Format = 'yyyy-MM-dd';
catalog.EndUTCInclusive.Format = 'yyyy-MM-dd';
catalog.EndUTCExclusive.Format = 'yyyy-MM-dd';
cfg.LECPLevel1CDFs = Case1_Restrict_Source_Years(cfg.LECPLevel1CDFs,catalog,0);
catalogFile = fullfile(cfg.OutputRoot, 'Florinski2008_Figure4_event.csv');
% This CSV is the existing program's event-catalog interface, not flux data.
writetable(catalog, catalogFile);

%% preserve source identity and current scientific settings
result = struct;
result.CreatedUTC = datetime('now', 'TimeZone', 'UTC');
result.Config = cfg;
result.Catalog = catalog;
result.ReferenceURL = "https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2007JA012859";
result.Scope = "Only V1 Figure 4 days: [2004-08-08 00:00,2004-08-12 00:00) UTC; no extra event search.";
result.Methods = [ ...
    "Direct original NASA annual LECP CDFs and original monthly COHO 1h CDF."; ...
    "Retain complete L2 bins at original Epoch, flux and sigma; discard DeltaT<0 under the existing time policy."; ...
    "Where a UTC bin has no complete positive seven-sector L2 row, use complete L1 per-sector arithmetic rate means at bin center; no sector-wise L1/L2 mixing."; ...
    "L1 rate-to-flux factor=1/[0.44*(1.78-0.57)] from the restored historical path; this is not asserted to be official L2 calibration."; ...
    "L1 sigma=sqrt(sum(sigma_i^2))/N only when all contributing uncertainties exist; source records and DeltaT are retained in the audit."; ...
    "CDF fill/range handling and the existing seven positive finite sector-flux/finite-PA requirement remain unchanged."; ...
    "B = mean of complete finite COHO BR/BT/BN vectors in the particle Epoch's UTC day/hour, using the existing program."; ...
    "No nearest-B fallback, magnetic interpolation, missing-flux filling, smoothing or new scientific threshold."; ...
    "Approved predicted CK at L2 original Epoch or L1 bin center; nominal P1 sector centers; full 3-D SC to RTN; particle velocity=-look."; ...
    "Predicted attitude is not telemetry reconstruction; actual mounting offsets/roll corrections are unavailable."; ...
    "S1--S7 are plotted; S8 remains a diagnostic, with no background subtraction."; ...
    "Four daily panels use their own Jmax and sigma/Jmax with fixed denominator, PA 0--180 deg, unmerged points and no fit."; ...
    "The source energy bounds remain unchanged in the audit; 0.57--1.78 MeV is the display convention and separately the adopted width in the L1 conversion."; ...
    "This runs the current method on the paper's dates; it does not claim to reproduce the paper's background correction or fitted curves."];
result.PlotsExecuted = logical(opts.RunPlots);
result.FigureFiles = strings(0, 1);
result.PitchAngleAuditFiles = strings(0, 1);
reports = cell(2, 1);
sourceManifests = cell(2, 1);
padTables = cell(2, 1);

%% existing daily and hourly event calculations
cadences = {'day','hour'};
cadenceFolders = {'1d','1h'};
figureGroups = {'Epoch_daily','Epoch_hourly'};
nativeFiles = {cfg.LECPNativeDailyCDFs, cfg.LECPNativeHourlyCDFs};
for ii = 1:2
    runCfg = cfg;
    runCfg.PADCadence = cadences{ii};
    runCfg.OutputRoot = fullfile(cfg.OutputRoot, figureGroups{ii});
    runCfg.PitchAngleDataFolder = fullfile(cfg.DataRoot, 'voyager1', ...
        'lecp', cadenceFolders{ii}, 'derived', 'pitch_angle', '2004', ...
        'florinski2008_figure4');
    reportFolder = fullfile(runCfg.PitchAngleDataFolder, 'reports');
    if ~isfolder(runCfg.OutputRoot), mkdir(runCfg.OutputRoot); end
    if ~isfolder(reportFolder), mkdir(reportFolder); end
    sourceManifests{ii} = Case1_Check_Data(runCfg, catalog);
    writetable(sourceManifests{ii}, fullfile(reportFolder, 'SourceManifest.csv'));
    if ~logical(opts.RunPlots), continue; end

    reports{ii} = Voyager_Case1_Plot_Events( ...
        'Spacecraft', 1, 'DataRoot', cfg.DataRoot, ...
        'CatalogFile', catalogFile, 'OutputFolder', runCfg.OutputRoot, ...
        'ReportFolder', reportFolder, 'ReportTag', 'Florinski2008_Figure4', ...
        'ContextMonths', 0, 'ContextDays', 0, ...
        'ShowEventBoundaries', cfg.ShowEventBoundaries, ...
        'Overwrite', opts.Overwrite, 'Visible', opts.Visible, ...
        'ExportDPI', cfg.ExportDPI, ...
        'MAGGapHours', cfg.MAGGapHours, 'FluxGapHours', cfg.FluxGapHours, ...
        'LECPDailyAverage', cfg.LECPDailyAverage, ...
        'CRSDisplay', 'lecp_p1_pitch_angle', ...
        'LECPNativeCDFs', nativeFiles{ii}, 'PADCadence', cadences{ii}, ...
        'LECPLevel1Fallback', cfg.LECPLevel1Fallback, ...
        'LECPLevel1CDFs', cfg.LECPLevel1CDFs, ...
        'LECPSourcePriority', cfg.LECPSourcePriority, ...
        'HourlyAttitudeApproved', cfg.HourlyAttitudeApproved, ...
        'AccumulationPolicy', cfg.AccumulationPolicy, ...
        'LECPSectorAverageDays', cfg.LECPSectorAverageDays, ...
        'PitchAngleMethod', cfg.PitchAngleMethod, ...
        'PredictedAttitudeApproved', cfg.PredictedAttitudeApproved, ...
        'NominalLECPGeometryApproved', cfg.NominalLECPGeometryApproved, ...
        'AttitudeDailyHourUTC', cfg.AttitudeDailyHourUTC, ...
        'LECPSectorPointingFile', cfg.LECPSectorPointingFile, ...
        'LECPBackgroundMode', cfg.LECPBackgroundMode, ...
        'PitchMergeToleranceDeg', cfg.PitchMergeToleranceDeg, ...
        'ColorPercentiles', cfg.ColorPercentiles, ...
        'ExportPitchAngleTable', false, ...
        'PitchAngleDataFolder', runCfg.PitchAngleDataFolder, ...
        'P1DisplayEnergyMeV', cfg.P1DisplayEnergyMeV, ...
        'ExportPeakPAD', false, ...
        'LineYMarginFraction', cfg.LineYMarginFraction, ...
        'CRSColorLimits', cfg.CRSColorLimits);
    current = reports{ii};
    if height(current) ~= 1 || any(contains(string(current.Status), 'error'))
        error('VoyagerFigure4:OverviewFailed', 'Current event program failed: %s', ...
            strjoin(string(current.Notes), '; '));
    end
    auditFile = string(current.PitchAngleAuditFile);
    if ~isfile(auditFile) || ~isfile(string(current.FigureFile))
        error('VoyagerFigure4:MissingOutput', 'The overview or its numerical audit is missing.');
    end
    saved = load(auditFile, 'pitchAngleTable');
    padTables{ii} = saved.pitchAngleTable;
    if ~isempty(padTables{ii})
        time = padTables{ii}.EpochUTC;
        assert(all(time >= startUTC & time < endUTCExclusive), ...
            'The current event program returned a record outside Figure 4.');
    end
    result.FigureFiles(end+1, 1) = string(current.FigureFile);
    result.PitchAngleAuditFiles(end+1, 1) = auditFile;
end
result.Reports = reports;
result.SourceManifests = sourceManifests;

%% four specified daily records, using the table just computed from CDF
validationFolder = fullfile(cfg.DataRoot, 'voyager1', 'lecp', ...
    'validation', 'florinski_figure4');
if ~isfolder(validationFolder), mkdir(validationFolder); end
if logical(opts.RunPlots)
    figureFile = fullfile(cfg.OutputRoot, ...
        'V1_Florinski2008_Figure4_20040808_20040811_daily_PAD.png');
    fixedAuditFile = fullfile(validationFolder, 'Florinski2008_Figure4_daily_PAD.mat');
    if ~logical(opts.Overwrite) && isfile(figureFile)
        if ~isfile(fixedAuditFile)
            error('VoyagerFigure4:ExistingFigureAudit', ...
                'Existing four-day figure has no audit; use Overwrite=true to regenerate.');
        end
        prior = load(fixedAuditFile, 'figure4Audit');
        figure4Audit = prior.figure4Audit;
    else
        plotOpts = struct('Visible', opts.Visible, 'ExportDPI', cfg.ExportDPI, ...
            'P1DisplayEnergyMeV', cfg.P1DisplayEnergyMeV);
        figure4Audit = Case1_Plot_Florinski_Figure4_PAD( ...
            padTables{1}, figureFile, plotOpts);
        figure4Audit.PitchAngleAuditFile = result.PitchAngleAuditFiles(1);
        figure4Audit.ReferenceURL = result.ReferenceURL;
        figure4Audit.SourceManifest = sourceManifests{1};
        save(fixedAuditFile, 'figure4Audit', '-v7.3');
    end
    result.FigureFiles(end+1, 1) = string(figureFile);
    result.FourDayAuditFile = string(fixedAuditFile);
    result.DailyPAD = padTables{1};
    result.HourlyPAD = padTables{2};
    result.FourDayPAD = figure4Audit;
end

%% code hashes and a complete numerical audit under the Voyager data root
codeNames = {'Run_Florinski2008_Figure4.m', 'Case1_Plot_Florinski_Figure4_PAD.m', ...
    'Voyager_Case1_Plot_Events.m', 'Case1_Config.m', 'Case1_Read_LECP_CDFs.m', ...
    'Voyager_Read_CDF_Product.m', 'Case1_Select_LECP_Epoch.m', ...
    'Case1_Read_LECP_Rates.m', 'Case1_Apply_L1_Fallback.m', ...
    'Case1_Predicted_LECP_Pointing.m', 'Case1_Read_Predicted_Attitude.m', ...
    'Case1_LECP_Geometry.m', 'Case1_Attitude_Files.m'};
codeFiles = string(fullfile(cfg.CodeRoot, codeNames)).';
codeSHA256 = strings(size(codeFiles));
for ii = 1:numel(codeFiles)
    codeSHA256(ii) = string(Case1_File_SHA256(char(codeFiles(ii))));
end
result.CodeManifest = table(codeFiles, codeSHA256, ...
    'VariableNames', {'SourceFile','SHA256'});
stamp = char(datetime('now', 'TimeZone', 'UTC', 'Format', 'yyyyMMdd_HHmmss_SSS'));
result.AuditFile = string(fullfile(validationFolder, ...
    ['Florinski2008_Figure4_run_', stamp, '.mat']));
save(result.AuditFile, 'result', '-v7.3');
fprintf('Figure 4 interval: 2004-08-08 through 2004-08-11 UTC.\n');
disp(result.FigureFiles);
fprintf('Numerical audit: %s\n', result.AuditFile);
end

function files = annualFiles(dataRoot, cadence, product)
folder = fullfile(dataRoot, 'voyager1', 'lecp', cadence, 'l2', ...
    'sectored_flux', '2004');
entries = dir(fullfile(folder, ...
    ['voyager-1_lecp_lev-2-', product, '-avg_20040101_v*.cdf']));
if numel(entries) ~= 1
    error('VoyagerFigure4:AnnualCDF', ...
        'Expected one verified original 2004 %s CDF in %s.', product, folder);
end
files = string(fullfile(entries.folder, entries.name));
end

function tf = isLogicalScalar(value)
tf = (islogical(value) || isnumeric(value)) && isscalar(value);
end
