function result = Run_Case1_Additional_L1_First(eventDate, cadence, selectionAudit)
%Run_Case1_Additional_L1_First Reuse the current pipeline for one added case.
%   Date-specific wrappers supply the documented event selection only.
%   Original batch manifests and all other event images remain untouched.
%   Author: Codex; Modified: 2026-09-04

%% explicit UTC date and existing cadence
validateattributes(eventDate, {'datetime'}, {'scalar'});
assert(~isnat(eventDate) && strcmp(eventDate.TimeZone, 'UTC'), 'Supply a finite UTC event date.');
assert(eventDate == dateshift(eventDate, 'start', 'day'), 'Supply the event day at midnight.');
if nargin < 2, cadence = 'both'; end
if nargin < 3, selectionAudit = struct; end
cadence = validatestring(cadence, {'day', 'hour', 'both'});
if strcmp(cadence, 'both')
    result.Day = Run_Case1_Additional_L1_First(eventDate, 'day', selectionAudit);
    result.Hour = Run_Case1_Additional_L1_First(eventDate, 'hour', selectionAudit);
    return
end
createdUTC = datetime('now', 'TimeZone', 'UTC');
cfg = Case1_Config;
cfg.ContextDays = 3;
cfg.LECPSourcePriority = 'l1_first';
cfg.PADCadence = cadence;
cfg.ExportPeakPAD = strcmp(cadence, 'hour');
Case1_Add_IRFU_Path(cfg.IRFURoot);

%% one supplementary case; no invented original slide/line attribution
dateTag = char(datetime(eventDate, 'Format', 'yyyyMMdd'));
eventID = string(['Case1-Added-', dateTag]);
catalog = table(eventID, eventDate, eventDate, eventDate+days(1), ...
    1, NaN, NaN, 'VariableNames', {'EventID', 'StartUTC', ...
    'EndUTCInclusive', 'EndUTCExclusive', 'Spacecraft', ...
    'SourceSlide', 'SourceLine'});
catalog.StartUTC.Format = 'yyyy-MM-dd';
catalog.EndUTCInclusive.Format = 'yyyy-MM-dd';
catalog.EndUTCExclusive.Format = 'yyyy-MM-dd';

selectionAudit.EventID = eventID;
selectionAudit.EventDateUTC = eventDate;
selectionAudit.WindowStartUTC = eventDate-days(3);
selectionAudit.WindowEndUTCExclusive = eventDate+days(4);
selectionAudit.PADSelection = 'Current seven-day maximum S1-S7 flux; two nearest usable records on each side.';
selectionAudit.SciencePolicy = 'Current L1-first means, errors and legacy conversion; three-dimensional predicted attitude; same-bin magnetic field; no new quality thresholds or background correction.';

%% separate supplementary records; established picture folders are reused
dataFolder = fullfile(cfg.DataRoot, 'voyager1', 'lecp', 'validation', ...
    ['supplemental_', dateTag]);
reportFolder = fullfile(cfg.OutputRoot, ['Supplemental_', dateTag], cadence);
if ~isfolder(dataFolder), mkdir(dataFolder); end
if ~isfolder(reportFolder), mkdir(reportFolder); end
catalogFile = fullfile(dataFolder, ['Case1_Added_', dateTag, '_catalog.csv']);
writetable(catalog, catalogFile);
selectionFile = fullfile(dataFolder, ['Case1_Added_', dateTag, '_selection.mat']);
save(selectionFile, 'selectionAudit', 'catalog', '-v7.3');

nativeCDFs = cfg.LECPNativeDailyCDFs;
outputGroup = 'Epoch_daily';
if strcmp(cadence, 'hour')
    nativeCDFs = cfg.LECPNativeHourlyCDFs;
    outputGroup = 'Epoch_hourly';
    cfg.PitchAngleDataFolder = fullfile(cfg.DataRoot, 'voyager1', 'lecp', ...
        '1h', 'derived', 'pitch_angle', '2013-2021');
end
cfg.OutputRoot = fullfile(cfg.OutputRoot, outputGroup);
cfg.CatalogFile = catalogFile;
cfg.SourceManifestFile = fullfile(reportFolder, 'source_manifest.csv');
cfg.RunAuditFile = fullfile(reportFolder, 'data_processing_assumptions.txt');
cfg.LECPNativeDailyCDFs = Case1_Restrict_Source_Years( ...
    cfg.LECPNativeDailyCDFs, catalog, cfg.ContextDays);
cfg.LECPNativeHourlyCDFs = Case1_Restrict_Source_Years( ...
    cfg.LECPNativeHourlyCDFs, catalog, cfg.ContextDays);
cfg.LECPLevel1CDFs = Case1_Restrict_Source_Years( ...
    cfg.LECPLevel1CDFs, catalog, cfg.ContextDays);
nativeCDFs = Case1_Restrict_Source_Years(nativeCDFs, catalog, cfg.ContextDays);

%% original CDF and kernel preflight, with existing method documentation
sourceManifest = Case1_Check_Data(cfg, catalog);
writetable(sourceManifest, cfg.SourceManifestFile);
Case1_Write_Audit(cfg.RunAuditFile, cfg, catalog, sourceManifest, true);
readmeNames = {'README_数据处理与假设.md', 'README_Level1补充通路.md', ...
    'README_三天窗口_L1优先.md', 'README_预测姿态与扇区几何.md', ...
    ['README_补充事件', dateTag, '.md']};
for ii = 1:numel(readmeNames)
    copyfile(fullfile(cfg.CodeRoot, readmeNames{ii}), ...
        fullfile(reportFolder, readmeNames{ii}), 'f');
end

%% unchanged production renderer; overwrite is scoped to the new EventID
reportV1 = Voyager_Case1_Plot_Events( ...
    'Spacecraft', 1, ...
    'DataRoot', cfg.DataRoot, ...
    'OutputFolder', cfg.OutputRoot, ...
    'CatalogFile', catalogFile, ...
    'ReportFolder', reportFolder, ...
    'ReportTag', ['Case1_Added_', dateTag, '_L1_First'], ...
    'ContextMonths', 0, ...
    'ContextDays', cfg.ContextDays, ...
    'ShowEventBoundaries', cfg.ShowEventBoundaries, ...
    'Overwrite', true, ...
    'Visible', false, ...
    'ExportDPI', cfg.ExportDPI, ...
    'MAGGapHours', cfg.MAGGapHours, ...
    'FluxGapHours', cfg.FluxGapHours, ...
    'LECPDailyAverage', cfg.LECPDailyAverage, ...
    'CRSDisplay', 'lecp_p1_pitch_angle', ...
    'LECPSectoredDailyCDF', cfg.LECPSectoredDailyCDF, ...
    'LECPNativeCDFs', nativeCDFs, ...
    'LECPLevel1Fallback', cfg.LECPLevel1Fallback, ...
    'LECPLevel1CDFs', cfg.LECPLevel1CDFs, ...
    'LECPSourcePriority', cfg.LECPSourcePriority, ...
    'PADCadence', cfg.PADCadence, ...
    'HourlyAttitudeApproved', cfg.HourlyAttitudeApproved, ...
    'AccumulationPolicy', cfg.AccumulationPolicy, ...
    'LECPSectorAverageDays', cfg.LECPSectorAverageDays, ...
    'PitchAngleMethod', cfg.PitchAngleMethod, ...
    'PredictedAttitudeApproved', cfg.PredictedAttitudeApproved, ...
    'NominalLECPGeometryApproved', cfg.NominalLECPGeometryApproved, ...
    'AttitudeDailyHourUTC', cfg.AttitudeDailyHourUTC, ...
    'LECPSectorPointingFile', cfg.LECPSectorPointingFile, ...
    'LECPBackgroundMode', cfg.LECPBackgroundMode, ...
    'PitchMergeToleranceDeg', cfg.PitchMergeToleranceDeg, ...
    'ColorPercentiles', cfg.ColorPercentiles, ...
    'ExportPitchAngleTable', cfg.ExportPitchAngleTable, ...
    'PitchAngleDataFolder', cfg.PitchAngleDataFolder, ...
    'P1DisplayEnergyMeV', cfg.P1DisplayEnergyMeV, ...
    'ExportPeakPAD', cfg.ExportPeakPAD, ...
    'PeakPADFolder', cfg.PeakPADFolder, ...
    'PeakPADDataFolder', cfg.PeakPADDataFolder, ...
    'LineYMarginFraction', cfg.LineYMarginFraction, ...
    'CRSColorLimits', cfg.CRSColorLimits);

%% one-cadence run record, without replacing any original batch manifest
result = struct('CreatedUTC', createdUTC, 'Cadence', string(cadence), ...
    'ContextDays', cfg.ContextDays, 'SourcePriority', string(cfg.LECPSourcePriority), ...
    'Catalog', catalog, 'SelectionAudit', selectionAudit, ...
    'SelectionAuditFile', string(selectionFile), 'ReportFolder', string(reportFolder));
result.Run = struct('Config', cfg, 'Catalog', catalog, ...
    'SourceManifest', sourceManifest, 'ReportV1', reportV1, ...
    'ReportV2', table, 'PlotsExecuted', true);
result.CodeFiles = string(fullfile(cfg.CodeRoot, ...
    {'Run_Case1_Additional_L1_First.m', ['Run_Case1_Added_', dateTag, '_L1_First.m'], 'Case1_Config.m', ...
    'Case1_Check_Data.m', 'Case1_Write_Audit.m', ...
    'Voyager_Case1_Plot_Events.m'})).';
result.CodeSHA256 = strings(size(result.CodeFiles));
for ii = 1:numel(result.CodeFiles)
    result.CodeSHA256(ii) = string(Case1_File_SHA256(char(result.CodeFiles(ii))));
end
stamp = char(datetime('now', 'TimeZone', 'UTC', 'Format', 'yyyyMMdd_HHmmss_SSS'));
result.AuditFile = string(fullfile(dataFolder, ['replot_', cadence, '_', stamp, '.mat']));
save(result.AuditFile, 'result', '-v7.3');
fprintf('Supplementary %s %s run audit: %s\n', dateTag, cadence, result.AuditFile);
assert(height(reportV1) == 1 && string(reportV1.EventID) == eventID, ...
    'The supplementary run must contain exactly the new case.');
assert(~any(contains(string(reportV1.Status), 'error')), ...
    'Supplementary plot failed; inspect its saved run report.');
end
