function audit = Verify_V1_Wave_Sources
% Read-only source validation; no measured-data spectral calculation.
root=fileparts(mfilename('fullpath'));
addpath(fullfile(fileparts(root),'Case1_PPT_VerticalLine_Events_7d_fu'));
Case1_Add_IRFU_Path('C:/Users/Administrator/Documents/irfu-matlab-master');
cfg.DataRoot='Z:/SPART-WORK/Data/Voyager';
cfg.StartUTC=datetime(2012,8,25,'TimeZone','UTC');
cfg.StopUTC=datetime(2021,12,17,'TimeZone','UTC');
out='C:/Users/Administrator/Documents/Recovery-Work-Voyager_betatron/V1_Wave_1Day_30Days';
if ~isfolder(out), mkdir(out); end
[raw,sources,duplicates]=V1_Wave_Read_Hourly(cfg);
pwsFile=fullfile(cfg.DataRoot,'voyager1','pws','calibrated','spectrum_analyzer', ...
    'native','2012','vg1_pws_lr_20120825_v5.30.cdf');
d=dataobj(pwsFile); frequency=getv(d,'frequency'); electric=getv(d,'electric_field');
epoch=getv(d,'epoch'); time=EpochTT(int64(epoch.data(:))).epochUnix;
pws=struct('Dataset','VG1_PWS_LR','SourceFile',pwsFile, ...
    'SHA256',Case1_File_SHA256(pwsFile),'Frequency',frequency, ...
    'ElectricFieldMetadata',rmfield(electric,'data'),'Records',electric.nrec, ...
    'FirstUTC',datetime(min(time),'ConvertFrom','posixtime','TimeZone','UTC'), ...
    'LastUTC',datetime(max(time),'ConvertFrom','posixtime','TimeZone','UTC'), ...
    'RequestedFrequencyHz',[1/(30*86400),1/86400], ...
    'OverlapRequestedBand',any(frequency.data>=1/(30*86400) & frequency.data<=1/86400));
assert(~pws.OverlapRequestedBand,'Revisit electric-field availability.');
audit=struct('MAGRecords',height(raw),'ValidRTNVectors',nnz(all(isfinite(raw.B_RTN_nT),2)), ...
    'ValidMagnitude',nnz(isfinite(raw.Bmag_nT)),'SourceCDFs',height(sources), ...
    'IdenticalDuplicateRecords',height(duplicates),'PWS',pws);
save(fullfile(out,'source_verification.mat'),'audit','raw','sources','duplicates','-v7.3');
writetable(sources(:,{'SourceFile','SHA256','RecordsInRange'}),fullfile(out,'source_manifest.csv'));
writetable(raw,fullfile(out,'hourly_input_audit.csv'));
fid=fopen(fullfile(out,'electric_field_check.json'),'w','n','UTF-8');
cleanup=onCleanup(@()fclose(fid));
summary=struct('Dataset',pws.Dataset,'RepresentativeCDF',pws.SourceFile, ...
    'SHA256',pws.SHA256,'FrequencyHz',double(frequency.data), ...
    'Units',electric.UNITS,'Records',electric.nrec,'OverlapRequestedBand',false, ...
    'DownloadScope','One representative original CDF; not full 2012--2021 archive', ...
    'Conclusion','No suitable electric-field measurement in 1--30 day period band');
fprintf(fid,'%s',jsonencode(summary,PrettyPrint=true));
disp(audit);
end
